/**
 * C Full Course — Modules 3-15, authored content (lighter-detail pass).
 * Same shape/style as Backend/javaModules3to15.js.
 */
let AUTO_ID = 91000;
function qid() { AUTO_ID += 1; return `cq${AUTO_ID}`; }
function lesson(order, title, estMinutes, learn, practice, test) {
  return { order, title, est_minutes: estMinutes, content_ready: true, learn, practice, test };
}
function quickCheck(q) {
  if (q.type === 'code') return { questions: [{ id: qid(), type: 'code', text: q.text, language: 'c', starter_code: q.starter_code, test_cases: q.test_cases }] };
  return { questions: [{ id: qid(), type: 'mcq', text: q.text, options: q.options, correct_index: q.correct_index }] };
}
function ex(code, output) { return { code, output }; }
const MAIN = (body) => `#include <stdio.h>\n\nint main() {\n${body}\n    return 0;\n}`;

const M3 = [
  lesson(1, 'Array Basics', 6, { explanation: 'An array stores multiple values of the same type in one variable, accessed by index starting at 0.', syntax: 'int nums[3] = {10, 20, 30};', examples: [ex(MAIN('    int nums[3] = {10, 20, 30};\n    printf("%d\\n", nums[1]);'), '20')], important_points: ['C does not check array bounds — reading/writing outside the array is undefined behavior, not a safe error.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    int nums[3] = {10, 20, 30};\n    printf("%d\\n", nums[1]);') }, quickCheck({ text: 'What is nums[0] in int nums[3] = {10,20,30}?', options: ['10', '20', '30', 'Undefined'], correct_index: 0 })),
  lesson(2, '1D Arrays', 6, { explanation: 'A 1D array is a single row of elements — you loop through it with an index from 0 to length-1.', syntax: 'for (int i = 0; i < 3; i++) { ... arr[i] ... }', examples: [ex(MAIN('    int arr[3] = {1, 2, 3};\n    for (int i = 0; i < 3; i++) {\n        printf("%d ", arr[i]);\n    }\n    printf("\\n");'), '1 2 3')], important_points: ['sizeof(arr)/sizeof(arr[0]) is the common way to compute an array\'s length in C.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    int arr[3] = {1, 2, 3};\n    for (int i = 0; i < 3; i++) {\n        printf("%d ", arr[i]);\n    }\n    printf("\\n");') }, quickCheck({ text: 'Which loop variable range visits every element of a 3-element array?', options: ['1 to 3', '0 to 2', '0 to 3', '1 to 2'], correct_index: 1 })),
  lesson(3, '2D Arrays', 6, { explanation: 'A 2D array is a grid — declared with two sizes and accessed with two indexes.', syntax: 'int grid[2][2] = {{1,2},{3,4}};', examples: [ex(MAIN('    int grid[2][2] = {{1, 2}, {3, 4}};\n    printf("%d\\n", grid[1][0]);'), '3')], important_points: ['grid[row][col] — the first index is the row, the second is the column.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    int grid[2][2] = {{1, 2}, {3, 4}};\n    printf("%d\\n", grid[1][0]);') }, quickCheck({ text: 'For int grid[2][2] = {{1,2},{3,4}}, what is grid[0][1]?', options: ['1', '2', '3', '4'], correct_index: 1 })),
  lesson(4, 'Array Practice', 7, { explanation: 'Combine a loop with an array to compute something, like a sum.', syntax: '', examples: [ex(MAIN('    int nums[4] = {1, 2, 3, 4};\n    int sum = 0;\n    for (int i = 0; i < 4; i++) sum += nums[i];\n    printf("%d\\n", sum);'), '10')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    int nums[4] = {5, 6, 7, 8};\n    // print the sum of nums\n') }, quickCheck({ type: 'code', text: 'Given int nums[4] = {5,6,7,8}, print their sum.', starter_code: MAIN('    int nums[4] = {5, 6, 7, 8};\n    // print the sum\n'), test_cases: [{ input: '', expected_output: '26' }] })),
  lesson(5, 'String Basics', 6, { explanation: 'In C, a string is just a char array ending in a special null character \'\\0\' that marks where the text stops.', syntax: 'char name[] = "Sam";', examples: [ex(MAIN('    char name[] = "Sam";\n    printf("%s\\n", name);'), 'Sam')], important_points: ['%s in printf prints a string up to (but not including) its terminating \'\\0\'.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    char name[] = "Sam";\n    printf("%s\\n", name);') }, quickCheck({ text: 'What character marks the end of a C string?', options: ['A space', '\\0 (null character)', '\\n', 'The last letter'], correct_index: 1 })),
  lesson(6, 'String Functions', 7, { explanation: 'The <string.h> library provides ready-made functions for common string tasks: strlen, strcpy, strcat, strcmp.', syntax: '#include <string.h>\nstrlen(str);', examples: [ex('#include <stdio.h>\n#include <string.h>\n\nint main() {\n    char name[] = "Sam";\n    printf("%d\\n", (int)strlen(name));\n    return 0;\n}', '3')], important_points: ['strcmp returns 0 when two strings are equal — not 1/true like you might expect.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n#include <string.h>\n\nint main() {\n    char name[] = "Sam";\n    printf("%d\\n", (int)strlen(name));\n    return 0;\n}' }, quickCheck({ text: 'What does strcmp("a", "a") return?', options: ['1', '-1', '0', 'true'], correct_index: 2 })),
  lesson(7, 'String Practice', 7, { explanation: 'Practice combining strcpy and strcat to build up a string.', syntax: '', examples: [ex('#include <stdio.h>\n#include <string.h>\n\nint main() {\n    char greeting[20] = "Hi ";\n    strcat(greeting, "Sam");\n    printf("%s\\n", greeting);\n    return 0;\n}', 'Hi Sam')], important_points: ['The destination buffer for strcat must already be big enough to hold the combined result.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n#include <string.h>\n\nint main() {\n    char greeting[30] = "Hello ";\n    strcat(greeting, "World");\n    printf("%s\\n", greeting);\n    return 0;\n}' }, quickCheck({ text: 'What does strcat(dest, src) do?', options: ['Compares two strings', 'Copies src over dest', 'Appends src to the end of dest', 'Deletes src'], correct_index: 2 }))
];

const M4 = [
  lesson(1, 'Pointer Introduction', 7, { explanation: 'A pointer is a variable that stores the memory address of another variable.', syntax: 'int x = 5;\nint *p = &x;', examples: [ex(MAIN('    int x = 5;\n    int *p = &x;\n    printf("%d\\n", *p);'), '5')], important_points: ['& gets an address; * (dereference) gets the value stored at an address.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    int x = 5;\n    int *p = &x;\n    printf("%d\\n", *p);') }, quickCheck({ text: 'What does *p do when p is a pointer?', options: ['Gets the address of p', 'Gets the value p points to', 'Multiplies p', 'Deletes p'], correct_index: 1 })),
  lesson(2, 'Pointer Arithmetic', 6, { explanation: 'Adding to a pointer moves it forward by that many elements of its type, not by raw bytes.', syntax: 'p + 1;', examples: [ex(MAIN('    int arr[3] = {10, 20, 30};\n    int *p = arr;\n    printf("%d\\n", *(p + 1));'), '20')], important_points: ['p + 1 on an int* moves 4 bytes (one int), not 1 byte.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    int arr[3] = {10, 20, 30};\n    int *p = arr;\n    printf("%d\\n", *(p + 1));') }, quickCheck({ text: 'If p points to arr[0], what does *(p + 1) give you?', options: ['arr[0]', 'arr[1]', 'The address of arr', 'A syntax error'], correct_index: 1 })),
  lesson(3, 'Pointers and Arrays', 6, { explanation: 'An array\'s name decays into a pointer to its first element, so arr[i] and *(arr + i) mean the same thing.', syntax: 'arr[i] == *(arr + i)', examples: [ex(MAIN('    int arr[3] = {1, 2, 3};\n    printf("%d\\n", *(arr + 2));'), '3')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    int arr[3] = {1, 2, 3};\n    printf("%d\\n", *(arr + 2));') }, quickCheck({ text: 'Which expression equals arr[2]?', options: ['*(arr + 2)', '&arr + 2', '2 * arr', 'arr(2)'], correct_index: 0 })),
  lesson(4, 'Pointers and Functions', 6, { explanation: 'Passing a pointer to a function lets that function modify the caller\'s variable, since it has the real address.', syntax: 'void inc(int *p) { (*p)++; }', examples: [ex(MAIN('    int x = 5;\n    void inc(int *p);\n    return 0;\n}\n\nvoid inc(int *p) {\n    (*p)++;\n}'), '(compiles — demonstrates pass-by-pointer syntax)')], important_points: ['Regular C function arguments are copied — a pointer is how you let a function change the original variable.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n\nvoid inc(int *p) {\n    (*p)++;\n}\n\nint main() {\n    int x = 5;\n    inc(&x);\n    printf("%d\\n", x);\n    return 0;\n}' }, quickCheck({ text: 'Why pass a pointer to a function instead of a plain value?', options: ['It is required for all functions', 'So the function can modify the caller\'s variable', 'It makes the code shorter only', 'Pointers cannot be passed'], correct_index: 1 })),
  lesson(5, 'Double Pointers', 6, { explanation: 'A double pointer (int **) is a pointer to a pointer — it stores the address of another pointer variable.', syntax: 'int x = 5;\nint *p = &x;\nint **pp = &p;', examples: [ex(MAIN('    int x = 5;\n    int *p = &x;\n    int **pp = &p;\n    printf("%d\\n", **pp);'), '5')], important_points: ['**pp dereferences twice: once to get p, once more to get x.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    int x = 5;\n    int *p = &x;\n    int **pp = &p;\n    printf("%d\\n", **pp);') }, quickCheck({ text: 'What does **pp give you if pp is a pointer to a pointer to x?', options: ['The address of p', 'The address of x', 'The value of x', 'A compile error'], correct_index: 2 })),
  lesson(6, 'Pointer Practice', 7, { explanation: 'Practice: write a function that swaps two integers using pointers.', syntax: '', examples: [ex('#include <stdio.h>\n\nvoid swap(int *a, int *b) {\n    int temp = *a;\n    *a = *b;\n    *b = temp;\n}\n\nint main() {\n    int x = 1, y = 2;\n    swap(&x, &y);\n    printf("%d %d\\n", x, y);\n    return 0;\n}', '2 1')], important_points: ['Swapping requires pointers — passing plain ints would only swap local copies.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n\nvoid swap(int *a, int *b) {\n    int temp = *a;\n    *a = *b;\n    *b = temp;\n}\n\nint main() {\n    int x = 3, y = 9;\n    swap(&x, &y);\n    printf("%d %d\\n", x, y);\n    return 0;\n}' }, quickCheck({ text: 'Why can\'t swap(int a, int b) (without pointers) swap the caller\'s variables?', options: ['C forbids swapping', 'Arguments are copied — the originals are untouched', 'It works fine without pointers', 'ints cannot be swapped'], correct_index: 1 }))
];

const M5 = [
  lesson(1, 'Function Basics', 6, { explanation: 'A function is a named, reusable block of code with its own return type and parameter list.', syntax: 'int add(int a, int b) { return a + b; }', examples: [ex('#include <stdio.h>\n\nint add(int a, int b) {\n    return a + b;\n}\n\nint main() {\n    printf("%d\\n", add(2, 3));\n    return 0;\n}', '5')], important_points: ['A function must be declared (or defined) before it is used in main() unless it is defined above main().'], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n\nint add(int a, int b) {\n    return a + b;\n}\n\nint main() {\n    printf("%d\\n", add(2, 3));\n    return 0;\n}' }, quickCheck({ text: 'What does "int" mean in "int add(int a, int b)"?', options: ['The name of the function', 'The type of value the function returns', 'A parameter', 'A comment'], correct_index: 1 })),
  lesson(2, 'Parameters', 6, { explanation: 'Parameters are the named inputs a function accepts — the values passed in when it is called.', syntax: 'void greet(char name[]) { printf("Hi %s\\n", name); }', examples: [ex('#include <stdio.h>\n\nvoid greet(char name[]) {\n    printf("Hi %s\\n", name);\n}\n\nint main() {\n    greet("Sam");\n    return 0;\n}', 'Hi Sam')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n\nvoid greet(char name[]) {\n    printf("Hi %s\\n", name);\n}\n\nint main() {\n    greet("Sam");\n    return 0;\n}' }, quickCheck({ text: 'In void greet(char name[]), "name" is:', options: ['A global variable', 'A parameter', 'The return value', 'A macro'], correct_index: 1 })),
  lesson(3, 'Return Values', 6, { explanation: 'A function\'s return type declares what kind of value it hands back; "void" means it returns nothing.', syntax: 'int square(int n) { return n * n; }', examples: [ex(MAIN('    int square(int n);\n    printf("%d\\n", square(4));\n    return 0;\n}\nint square(int n) { return n * n; }'), '16')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n\nint square(int n) {\n    return n * n;\n}\n\nint main() {\n    printf("%d\\n", square(4));\n    return 0;\n}' }, quickCheck({ text: 'What does "void" as a return type mean?', options: ['Returns 0', 'Returns nothing', 'Returns any type', 'A syntax error'], correct_index: 1 })),
  lesson(4, 'Recursion', 7, { explanation: 'A recursive function calls itself with a smaller input, until it reaches a base case that stops the recursion.', syntax: 'int fact(int n) { if (n <= 1) return 1; return n * fact(n - 1); }', examples: [ex('#include <stdio.h>\n\nint fact(int n) {\n    if (n <= 1) return 1;\n    return n * fact(n - 1);\n}\n\nint main() {\n    printf("%d\\n", fact(4));\n    return 0;\n}', '24')], important_points: ['Every recursive function needs a base case, or it will call itself forever (stack overflow).'], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n\nint fact(int n) {\n    if (n <= 1) return 1;\n    return n * fact(n - 1);\n}\n\nint main() {\n    printf("%d\\n", fact(5));\n    return 0;\n}' }, quickCheck({ text: 'What is a "base case" in recursion?', options: ['The first function call', 'The condition that stops further recursive calls', 'A syntax requirement only', 'The slowest part'], correct_index: 1 })),
  lesson(5, 'Function Practice', 7, { explanation: 'Practice: write a function that checks if a number is even.', syntax: '', examples: [ex('#include <stdio.h>\n\nint isEven(int n) {\n    return n % 2 == 0;\n}\n\nint main() {\n    printf("%d\\n", isEven(4));\n    return 0;\n}', '1')], important_points: ['C has no boolean type by default — 0 means false, any nonzero value means true.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n\nint isEven(int n) {\n    return n % 2 == 0;\n}\n\nint main() {\n    printf("%d\\n", isEven(7));\n    return 0;\n}' }, quickCheck({ type: 'code', text: 'Write isEven(n) and print isEven(10).', starter_code: '#include <stdio.h>\n\nint isEven(int n) {\n    // return 1 if even, 0 if odd\n}\n\nint main() {\n    printf("%d\\n", isEven(10));\n    return 0;\n}', test_cases: [{ input: '', expected_output: '1' }] }))
];

const M6 = [
  lesson(1, 'struct Basics', 6, { explanation: 'A struct groups related variables of different types together under one name.', syntax: 'struct Point { int x; int y; };', examples: [ex(MAIN('    struct Point { int x; int y; };\n    struct Point p = {1, 2};\n    printf("%d\\n", p.x);'), '1')], important_points: ['Access a struct\'s fields with the dot operator: p.x, p.y.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    struct Point { int x; int y; };\n    struct Point p = {1, 2};\n    printf("%d\\n", p.x);') }, quickCheck({ text: 'How do you access field x of struct variable p?', options: ['p->x', 'p.x', 'p[x]', 'p(x)'], correct_index: 1 })),
  lesson(2, 'Nested Structures', 6, { explanation: 'A struct can contain another struct as one of its fields.', syntax: 'struct Line { struct Point start; struct Point end; };', examples: [ex(MAIN('    struct Point { int x; int y; };\n    struct Line { struct Point start; struct Point end; };\n    struct Line l = {{0,0}, {5,5}};\n    printf("%d\\n", l.end.x);'), '5')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    struct Point { int x; int y; };\n    struct Line { struct Point start; struct Point end; };\n    struct Line l = {{0,0}, {5,5}};\n    printf("%d\\n", l.end.x);') }, quickCheck({ text: 'How do you reach a nested struct field like l.end.x?', options: ['Chain dots: l.end.x', 'l[end][x]', 'l->end->x always', 'It is not possible'], correct_index: 0 })),
  lesson(3, 'Arrays of Structures', 6, { explanation: 'You can make an array of structs, just like an array of ints — useful for a list of records.', syntax: 'struct Point pts[2];', examples: [ex(MAIN('    struct Point { int x; int y; };\n    struct Point pts[2] = {{1,1}, {2,2}};\n    printf("%d\\n", pts[1].x);'), '2')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    struct Point { int x; int y; };\n    struct Point pts[2] = {{1,1}, {2,2}};\n    printf("%d\\n", pts[1].x);') }, quickCheck({ text: 'An array of structs is used to store:', options: ['A single value', 'Multiple records of the same shape', 'Only strings', 'Function pointers'], correct_index: 1 })),
  lesson(4, 'Structures and Pointers', 6, { explanation: 'When you have a pointer to a struct, use -> instead of . to access its fields.', syntax: 'p->x   // same as (*p).x', examples: [ex(MAIN('    struct Point { int x; int y; };\n    struct Point pt = {3, 4};\n    struct Point *p = &pt;\n    printf("%d\\n", p->x);'), '3')], important_points: ['p->x is shorthand for (*p).x.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    struct Point { int x; int y; };\n    struct Point pt = {3, 4};\n    struct Point *p = &pt;\n    printf("%d\\n", p->x);') }, quickCheck({ text: 'If p is a pointer to a struct, how do you access field x?', options: ['p.x', 'p->x', '*p.x', '&p.x'], correct_index: 1 })),
  lesson(5, 'Unions', 6, { explanation: 'A union looks like a struct but all its members share the same memory — only one field is valid at a time.', syntax: 'union Data { int i; float f; };', examples: [ex(MAIN('    union Data { int i; float f; };\n    union Data d;\n    d.i = 5;\n    printf("%d\\n", d.i);'), '5')], important_points: ['A union\'s size is the size of its largest member, since fields overlap in memory.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    union Data { int i; float f; };\n    union Data d;\n    d.i = 5;\n    printf("%d\\n", d.i);') }, quickCheck({ text: 'What is different about a union compared to a struct?', options: ['Unions cannot have fields', 'All union fields share the same memory', 'Unions are always bigger', 'Nothing, they are identical'], correct_index: 1 })),
  lesson(6, 'Practice', 7, { explanation: 'Practice: model a Student with a struct and print one field.', syntax: '', examples: [ex(MAIN('    struct Student { char name[20]; int marks; };\n    struct Student s = {"Sam", 85};\n    printf("%s: %d\\n", s.name, s.marks);'), 'Sam: 85')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    struct Student { char name[20]; int marks; };\n    struct Student s = {"Ana", 92};\n    // print s.name and s.marks\n') }, quickCheck({ type: 'code', text: 'Given struct Student {char name[20]; int marks;} s = {"Ana", 92}, print s.marks.', starter_code: MAIN('    struct Student { char name[20]; int marks; };\n    struct Student s = {"Ana", 92};\n    // print s.marks\n'), test_cases: [{ input: '', expected_output: '92' }] }))
];

const M7 = [
  lesson(1, 'Stack vs Heap', 6, { explanation: 'Stack memory is automatically managed and freed when a function returns; heap memory is manually allocated and must be freed by you.', syntax: '', examples: [ex('', '(conceptual — no single runnable snippet)')], important_points: ['Local variables (like "int x;") live on the stack — heap memory is what malloc() gives you.'], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'Which memory is freed automatically when a function returns?', options: ['Heap memory', 'Stack memory', 'Both', 'Neither'], correct_index: 1 })),
  lesson(2, 'malloc', 6, { explanation: 'malloc allocates a block of memory on the heap and returns a pointer to it (or NULL if it fails).', syntax: 'int *arr = malloc(5 * sizeof(int));', examples: [ex('#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    int *arr = malloc(3 * sizeof(int));\n    arr[0] = 10;\n    printf("%d\\n", arr[0]);\n    free(arr);\n    return 0;\n}', '10')], important_points: ['malloc does not initialize the memory — its contents start out unpredictable.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    int *arr = malloc(3 * sizeof(int));\n    arr[0] = 10;\n    printf("%d\\n", arr[0]);\n    free(arr);\n    return 0;\n}' }, quickCheck({ text: 'What does malloc(5 * sizeof(int)) allocate?', options: ['Space for 5 ints, uninitialized', 'Space for 5 ints, all zeroed', '5 bytes', 'Nothing until used'], correct_index: 0 })),
  lesson(3, 'calloc', 6, { explanation: 'calloc allocates memory like malloc, but also zero-initializes it — useful when you need a clean starting value.', syntax: 'int *arr = calloc(5, sizeof(int));', examples: [ex('#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    int *arr = calloc(3, sizeof(int));\n    printf("%d\\n", arr[0]);\n    free(arr);\n    return 0;\n}', '0')], important_points: ['calloc\'s two arguments are (count, size-of-each-element), not one combined byte count.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    int *arr = calloc(3, sizeof(int));\n    printf("%d\\n", arr[0]);\n    free(arr);\n    return 0;\n}' }, quickCheck({ text: 'What is the key difference between malloc and calloc?', options: ['calloc zero-initializes the memory', 'malloc is slower', 'calloc cannot fail', 'There is no difference'], correct_index: 0 })),
  lesson(4, 'realloc', 6, { explanation: 'realloc resizes a previously allocated block, keeping its existing contents where possible.', syntax: 'arr = realloc(arr, 10 * sizeof(int));', examples: [ex('#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    int *arr = malloc(2 * sizeof(int));\n    arr[0] = 1;\n    arr = realloc(arr, 4 * sizeof(int));\n    printf("%d\\n", arr[0]);\n    free(arr);\n    return 0;\n}', '1')], important_points: ['Always assign realloc\'s result back — if it fails it returns NULL and the original pointer would otherwise be lost.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    int *arr = malloc(2 * sizeof(int));\n    arr[0] = 1;\n    arr = realloc(arr, 4 * sizeof(int));\n    printf("%d\\n", arr[0]);\n    free(arr);\n    return 0;\n}' }, quickCheck({ text: 'What does realloc do?', options: ['Frees memory', 'Resizes a previously allocated block', 'Allocates zeroed memory', 'Copies a string'], correct_index: 1 })),
  lesson(5, 'free', 6, { explanation: 'free() releases heap memory you allocated with malloc/calloc/realloc back to the system.', syntax: 'free(ptr);', examples: [ex('#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    int *p = malloc(sizeof(int));\n    *p = 42;\n    printf("%d\\n", *p);\n    free(p);\n    return 0;\n}', '42')], important_points: ['Using a pointer after freeing it ("use after free") is undefined behavior — set it to NULL if you might check it again.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    int *p = malloc(sizeof(int));\n    *p = 42;\n    printf("%d\\n", *p);\n    free(p);\n    return 0;\n}' }, quickCheck({ text: 'What does free(ptr) do?', options: ['Deletes the pointer variable', 'Releases the heap memory ptr points to', 'Sets ptr to 0 automatically', 'Nothing, it is optional'], correct_index: 1 })),
  lesson(6, 'Memory Leaks', 6, { explanation: 'A memory leak happens when allocated memory is never freed — the program keeps using more memory over time.', syntax: '', examples: [ex('', '(conceptual)')], important_points: ['Every malloc/calloc should have a matching free once the memory is no longer needed.'], common_mistakes: ['Overwriting the only pointer to allocated memory before calling free() on it — the memory becomes unreachable and leaked.'], real_world: '' }, null, quickCheck({ text: 'What causes a memory leak in C?', options: ['Calling free() too often', 'Allocated memory that is never freed', 'Using too many stack variables', 'Using printf too much'], correct_index: 1 }))
];

const M8 = [
  lesson(1, 'Opening Files', 6, { explanation: 'fopen() opens a file and returns a FILE pointer, or NULL if it fails.', syntax: 'FILE *f = fopen("data.txt", "r");', examples: [ex('#include <stdio.h>\n\nint main() {\n    FILE *f = fopen("data.txt", "w");\n    if (f) printf("opened\\n");\n    if (f) fclose(f);\n    return 0;\n}', 'opened')], important_points: ['Always check if fopen returned NULL before using the file — the file might not exist or be accessible.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n\nint main() {\n    FILE *f = fopen("data.txt", "w");\n    if (f) printf("opened\\n");\n    if (f) fclose(f);\n    return 0;\n}' }, quickCheck({ text: 'What does fopen return if it fails to open a file?', options: ['0', 'NULL', 'An empty string', 'It crashes'], correct_index: 1 })),
  lesson(2, 'Reading Files', 6, { explanation: 'fgets() reads a line of text from a file into a buffer.', syntax: 'char line[100];\nfgets(line, 100, f);', examples: [ex('', '(reads a line from an open file into "line")')], important_points: ['fgets stops at a newline or when the buffer is full, whichever comes first.'], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'What does fgets(line, 100, f) do?', options: ['Writes to the file', 'Reads up to 99 characters (or a line) into "line"', 'Deletes the file', 'Opens a new file'], correct_index: 1 })),
  lesson(3, 'Writing Files', 6, { explanation: 'fprintf() writes formatted text to a file, just like printf writes to the screen.', syntax: 'fprintf(f, "%s", "hello");', examples: [ex('#include <stdio.h>\n\nint main() {\n    FILE *f = fopen("out.txt", "w");\n    fprintf(f, "%s", "hello");\n    fclose(f);\n    printf("written\\n");\n    return 0;\n}', 'written')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n\nint main() {\n    FILE *f = fopen("out.txt", "w");\n    fprintf(f, "%s", "hello");\n    fclose(f);\n    printf("written\\n");\n    return 0;\n}' }, quickCheck({ text: 'Which function writes formatted text to a file?', options: ['fscanf', 'fprintf', 'fgets', 'fopen'], correct_index: 1 })),
  lesson(4, 'File Modes', 6, { explanation: 'fopen\'s second argument is a mode: "r" read, "w" write (overwrite), "a" append.', syntax: 'fopen("data.txt", "a");', examples: [ex('', '"a" opens for appending — new writes go after existing content instead of erasing it.')], important_points: ['"w" mode erases the existing file content immediately when opened.'], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'Which mode appends to a file without erasing existing content?', options: ['"r"', '"w"', '"a"', '"x"'], correct_index: 2 })),
  lesson(5, 'Closing Files', 6, { explanation: 'fclose() closes a file and flushes any buffered writes to disk — always close files when done.', syntax: 'fclose(f);', examples: [ex('#include <stdio.h>\n\nint main() {\n    FILE *f = fopen("out.txt", "w");\n    fclose(f);\n    printf("closed\\n");\n    return 0;\n}', 'closed')], important_points: ['Forgetting to close a file can leave writes unflushed, or leak file handles in long-running programs.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n\nint main() {\n    FILE *f = fopen("out.txt", "w");\n    fclose(f);\n    printf("closed\\n");\n    return 0;\n}' }, quickCheck({ text: 'Why should you always call fclose() on an opened file?', options: ['It is optional, no reason', 'To flush buffered writes and release the file handle', 'It deletes the file', 'It renames the file'], correct_index: 1 }))
];

const M9 = [
  lesson(1, 'Macros', 6, { explanation: 'A macro is text substituted by the preprocessor before compilation — often used for constants or short code snippets.', syntax: '#define PI 3.14', examples: [ex(MAIN('    #define PI 3.14 // note: normally written above main\n    printf("%f\\n", PI);'), '3.140000')], important_points: ['Macros are simple text replacement — no type checking happens.'], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'When does macro substitution happen?', options: ['At runtime', 'Before compilation, by the preprocessor', 'After the program finishes', 'Never automatically'], correct_index: 1 })),
  lesson(2, '#define', 6, { explanation: '#define can create both constants and simple function-like macros.', syntax: '#define SQUARE(x) ((x) * (x))', examples: [ex('#include <stdio.h>\n#define SQUARE(x) ((x) * (x))\n\nint main() {\n    printf("%d\\n", SQUARE(5));\n    return 0;\n}', '25')], important_points: ['Wrap macro parameters in parentheses — SQUARE(x) without them can break on expressions like SQUARE(1+2).'], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n#define SQUARE(x) ((x) * (x))\n\nint main() {\n    printf("%d\\n", SQUARE(5));\n    return 0;\n}' }, quickCheck({ text: 'Why wrap macro parameters in parentheses, e.g. ((x)*(x))?', options: ['Style only, no real effect', 'To avoid operator-precedence bugs when x is an expression', 'C requires it syntactically', 'To make it run faster'], correct_index: 1 })),
  lesson(3, '#include', 6, { explanation: '#include pulls in declarations from another file — <angle brackets> for standard library headers, "quotes" for your own files.', syntax: '#include <stdio.h>\n#include "myheader.h"', examples: [ex('', '#include <stdio.h> is why printf() is available in your program.')], important_points: [], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'When do you use "quotes" instead of <angle brackets> for #include?', options: ['Never, angle brackets always work', 'For your own project header files', 'Only for math.h', 'Quotes are not valid C'], correct_index: 1 })),
  lesson(4, 'Conditional Compilation', 6, { explanation: '#ifdef/#ifndef/#endif let you include or exclude code at compile time, often for debugging or platform differences.', syntax: '#ifdef DEBUG\n  printf("debug info\\n");\n#endif', examples: [ex('', 'Code between #ifdef DEBUG and #endif only compiles if DEBUG was defined.')], important_points: ['Header files commonly use #ifndef HEADER_H / #define HEADER_H to prevent being included twice.'], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'What does #ifdef DEBUG ... #endif do?', options: ['Always compiles the code', 'Only compiles the code if DEBUG is defined', 'Deletes the code', 'Runs the code conditionally at runtime'], correct_index: 1 }))
];

const M10 = [
  lesson(1, 'auto', 6, { explanation: '"auto" is the default storage class for local variables — it is rarely written explicitly since it\'s automatic.', syntax: 'auto int x = 5; // same as: int x = 5;', examples: [ex(MAIN('    auto int x = 5;\n    printf("%d\\n", x);'), '5')], important_points: ['Every ordinary local variable is "auto" by default — the keyword is almost never typed in modern C.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    auto int x = 5;\n    printf("%d\\n", x);') }, quickCheck({ text: 'What is the default storage class of a local variable?', options: ['static', 'extern', 'auto', 'register'], correct_index: 2 })),
  lesson(2, 'static', 6, { explanation: 'A static local variable keeps its value between function calls instead of resetting each time.', syntax: 'static int count = 0;', examples: [ex('#include <stdio.h>\n\nvoid counter() {\n    static int count = 0;\n    count++;\n    printf("%d\\n", count);\n}\n\nint main() {\n    counter();\n    counter();\n    return 0;\n}', '1\n2')], important_points: ['A static variable is initialized only once, the first time that line runs.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n\nvoid counter() {\n    static int count = 0;\n    count++;\n    printf("%d\\n", count);\n}\n\nint main() {\n    counter();\n    counter();\n    counter();\n    return 0;\n}' }, quickCheck({ text: 'What makes "static" special for a local variable?', options: ['It resets to 0 every call', 'It keeps its value between calls', 'It cannot be modified', 'It is global automatically'], correct_index: 1 })),
  lesson(3, 'extern', 6, { explanation: '"extern" declares that a variable is defined in another file, letting multiple files share one global variable.', syntax: 'extern int counter; // declared in another .c file', examples: [ex('', '(conceptual — extern is used across multiple .c files, not within a single snippet)')], important_points: ['extern only declares the variable — the actual definition (with memory allocated) lives in exactly one file.'], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'What is "extern" used for?', options: ['Making a variable local', 'Sharing a global variable across multiple files', 'Deleting a variable', 'Speeding up loops'], correct_index: 1 })),
  lesson(4, 'register', 6, { explanation: '"register" hints to the compiler that a variable is used often and should be kept in a CPU register for speed — modern compilers mostly ignore this and optimize on their own.', syntax: 'register int i;', examples: [ex(MAIN('    register int i;\n    for (i = 0; i < 3; i++) {\n        printf("%d ", i);\n    }\n    printf("\\n");'), '0 1 2')], important_points: ['You cannot take the address (&) of a register variable in strict C, since it might not exist in memory.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    register int i;\n    for (i = 0; i < 3; i++) {\n        printf("%d ", i);\n    }\n    printf("\\n");') }, quickCheck({ text: 'What was "register" originally meant to do?', options: ['Make a variable global', 'Hint the compiler to keep the variable in a fast CPU register', 'Prevent modification', 'Allocate heap memory'], correct_index: 1 }))
];

const M11 = [
  lesson(1, 'Bitwise Operators', 7, { explanation: 'Bitwise operators (&, |, ^, ~, <<, >>) work directly on the individual bits of a number.', syntax: 'a & b, a | b, a << 1', examples: [ex(MAIN('    int a = 5; // 0101\n    int b = 3; // 0011\n    printf("%d\\n", a & b);'), '1')], important_points: ['<< 1 doubles a number (shifts bits left); >> 1 halves it (shifts right).'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    int a = 5;\n    int b = 3;\n    printf("%d\\n", a & b);') }, quickCheck({ text: 'What does the << operator do?', options: ['Divides by 2', 'Shifts bits left (roughly multiplies by 2)', 'Compares two values', 'Negates a number'], correct_index: 1 })),
  lesson(2, 'Function Pointers', 7, { explanation: 'A function pointer stores the address of a function, letting you call it indirectly or pass it as an argument.', syntax: 'int (*fp)(int) = &square;', examples: [ex('#include <stdio.h>\n\nint square(int n) { return n * n; }\n\nint main() {\n    int (*fp)(int) = square;\n    printf("%d\\n", fp(4));\n    return 0;\n}', '16')], important_points: ['Function pointers are how C implements passing "behavior" as data (e.g. callbacks, qsort comparators).'], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n\nint square(int n) { return n * n; }\n\nint main() {\n    int (*fp)(int) = square;\n    printf("%d\\n", fp(5));\n    return 0;\n}' }, quickCheck({ text: 'What does a function pointer store?', options: ['A function\'s return value', 'The address of a function', 'A function\'s name as text', 'Nothing useful'], correct_index: 1 })),
  lesson(3, 'Command Line Arguments', 6, { explanation: 'main(int argc, char *argv[]) receives command-line arguments — argc is the count, argv is the array of argument strings.', syntax: 'int main(int argc, char *argv[]) { ... }', examples: [ex('', 'Running "./program hello" gives argc = 2, argv[0] = "./program", argv[1] = "hello".')], important_points: ['argv[0] is always the program\'s own name, not the first real argument.'], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'What does argv[0] usually contain?', options: ['The first real argument', 'The program\'s own name/path', 'Always NULL', 'The argument count'], correct_index: 1 })),
  lesson(4, 'typedef', 6, { explanation: 'typedef creates an alias for an existing type, often to shorten a long struct type name.', syntax: 'typedef struct { int x; int y; } Point;', examples: [ex(MAIN('    typedef struct { int x; int y; } Point;\n    Point p = {1, 2};\n    printf("%d\\n", p.x);'), '1')], important_points: ['After a typedef, you can write "Point p;" instead of "struct Point p;".'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    typedef struct { int x; int y; } Point;\n    Point p = {1, 2};\n    printf("%d\\n", p.x);') }, quickCheck({ text: 'What does typedef mainly let you do?', options: ['Delete a type', 'Create a shorter alias for an existing type', 'Convert between types automatically', 'Define a macro'], correct_index: 1 })),
  lesson(5, 'Enums', 6, { explanation: 'An enum defines a set of named integer constants, making code more readable than raw numbers.', syntax: 'enum Day { MON, TUE, WED };', examples: [ex(MAIN('    enum Day { MON, TUE, WED };\n    enum Day d = TUE;\n    printf("%d\\n", d);'), '1')], important_points: ['Enum values start at 0 by default and increase by 1 unless you assign specific numbers.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    enum Day { MON, TUE, WED };\n    enum Day d = TUE;\n    printf("%d\\n", d);') }, quickCheck({ text: 'By default, what integer value does the first enum member get?', options: ['1', '0', '-1', 'It is undefined'], correct_index: 1 }))
];

const M12 = [
  lesson(1, 'errno', 6, { explanation: 'errno is a global variable many C library functions set when they fail, describing what went wrong.', syntax: '#include <errno.h>', examples: [ex('', 'If fopen() fails, errno holds a code you can look up (e.g. "file not found").')], important_points: ['errno is only meaningful right after a failing call — a later successful call can overwrite it.'], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'When is errno meaningful to check?', options: ['At any point in the program', 'Right after a call that failed', 'Only at program start', 'Never in C'], correct_index: 1 })),
  lesson(2, 'perror', 6, { explanation: 'perror() prints a human-readable message for the current errno value, prefixed by text you provide.', syntax: 'perror("fopen failed");', examples: [ex('#include <stdio.h>\n\nint main() {\n    FILE *f = fopen("does_not_exist.txt", "r");\n    if (!f) {\n        perror("fopen failed");\n    }\n    return 0;\n}', 'fopen failed: No such file or directory')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n\nint main() {\n    FILE *f = fopen("does_not_exist.txt", "r");\n    if (!f) {\n        perror("fopen failed");\n    }\n    return 0;\n}' }, quickCheck({ text: 'What does perror("fopen failed") print?', options: ['Nothing unless errno is 0', 'Your message plus a description of the current error', 'Only your message', 'The line number of the error'], correct_index: 1 })),
  lesson(3, 'Defensive Coding', 7, { explanation: 'Defensive coding means checking things that could go wrong — null pointers, failed allocations, invalid input — before using them.', syntax: 'if (p == NULL) { /* handle it */ }', examples: [ex('#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    int *p = malloc(sizeof(int));\n    if (p == NULL) {\n        printf("allocation failed\\n");\n        return 1;\n    }\n    *p = 5;\n    printf("%d\\n", *p);\n    free(p);\n    return 0;\n}', '5')], important_points: ['Checking malloc\'s return value for NULL before dereferencing it prevents crashes on out-of-memory conditions.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    int *p = malloc(sizeof(int));\n    if (p == NULL) {\n        printf("allocation failed\\n");\n        return 1;\n    }\n    *p = 7;\n    printf("%d\\n", *p);\n    free(p);\n    return 0;\n}' }, quickCheck({ text: 'Why check if malloc returned NULL before using the pointer?', options: ['It never returns NULL', 'To avoid dereferencing an invalid pointer if allocation failed', 'It is required by the compiler', 'To free memory faster'], correct_index: 1 }))
];

const M13 = [
  lesson(1, 'Linked Lists', 7, { explanation: 'A linked list is a chain of nodes, each holding a value and a pointer to the next node.', syntax: 'struct Node { int val; struct Node *next; };', examples: [ex('#include <stdio.h>\n#include <stdlib.h>\n\nstruct Node { int val; struct Node *next; };\n\nint main() {\n    struct Node *head = malloc(sizeof(struct Node));\n    head->val = 10;\n    head->next = NULL;\n    printf("%d\\n", head->val);\n    return 0;\n}', '10')], important_points: ['The last node\'s "next" pointer is NULL, marking the end of the list.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n#include <stdlib.h>\n\nstruct Node { int val; struct Node *next; };\n\nint main() {\n    struct Node *head = malloc(sizeof(struct Node));\n    head->val = 10;\n    head->next = NULL;\n    printf("%d\\n", head->val);\n    return 0;\n}' }, quickCheck({ text: 'What marks the end of a singly linked list?', options: ['A node with value 0', 'A "next" pointer that is NULL', 'The first node', 'A special "END" struct'], correct_index: 1 })),
  lesson(2, 'Stacks', 6, { explanation: 'A stack (LIFO) can be built on top of an array, tracking a "top" index for the most recently pushed item.', syntax: 'arr[top++] = value; // push\nvalue = arr[--top]; // pop', examples: [ex(MAIN('    int stack[10];\n    int top = 0;\n    stack[top++] = 5;\n    stack[top++] = 8;\n    printf("%d\\n", stack[--top]);'), '8')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    int stack[10];\n    int top = 0;\n    stack[top++] = 5;\n    stack[top++] = 8;\n    printf("%d\\n", stack[--top]);') }, quickCheck({ text: 'In an array-based stack, what does "top" typically track?', options: ['The bottom of the stack', 'The index of the most recently pushed item', 'The array size', 'A random index'], correct_index: 1 })),
  lesson(3, 'Queues', 6, { explanation: 'A queue (FIFO) tracks two indexes: front (where you remove from) and rear (where you add to).', syntax: 'arr[rear++] = value; // enqueue\nvalue = arr[front++]; // dequeue', examples: [ex(MAIN('    int q[10];\n    int front = 0, rear = 0;\n    q[rear++] = 1;\n    q[rear++] = 2;\n    printf("%d\\n", q[front++]);'), '1')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    int q[10];\n    int front = 0, rear = 0;\n    q[rear++] = 1;\n    q[rear++] = 2;\n    printf("%d\\n", q[front++]);') }, quickCheck({ text: 'In a queue, which end do you remove elements from?', options: ['The rear', 'The front', 'Either end', 'The middle'], correct_index: 1 })),
  lesson(4, 'Searching', 6, { explanation: 'Linear search checks each element in turn; binary search halves a sorted array\'s range each step.', syntax: '', examples: [ex(MAIN('    int arr[5] = {1, 3, 5, 7, 9};\n    int target = 7, found = -1;\n    for (int i = 0; i < 5; i++) {\n        if (arr[i] == target) { found = i; break; }\n    }\n    printf("%d\\n", found);'), '3')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    int arr[5] = {1, 3, 5, 7, 9};\n    int target = 5, found = -1;\n    for (int i = 0; i < 5; i++) {\n        if (arr[i] == target) { found = i; break; }\n    }\n    printf("%d\\n", found);') }, quickCheck({ text: 'Which search requires the array to already be sorted?', options: ['Linear search', 'Binary search', 'Both require sorting', 'Neither'], correct_index: 1 })),
  lesson(5, 'Sorting', 6, { explanation: 'Bubble sort repeatedly swaps adjacent out-of-order elements until the whole array is sorted.', syntax: '', examples: [ex(MAIN('    int arr[4] = {4, 2, 3, 1};\n    for (int i = 0; i < 4; i++) {\n        for (int j = 0; j < 3 - i; j++) {\n            if (arr[j] > arr[j+1]) {\n                int t = arr[j]; arr[j] = arr[j+1]; arr[j+1] = t;\n            }\n        }\n    }\n    printf("%d\\n", arr[0]);'), '1')], important_points: ['Bubble sort is simple but slow (O(n^2)) — fine for learning, not for large real datasets.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    int arr[4] = {4, 2, 3, 1};\n    for (int i = 0; i < 4; i++) {\n        for (int j = 0; j < 3 - i; j++) {\n            if (arr[j] > arr[j+1]) {\n                int t = arr[j]; arr[j] = arr[j+1]; arr[j+1] = t;\n            }\n        }\n    }\n    printf("%d\\n", arr[0]);') }, quickCheck({ text: 'What is bubble sort\'s main downside?', options: ['It cannot sort integers', 'It is slow (O(n^2)) for large arrays', 'It needs extra memory', 'It only works on strings'], correct_index: 1 }))
];

const M14 = [
  lesson(1, 'Arrays', 6, { explanation: 'Revisiting arrays through a DSA lens: they give O(1) access by index but O(n) insertion in the middle.', syntax: '', examples: [ex(MAIN('    int arr[5] = {1, 2, 3, 4, 5};\n    printf("%d\\n", arr[2]);'), '3')], important_points: ['Accessing arr[i] is instant (O(1)) regardless of array size — that\'s an array\'s main strength.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    int arr[5] = {1, 2, 3, 4, 5};\n    printf("%d\\n", arr[2]);') }, quickCheck({ text: 'What is the time complexity of accessing arr[i] directly?', options: ['O(n)', 'O(1)', 'O(log n)', 'O(n^2)'], correct_index: 1 })),
  lesson(2, 'Trees Basics', 7, { explanation: 'A binary tree node has a value and pointers to at most two children, left and right.', syntax: 'struct Node { int val; struct Node *left, *right; };', examples: [ex('#include <stdio.h>\n#include <stdlib.h>\n\nstruct Node { int val; struct Node *left, *right; };\n\nint main() {\n    struct Node *root = malloc(sizeof(struct Node));\n    root->val = 10; root->left = NULL; root->right = NULL;\n    printf("%d\\n", root->val);\n    return 0;\n}', '10')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n#include <stdlib.h>\n\nstruct Node { int val; struct Node *left, *right; };\n\nint main() {\n    struct Node *root = malloc(sizeof(struct Node));\n    root->val = 10; root->left = NULL; root->right = NULL;\n    printf("%d\\n", root->val);\n    return 0;\n}' }, quickCheck({ text: 'How many children can a binary tree node have at most?', options: ['1', '2', '3', 'Unlimited'], correct_index: 1 })),
  lesson(3, 'Problem Solving', 7, { explanation: 'Apply arrays + loops to solve a small problem: find the largest value in an array.', syntax: '', examples: [ex(MAIN('    int arr[4] = {3, 7, 2, 5};\n    int max = arr[0];\n    for (int i = 1; i < 4; i++) if (arr[i] > max) max = arr[i];\n    printf("%d\\n", max);'), '7')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    int arr[5] = {9, 4, 8, 1, 6};\n    // find and print the largest value\n') }, quickCheck({ type: 'code', text: 'Given int arr[5] = {9,4,8,1,6}, print the largest value.', starter_code: MAIN('    int arr[5] = {9, 4, 8, 1, 6};\n    // print the max\n'), test_cases: [{ input: '', expected_output: '9' }] })),
  lesson(4, 'Complexity Basics', 6, { explanation: 'Big-O notation describes roughly how an algorithm\'s work grows as input size grows — O(1) constant, O(n) linear, O(n^2) quadratic.', syntax: '', examples: [ex('', 'A single loop over n elements is O(n); a nested loop over n elements is typically O(n^2).')], important_points: ['Big-O describes growth trend, not an exact time — O(n) code can still be slower than O(n^2) code for small n.'], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'A single loop that visits every element once is typically:', options: ['O(1)', 'O(n)', 'O(n^2)', 'O(log n)'], correct_index: 1 }))
];

const M15 = [
  lesson(1, 'Calculator', 8, { explanation: 'Build a simple calculator: read an operator and two numbers, branch on the operator.', syntax: '', examples: [ex(MAIN('    char op = \'+\';\n    int a = 4, b = 3, result = 0;\n    if (op == \'+\') result = a + b;\n    printf("%d\\n", result);'), '7')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    char op = \'*\';\n    int a = 6, b = 7, result = 0;\n    if (op == \'+\') result = a + b;\n    else if (op == \'*\') result = a * b;\n    printf("%d\\n", result);') }, quickCheck({ type: 'code', text: 'Extend the calculator with subtraction and print 10 - 4.', starter_code: MAIN('    char op = \'-\';\n    int a = 10, b = 4, result = 0;\n    if (op == \'+\') result = a + b;\n    else if (op == \'-\') result = a - b;\n    printf("%d\\n", result);'), test_cases: [{ input: '', expected_output: '6' }] })),
  lesson(2, 'Student Record System', 9, { explanation: 'Use a struct + array of structs to store a small set of student records.', syntax: '', examples: [ex(MAIN('    struct Student { char name[20]; int marks; };\n    struct Student list[2] = {{"Sam", 85}, {"Ana", 92}};\n    printf("%s\\n", list[0].name);'), 'Sam')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    struct Student { char name[20]; int marks; };\n    struct Student list[2] = {{"Sam", 85}, {"Ana", 92}};\n    // print each student\'s name and marks\n') }, quickCheck({ text: 'Which combination models a list of student records?', options: ['A single struct only', 'An array of structs', 'A 2D array of ints only', 'A single string'], correct_index: 1 })),
  lesson(3, 'Library Management', 9, { explanation: 'Extend the record pattern: track a book\'s title and a borrowed flag (0 or 1, since C has no built-in bool by default).', syntax: '', examples: [ex(MAIN('    struct Book { char title[20]; int borrowed; };\n    struct Book b = {"C Basics", 0};\n    b.borrowed = 1;\n    printf("%d\\n", b.borrowed);'), '1')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    struct Book { char title[20]; int borrowed; };\n    struct Book b = {"C Basics", 0};\n    b.borrowed = 1;\n    printf("%d\\n", b.borrowed);') }, quickCheck({ text: 'In plain C, how do you commonly represent a true/false borrowed status?', options: ['A string "yes"/"no" only', 'An int, 0 or 1', 'It cannot be represented', 'A struct'], correct_index: 1 })),
  lesson(4, 'Final C Project', 10, { explanation: 'Bring it together: a struct, an array of them, and a loop to search for one by name.', syntax: '', examples: [ex('#include <stdio.h>\n#include <string.h>\n\nstruct Item { char name[20]; };\n\nint main() {\n    struct Item items[3] = {{"Pen"}, {"Book"}, {"Bag"}};\n    for (int i = 0; i < 3; i++) {\n        if (strcmp(items[i].name, "Book") == 0) {\n            printf("Found: %s\\n", items[i].name);\n        }\n    }\n    return 0;\n}', 'Found: Book')], important_points: ['This shape — struct + array + search loop — is the same pattern behind most small record-management programs.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <stdio.h>\n#include <string.h>\n\nstruct Item { char name[20]; };\n\nint main() {\n    struct Item items[3] = {{"Pen"}, {"Book"}, {"Bag"}};\n    // find "Bag" and print "Found: Bag"\n    return 0;\n}' }, quickCheck({ type: 'code', text: 'Given items {Pen, Book, Bag}, find and print "Found: Bag".', starter_code: '#include <stdio.h>\n#include <string.h>\n\nstruct Item { char name[20]; };\n\nint main() {\n    struct Item items[3] = {{"Pen"}, {"Book"}, {"Bag"}};\n    for (int i = 0; i < 3; i++) {\n        if (strcmp(items[i].name, "Bag") == 0) {\n            printf("Found: %s\\n", items[i].name);\n        }\n    }\n    return 0;\n}', test_cases: [{ input: '', expected_output: 'Found: Bag' }] }))
];

module.exports = { M3, M4, M5, M6, M7, M8, M9, M10, M11, M12, M13, M14, M15 };
