/**
 * C++ Full Course — Modules 3-15, authored content (lighter-detail pass).
 */
let AUTO_ID = 92000;
function qid() { AUTO_ID += 1; return `cppq${AUTO_ID}`; }
function lesson(order, title, estMinutes, learn, practice, test) {
  return { order, title, est_minutes: estMinutes, content_ready: true, learn, practice, test };
}
function quickCheck(q) {
  if (q.type === 'code') return { questions: [{ id: qid(), type: 'code', text: q.text, language: 'cpp', starter_code: q.starter_code, test_cases: q.test_cases }] };
  return { questions: [{ id: qid(), type: 'mcq', text: q.text, options: q.options, correct_index: q.correct_index }] };
}
function ex(code, output) { return { code, output }; }
const MAIN = (body) => `#include <iostream>\nusing namespace std;\n\nint main() {\n${body}\n    return 0;\n}`;

const M3 = [
  lesson(1, 'Array Basics', 6, { explanation: 'An array holds a fixed number of same-type values, indexed from 0.', syntax: 'int nums[3] = {10, 20, 30};', examples: [ex(MAIN('    int nums[3] = {10, 20, 30};\n    cout << nums[1] << endl;'), '20')], important_points: ['C++ arrays don\'t check bounds either — same risk as C.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    int nums[3] = {10, 20, 30};\n    cout << nums[1] << endl;') }, quickCheck({ text: 'What is nums[0] for int nums[3] = {10,20,30}?', options: ['10', '20', '30', 'undefined'], correct_index: 0 })),
  lesson(2, '2D Arrays', 6, { explanation: 'A 2D array is a grid, accessed with two indexes: row then column.', syntax: 'int grid[2][2] = {{1,2},{3,4}};', examples: [ex(MAIN('    int grid[2][2] = {{1, 2}, {3, 4}};\n    cout << grid[1][0] << endl;'), '3')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    int grid[2][2] = {{1, 2}, {3, 4}};\n    cout << grid[1][0] << endl;') }, quickCheck({ text: 'For grid[2][2] = {{1,2},{3,4}}, what is grid[0][1]?', options: ['1', '2', '3', '4'], correct_index: 1 })),
  lesson(3, 'std::string Basics', 6, { explanation: 'std::string is C++\'s built-in string type — much safer and easier than C-style char arrays.', syntax: 'string name = "Sam";', examples: [ex(MAIN('    string name = "Sam";\n    cout << name.length() << endl;'), '3')], important_points: ['Unlike C strings, std::string handles its own memory and resizing automatically.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    string name = "Sam";\n    cout << name.length() << endl;') }, quickCheck({ text: 'What does "Sam".length() return for a std::string?', options: ['2', '3', '4', 'Error'], correct_index: 1 })),
  lesson(4, 'String Methods', 6, { explanation: 'std::string offers methods like substr, find, and + for concatenation.', syntax: 'str.substr(0, 3); str.find("a");', examples: [ex(MAIN('    string s = "hello";\n    cout << s.substr(0, 3) << endl;'), 'hel')], important_points: ['substr(start, length) — the second argument is a length, not an end index.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    string s = "hello";\n    cout << s.substr(0, 3) << endl;') }, quickCheck({ text: 'What does "hello".substr(0, 3) return?', options: ['"hel"', '"hell"', '"llo"', '"ello"'], correct_index: 0 })),
  lesson(5, 'Practice', 7, { explanation: 'Combine an array and a loop to print each element.', syntax: '', examples: [ex(MAIN('    string fruits[2] = {"apple", "banana"};\n    for (int i = 0; i < 2; i++) {\n        cout << fruits[i] << endl;\n    }'), 'apple\nbanana')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    int nums[4] = {1, 2, 3, 4};\n    // print the sum of nums\n') }, quickCheck({ type: 'code', text: 'Given int nums[4] = {1,2,3,4}, print their sum.', starter_code: MAIN('    int nums[4] = {1, 2, 3, 4};\n    // print the sum\n'), test_cases: [{ input: '', expected_output: '10' }] }))
];

const M4 = [
  lesson(1, 'Function Basics', 6, { explanation: 'A function groups reusable code under a name, with a return type and parameters.', syntax: 'int add(int a, int b) { return a + b; }', examples: [ex(MAIN('    int add(int a, int b);\n    cout << add(2, 3) << endl;\n    return 0;\n}\nint add(int a, int b) { return a + b; }'), '5')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\nusing namespace std;\n\nint add(int a, int b) { return a + b; }\n\nint main() {\n    cout << add(2, 3) << endl;\n    return 0;\n}' }, quickCheck({ text: 'What does the return type in "int add(...)" specify?', options: ['The function name', 'The type of value it returns', 'A parameter', 'Nothing important'], correct_index: 1 })),
  lesson(2, 'Default Arguments', 6, { explanation: 'A parameter can have a default value used automatically if the caller doesn\'t supply one.', syntax: 'void greet(string name = "friend") { ... }', examples: [ex('#include <iostream>\nusing namespace std;\n\nvoid greet(string name = "friend") {\n    cout << "Hi " << name << endl;\n}\n\nint main() {\n    greet();\n    return 0;\n}', 'Hi friend')], important_points: ['Default parameters must come after all non-default ones in the parameter list.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\nusing namespace std;\n\nvoid greet(string name = "friend") {\n    cout << "Hi " << name << endl;\n}\n\nint main() {\n    greet();\n    return 0;\n}' }, quickCheck({ text: 'What happens if you call greet() with no argument and a default is set?', options: ['A compile error', 'The default value is used', 'It always uses an empty string', 'It crashes'], correct_index: 1 })),
  lesson(3, 'Function Overloading', 7, { explanation: 'C++ lets you define multiple functions with the same name but different parameter types/counts.', syntax: 'int add(int a, int b);\ndouble add(double a, double b);', examples: [ex('#include <iostream>\nusing namespace std;\n\nint add(int a, int b) { return a + b; }\ndouble add(double a, double b) { return a + b; }\n\nint main() {\n    cout << add(2, 3) << endl;\n    return 0;\n}', '5')], important_points: ['The compiler picks the right overload based on the argument types you pass.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\nusing namespace std;\n\nint add(int a, int b) { return a + b; }\ndouble add(double a, double b) { return a + b; }\n\nint main() {\n    cout << add(2, 3) << endl;\n    return 0;\n}' }, quickCheck({ text: 'What does function overloading allow?', options: ['Recursive calls only', 'Multiple functions with the same name but different parameters', 'Global variables', 'Faster loops'], correct_index: 1 })),
  lesson(4, 'Recursion', 6, { explanation: 'A recursive function calls itself with a smaller input until a base case stops it.', syntax: 'int fact(int n) { if (n <= 1) return 1; return n * fact(n - 1); }', examples: [ex('#include <iostream>\nusing namespace std;\n\nint fact(int n) {\n    if (n <= 1) return 1;\n    return n * fact(n - 1);\n}\n\nint main() {\n    cout << fact(4) << endl;\n    return 0;\n}', '24')], important_points: ['Always define a base case, or the recursion never stops.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\nusing namespace std;\n\nint fact(int n) {\n    if (n <= 1) return 1;\n    return n * fact(n - 1);\n}\n\nint main() {\n    cout << fact(5) << endl;\n    return 0;\n}' }, quickCheck({ text: 'What stops a recursive function from calling itself forever?', options: ['Nothing, it always stops', 'The base case', 'The compiler', 'A timeout'], correct_index: 1 })),
  lesson(5, 'Inline Functions', 6, { explanation: '"inline" suggests to the compiler that a small function\'s code be inserted directly at the call site instead of doing a real function call.', syntax: 'inline int square(int n) { return n * n; }', examples: [ex('#include <iostream>\nusing namespace std;\n\ninline int square(int n) { return n * n; }\n\nint main() {\n    cout << square(4) << endl;\n    return 0;\n}', '16')], important_points: ['Modern compilers often inline small functions automatically, even without the keyword.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\nusing namespace std;\n\ninline int square(int n) { return n * n; }\n\nint main() {\n    cout << square(5) << endl;\n    return 0;\n}' }, quickCheck({ text: 'What does "inline" suggest to the compiler?', options: ['Make the function recursive', 'Insert the function\'s code directly at each call site', 'Make the function private', 'Run the function first'], correct_index: 1 }))
];

const M5 = [
  lesson(1, 'Pointer Basics', 6, { explanation: 'A pointer stores the memory address of a variable, same concept as in C.', syntax: 'int x = 5;\nint *p = &x;', examples: [ex(MAIN('    int x = 5;\n    int *p = &x;\n    cout << *p << endl;'), '5')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    int x = 5;\n    int *p = &x;\n    cout << *p << endl;') }, quickCheck({ text: 'What does *p do when p is a pointer to x?', options: ['Gets the address of x', 'Gets the value of x', 'Deletes x', 'Doubles x'], correct_index: 1 })),
  lesson(2, 'References', 6, { explanation: 'A reference is an alias for an existing variable — a second name for the same memory, set once at declaration.', syntax: 'int x = 5;\nint &ref = x;', examples: [ex(MAIN('    int x = 5;\n    int &ref = x;\n    ref = 10;\n    cout << x << endl;'), '10')], important_points: ['Unlike a pointer, a reference cannot be reassigned to refer to a different variable later.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    int x = 5;\n    int &ref = x;\n    ref = 10;\n    cout << x << endl;') }, quickCheck({ text: 'Changing "ref" (a reference to x) also changes:', options: ['Nothing else', 'x itself', 'Only a copy', 'It causes an error'], correct_index: 1 })),
  lesson(3, 'Pointers vs References', 6, { explanation: 'A pointer can be reassigned and can be null; a reference is bound once and always refers to a valid object.', syntax: '', examples: [ex('', '(conceptual comparison)')], important_points: ['Prefer references for simple "alias" use cases; use pointers when you need to reassign or represent "no value" (nullptr).'], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'Which can be reassigned to point somewhere else after creation?', options: ['A reference', 'A pointer', 'Both', 'Neither'], correct_index: 1 })),
  lesson(4, 'Dynamic Memory (new/delete)', 6, { explanation: 'new allocates memory on the heap in C++; delete frees it — the C++ equivalents of malloc/free.', syntax: 'int *p = new int(5);\ndelete p;', examples: [ex(MAIN('    int *p = new int(5);\n    cout << *p << endl;\n    delete p;'), '5')], important_points: ['Every "new" should be matched with exactly one "delete" to avoid memory leaks.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    int *p = new int(5);\n    cout << *p << endl;\n    delete p;') }, quickCheck({ text: 'What is the C++ equivalent of C\'s malloc/free?', options: ['alloc/dealloc', 'new/delete', 'create/destroy', 'make/remove'], correct_index: 1 }))
];

const M6 = [
  lesson(1, 'Classes', 6, { explanation: 'A class is a blueprint bundling data (fields) and behavior (methods) together.', syntax: 'class Dog {\npublic:\n    string name;\n};', examples: [ex(MAIN('    class Dog {\n    public:\n        string name;\n    };\n    Dog d;\n    d.name = "Rex";\n    cout << d.name << endl;'), 'Rex')], important_points: ['"public:" controls which members are accessible from outside the class.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    class Dog {\n    public:\n        string name;\n    };\n    Dog d;\n    d.name = "Rex";\n    cout << d.name << endl;') }, quickCheck({ text: 'What does the "public:" label control?', options: ['Which members outside code can access', 'How fast the class runs', 'Whether the class can be copied', 'Nothing'], correct_index: 0 })),
  lesson(2, 'Objects', 6, { explanation: 'An object is a concrete instance of a class — you can create many independent objects from one class.', syntax: 'Dog d1, d2;', examples: [ex(MAIN('    class Dog { public: string name; };\n    Dog d1, d2;\n    d1.name = "Rex";\n    d2.name = "Fido";\n    cout << d1.name << " " << d2.name << endl;'), 'Rex Fido')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    class Dog { public: string name; };\n    Dog d1, d2;\n    d1.name = "Rex";\n    d2.name = "Fido";\n    cout << d1.name << " " << d2.name << endl;') }, quickCheck({ text: 'How many independent objects can you create from one class?', options: ['Exactly one', 'Many, each with its own data', 'Zero', 'Only two'], correct_index: 1 })),
  lesson(3, 'Constructors', 6, { explanation: 'A constructor runs automatically when an object is created, setting up its initial state.', syntax: 'class Dog {\npublic:\n    string name;\n    Dog(string n) { name = n; }\n};', examples: [ex(MAIN('    class Dog {\n    public:\n        string name;\n        Dog(string n) { name = n; }\n    };\n    Dog d("Rex");\n    cout << d.name << endl;'), 'Rex')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    class Dog {\n    public:\n        string name;\n        Dog(string n) { name = n; }\n    };\n    Dog d("Rex");\n    cout << d.name << endl;') }, quickCheck({ text: 'When does a constructor run?', options: ['Only when explicitly called by name', 'Automatically when the object is created', 'Never automatically', 'Only on program exit'], correct_index: 1 })),
  lesson(4, 'Destructors', 6, { explanation: 'A destructor runs automatically when an object is destroyed, useful for cleanup like freeing memory.', syntax: 'class Dog {\npublic:\n    ~Dog() { cout << "destroyed"; }\n};', examples: [ex(MAIN('    class Dog {\n    public:\n        ~Dog() { cout << "bye"; }\n    };\n    { Dog d; }\n    cout << endl;'), 'bye')], important_points: ['A destructor\'s name is the class name prefixed with ~ and it takes no parameters.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    class Dog {\n    public:\n        ~Dog() { cout << "bye"; }\n    };\n    { Dog d; }\n    cout << endl;') }, quickCheck({ text: 'When does a destructor run?', options: ['When the object is created', 'When the object is destroyed', 'Every time a method is called', 'Never'], correct_index: 1 })),
  lesson(5, 'this Pointer', 6, { explanation: '"this" is a pointer to the current object inside a member function, letting you distinguish a field from a parameter of the same name.', syntax: 'this->name = name;', examples: [ex(MAIN('    class Dog {\n    public:\n        string name;\n        void setName(string name) { this->name = name; }\n    };\n    Dog d;\n    d.setName("Rex");\n    cout << d.name << endl;'), 'Rex')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    class Dog {\n    public:\n        string name;\n        void setName(string name) { this->name = name; }\n    };\n    Dog d;\n    d.setName("Rex");\n    cout << d.name << endl;') }, quickCheck({ text: 'What does "this" refer to inside a member function?', options: ['A random object', 'The current object', 'The class itself, not an instance', 'Nothing in C++'], correct_index: 1 })),
];
// Encapsulation appended as 6th lesson of M6 to match outline count (6 lessons: Classes, Objects, Constructors, Destructors, this Pointer, Encapsulation)
M6.push(lesson(6, 'Encapsulation', 6, { explanation: 'Encapsulation means keeping fields private and exposing controlled access through public getter/setter methods.', syntax: 'private:\n    int age;\npublic:\n    int getAge() { return age; }', examples: [ex(MAIN('    class Person {\n        int age;\n    public:\n        void setAge(int a) { if (a >= 0) age = a; }\n        int getAge() { return age; }\n    };\n    Person p;\n    p.setAge(20);\n    cout << p.getAge() << endl;'), '20')], important_points: ['Fields are private by default in a class — you must add "public:" to expose them.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    class Person {\n        int age;\n    public:\n        void setAge(int a) { if (a >= 0) age = a; }\n        int getAge() { return age; }\n    };\n    Person p;\n    p.setAge(20);\n    cout << p.getAge() << endl;') }, quickCheck({ text: 'By default, are a class\'s members public or private in C++?', options: ['Public', 'Private', 'Depends on the compiler', 'Protected'], correct_index: 1 })));

const M7 = [
  lesson(1, 'Inheritance Basics', 7, { explanation: 'A derived class inherits fields/methods from a base class using a colon.', syntax: 'class Dog : public Animal { };', examples: [ex(MAIN('    class Animal { public: void eat() { cout << "eating"; } };\n    class Dog : public Animal { };\n    Dog d;\n    d.eat();\n    cout << endl;'), 'eating')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    class Animal { public: void eat() { cout << "eating"; } };\n    class Dog : public Animal { };\n    Dog d;\n    d.eat();\n    cout << endl;') }, quickCheck({ text: 'What does "class Dog : public Animal" mean?', options: ['Dog implements an interface', 'Dog inherits from Animal', 'Dog is a friend of Animal', 'A syntax error'], correct_index: 1 })),
  lesson(2, 'Multiple Inheritance', 6, { explanation: 'C++ allows a class to inherit from more than one base class at once — a feature not all languages (like Java) support.', syntax: 'class C : public A, public B { };', examples: [ex('', '(conceptual — class C : public A, public B combines members from both)')], important_points: ['Multiple inheritance can cause ambiguity if two base classes define the same member name.'], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'Can a C++ class inherit from more than one base class?', options: ['No, never', 'Yes, via multiple inheritance', 'Only with interfaces', 'Only in C++20'], correct_index: 1 })),
  lesson(3, 'Virtual Functions', 7, { explanation: 'A virtual function lets a derived class override behavior, and the correct version runs even through a base-class pointer/reference.', syntax: 'virtual void sound() { }', examples: [ex(MAIN('    class Animal { public: virtual void sound() { cout << "..."; } };\n    class Dog : public Animal { public: void sound() override { cout << "Bark"; } };\n    Animal *a = new Dog();\n    a->sound();\n    cout << endl;'), 'Bark')], important_points: ['Without "virtual", calling through a base pointer would run the base class\'s version instead — this is what enables polymorphism.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    class Animal { public: virtual void sound() { cout << "..."; } };\n    class Dog : public Animal { public: void sound() override { cout << "Bark"; } };\n    Animal *a = new Dog();\n    a->sound();\n    cout << endl;') }, quickCheck({ text: 'What does "virtual" enable on a base class method?', options: ['Faster execution', 'The derived class\'s override to run via a base pointer/reference', 'Automatic memory management', 'Multiple inheritance'], correct_index: 1 })),
  lesson(4, 'Abstract Classes', 6, { explanation: 'A class with at least one pure virtual function (= 0) is abstract and cannot be instantiated directly.', syntax: 'virtual double area() = 0;', examples: [ex(MAIN('    class Shape { public: virtual double area() = 0; };\n    class Circle : public Shape { public: double area() override { return 3.14 * 4; } };\n    Shape *s = new Circle();\n    cout << s->area() << endl;'), '12.56')], important_points: ['"= 0" marks a pure virtual function — the class becomes abstract until a subclass implements it.'], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    class Shape { public: virtual double area() = 0; };\n    class Circle : public Shape { public: double area() override { return 3.14 * 4; } };\n    Shape *s = new Circle();\n    cout << s->area() << endl;') }, quickCheck({ text: 'What makes a C++ class "abstract"?', options: ['Having a constructor', 'Having at least one pure virtual function (= 0)', 'Having no fields', 'Being declared "final"'], correct_index: 1 })),
  lesson(5, 'Operator Overloading', 7, { explanation: 'C++ lets you redefine how operators like + behave for your own classes.', syntax: 'Point operator+(const Point &other) { return Point(x + other.x, y + other.y); }', examples: [ex('#include <iostream>\nusing namespace std;\n\nclass Point {\npublic:\n    int x;\n    Point(int x) : x(x) {}\n    Point operator+(const Point &o) { return Point(x + o.x); }\n};\n\nint main() {\n    Point a(2), b(3);\n    Point c = a + b;\n    cout << c.x << endl;\n    return 0;\n}', '5')], important_points: ['Operator overloading lets custom types be used with natural syntax like a + b instead of a.add(b).'], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\nusing namespace std;\n\nclass Point {\npublic:\n    int x;\n    Point(int x) : x(x) {}\n    Point operator+(const Point &o) { return Point(x + o.x); }\n};\n\nint main() {\n    Point a(2), b(3);\n    Point c = a + b;\n    cout << c.x << endl;\n    return 0;\n}' }, quickCheck({ text: 'What does operator overloading let you do?', options: ['Redefine what operators like + do for your own types', 'Change how the compiler runs', 'Remove operators from the language', 'Only overload +'], correct_index: 0 }))
];

const M8 = [
  lesson(1, 'Function Templates', 7, { explanation: 'A function template works with any type, decided at the call site, avoiding rewriting the same function per type.', syntax: 'template <typename T>\nT maxVal(T a, T b) { return a > b ? a : b; }', examples: [ex('#include <iostream>\nusing namespace std;\n\ntemplate <typename T>\nT maxVal(T a, T b) { return a > b ? a : b; }\n\nint main() {\n    cout << maxVal(3, 7) << endl;\n    return 0;\n}', '7')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\nusing namespace std;\n\ntemplate <typename T>\nT maxVal(T a, T b) { return a > b ? a : b; }\n\nint main() {\n    cout << maxVal(3, 7) << endl;\n    return 0;\n}' }, quickCheck({ text: 'What does "template <typename T>" let a function do?', options: ['Only work with int', 'Work generically with any type T', 'Run faster automatically', 'Avoid needing a return type'], correct_index: 1 })),
  lesson(2, 'Class Templates', 6, { explanation: 'A class template is a class parameterized by a type, like a custom generic container.', syntax: 'template <typename T>\nclass Box { public: T value; };', examples: [ex(MAIN('    template <typename T>\n    class Box { public: T value; };\n    Box<int> b;\n    b.value = 5;\n    cout << b.value << endl;'), '5')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    template <typename T>\n    class Box { public: T value; };\n    Box<int> b;\n    b.value = 5;\n    cout << b.value << endl;') }, quickCheck({ text: 'What does Box<int> mean for a class template Box<T>?', options: ['Box works only with strings', 'T is specialized to int for this Box', 'A syntax error', 'Box has 4 bytes'], correct_index: 1 })),
  lesson(3, 'Template Practice', 7, { explanation: 'Practice: write a generic swap function using a template.', syntax: '', examples: [ex('#include <iostream>\nusing namespace std;\n\ntemplate <typename T>\nvoid mySwap(T &a, T &b) {\n    T temp = a; a = b; b = temp;\n}\n\nint main() {\n    int x = 1, y = 2;\n    mySwap(x, y);\n    cout << x << " " << y << endl;\n    return 0;\n}', '2 1')], important_points: ['Using references (T&) here means mySwap modifies the caller\'s actual variables.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\nusing namespace std;\n\ntemplate <typename T>\nvoid mySwap(T &a, T &b) {\n    T temp = a; a = b; b = temp;\n}\n\nint main() {\n    int x = 3, y = 9;\n    mySwap(x, y);\n    cout << x << " " << y << endl;\n    return 0;\n}' }, quickCheck({ text: 'Why use T& (a reference) as the parameter type in mySwap?', options: ['So it can modify the caller\'s actual variables', 'It is required syntax for templates', 'To make it read-only', 'It has no effect'], correct_index: 0 }))
];

const M9 = [
  lesson(1, 'vector', 6, { explanation: 'std::vector is a resizable array — the most commonly used STL container.', syntax: 'vector<int> v;\nv.push_back(5);', examples: [ex('#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n    vector<int> v;\n    v.push_back(1);\n    v.push_back(2);\n    cout << v[1] << endl;\n    return 0;\n}', '2')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n    vector<int> v;\n    v.push_back(1);\n    v.push_back(2);\n    cout << v[1] << endl;\n    return 0;\n}' }, quickCheck({ text: 'What does v.push_back(5) do to a vector?', options: ['Removes the last element', 'Adds 5 to the end', 'Sorts the vector', 'Clears the vector'], correct_index: 1 })),
  lesson(2, 'map', 6, { explanation: 'std::map stores sorted key-value pairs with fast lookup by key.', syntax: 'map<string, int> ages;\nages["Sam"] = 20;', examples: [ex('#include <iostream>\n#include <map>\nusing namespace std;\n\nint main() {\n    map<string, int> ages;\n    ages["Sam"] = 20;\n    cout << ages["Sam"] << endl;\n    return 0;\n}', '20')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\n#include <map>\nusing namespace std;\n\nint main() {\n    map<string, int> ages;\n    ages["Sam"] = 20;\n    cout << ages["Sam"] << endl;\n    return 0;\n}' }, quickCheck({ text: 'A std::map stores data as:', options: ['A single sorted list of values', 'Key-value pairs', 'A fixed-size array', 'Only integers'], correct_index: 1 })),
  lesson(3, 'set', 6, { explanation: 'std::set stores unique values in sorted order — adding a duplicate has no effect.', syntax: 'set<int> nums;\nnums.insert(5);', examples: [ex('#include <iostream>\n#include <set>\nusing namespace std;\n\nint main() {\n    set<int> nums;\n    nums.insert(5);\n    nums.insert(5);\n    cout << nums.size() << endl;\n    return 0;\n}', '1')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\n#include <set>\nusing namespace std;\n\nint main() {\n    set<int> nums;\n    nums.insert(5);\n    nums.insert(5);\n    cout << nums.size() << endl;\n    return 0;\n}' }, quickCheck({ text: 'After inserting 5 twice into a set, its size is:', options: ['0', '1', '2', 'Error'], correct_index: 1 })),
  lesson(4, 'pair', 6, { explanation: 'std::pair bundles two values of possibly different types together, accessed via .first and .second.', syntax: 'pair<string, int> p = {"Sam", 20};', examples: [ex('#include <iostream>\n#include <utility>\nusing namespace std;\n\nint main() {\n    pair<string, int> p = {"Sam", 20};\n    cout << p.first << " " << p.second << endl;\n    return 0;\n}', 'Sam 20')], important_points: ['map internally stores its entries as pair<key, value>.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\n#include <utility>\nusing namespace std;\n\nint main() {\n    pair<string, int> p = {"Sam", 20};\n    cout << p.first << " " << p.second << endl;\n    return 0;\n}' }, quickCheck({ text: 'How do you access the two values in a std::pair p?', options: ['p[0], p[1]', 'p.first, p.second', 'p.a, p.b', 'p.left, p.right'], correct_index: 1 })),
  lesson(5, 'algorithm basics', 6, { explanation: 'The <algorithm> header provides ready-made functions like sort() and find() that work across containers.', syntax: 'sort(v.begin(), v.end());', examples: [ex('#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    vector<int> v = {3, 1, 2};\n    sort(v.begin(), v.end());\n    cout << v[0] << endl;\n    return 0;\n}', '1')], important_points: ['sort/find take iterator ranges (.begin(), .end()), not the container itself.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    vector<int> v = {3, 1, 2};\n    sort(v.begin(), v.end());\n    cout << v[0] << endl;\n    return 0;\n}' }, quickCheck({ text: 'What does sort(v.begin(), v.end()) do?', options: ['Reverses v', 'Sorts v in ascending order', 'Removes duplicates', 'Prints v'], correct_index: 1 }))
];

const M10 = [
  lesson(1, 'try/catch', 6, { explanation: 'try/catch lets your program handle a runtime error instead of crashing.', syntax: 'try { ... } catch (exception &e) { ... }', examples: [ex('#include <iostream>\nusing namespace std;\n\nint main() {\n    try {\n        throw runtime_error("bad input");\n    } catch (exception &e) {\n        cout << e.what() << endl;\n    }\n    return 0;\n}', 'bad input')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\nusing namespace std;\n\nint main() {\n    try {\n        throw runtime_error("bad input");\n    } catch (exception &e) {\n        cout << e.what() << endl;\n    }\n    return 0;\n}' }, quickCheck({ text: 'What does e.what() return for a caught exception?', options: ['The exception\'s type only', 'A human-readable error message', 'Nothing', 'The line number'], correct_index: 1 })),
  lesson(2, 'throw', 6, { explanation: '"throw" raises an exception, on purpose, when something invalid happens.', syntax: 'throw invalid_argument("bad value");', examples: [ex('#include <iostream>\nusing namespace std;\n\nvoid check(int age) {\n    if (age < 0) throw invalid_argument("negative age");\n    cout << "OK: " << age << endl;\n}\n\nint main() {\n    check(20);\n    return 0;\n}', 'OK: 20')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\nusing namespace std;\n\nvoid check(int age) {\n    if (age < 0) throw invalid_argument("negative age");\n    cout << "OK: " << age << endl;\n}\n\nint main() {\n    check(20);\n    return 0;\n}' }, quickCheck({ text: 'What does "throw" do?', options: ['Catches an exception', 'Raises an exception', 'Prints a message only', 'Ends the program silently'], correct_index: 1 })),
  lesson(3, 'Custom Exceptions', 7, { explanation: 'You can define your own exception type by inheriting from std::exception (or a subclass like runtime_error).', syntax: 'class MyError : public exception {\npublic:\n    const char* what() const noexcept override { return "custom error"; }\n};', examples: [ex('#include <iostream>\nusing namespace std;\n\nclass MyError : public exception {\npublic:\n    const char* what() const noexcept override { return "custom error"; }\n};\n\nint main() {\n    try {\n        throw MyError();\n    } catch (exception &e) {\n        cout << e.what() << endl;\n    }\n    return 0;\n}', 'custom error')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\nusing namespace std;\n\nclass MyError : public exception {\npublic:\n    const char* what() const noexcept override { return "custom error"; }\n};\n\nint main() {\n    try {\n        throw MyError();\n    } catch (exception &e) {\n        cout << e.what() << endl;\n    }\n    return 0;\n}' }, quickCheck({ text: 'To create a custom exception type, you typically:', options: ['Inherit from std::exception', 'Use only built-in types', 'Write a plain int', 'It is not possible in C++'], correct_index: 0 }))
];

const M11 = [
  lesson(1, 'ifstream', 6, { explanation: 'ifstream reads from a file, similar to how cin reads from the keyboard.', syntax: 'ifstream file("data.txt");\nstring line;\ngetline(file, line);', examples: [ex('', '(conceptual — reading requires an actual file present)')], important_points: ['Always check "if (file.is_open())" before reading, in case the file doesn\'t exist.'], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'Which stream type reads from a file?', options: ['ofstream', 'ifstream', 'cout', 'cin only'], correct_index: 1 })),
  lesson(2, 'ofstream', 6, { explanation: 'ofstream writes to a file, similar to how cout writes to the screen.', syntax: 'ofstream file("out.txt");\nfile << "hello";', examples: [ex('#include <iostream>\n#include <fstream>\nusing namespace std;\n\nint main() {\n    ofstream file("out.txt");\n    file << "hello";\n    file.close();\n    cout << "written" << endl;\n    return 0;\n}', 'written')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\n#include <fstream>\nusing namespace std;\n\nint main() {\n    ofstream file("out.txt");\n    file << "hello";\n    file.close();\n    cout << "written" << endl;\n    return 0;\n}' }, quickCheck({ text: 'Which stream type writes to a file?', options: ['ifstream', 'ofstream', 'cin', 'cerr only'], correct_index: 1 })),
  lesson(3, 'File Modes', 6, { explanation: 'File streams accept mode flags like ios::app (append) or ios::trunc (overwrite).', syntax: 'ofstream file("out.txt", ios::app);', examples: [ex('', 'ios::app opens for appending instead of overwriting the file.')], important_points: [], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'Which mode flag appends instead of overwriting a file?', options: ['ios::trunc', 'ios::app', 'ios::in', 'ios::binary'], correct_index: 1 }))
];

const M12 = [
  lesson(1, 'Smart Pointers', 7, { explanation: 'A smart pointer (like unique_ptr) automatically deletes its owned memory when it goes out of scope, avoiding manual delete calls.', syntax: 'unique_ptr<int> p = make_unique<int>(5);', examples: [ex('#include <iostream>\n#include <memory>\nusing namespace std;\n\nint main() {\n    unique_ptr<int> p = make_unique<int>(5);\n    cout << *p << endl;\n    return 0;\n}', '5')], important_points: ['unique_ptr auto-frees its memory when it goes out of scope — no manual delete needed.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\n#include <memory>\nusing namespace std;\n\nint main() {\n    unique_ptr<int> p = make_unique<int>(5);\n    cout << *p << endl;\n    return 0;\n}' }, quickCheck({ text: 'What is the main advantage of unique_ptr over a raw pointer?', options: ['It runs code faster', 'It automatically frees its memory', 'It can point to multiple things at once', 'It cannot be dereferenced'], correct_index: 1 })),
  lesson(2, 'Lambda Expressions', 6, { explanation: 'A lambda is a short, inline anonymous function, often used with algorithms like sort.', syntax: 'auto add = [](int a, int b) { return a + b; };', examples: [ex('#include <iostream>\nusing namespace std;\n\nint main() {\n    auto add = [](int a, int b) { return a + b; };\n    cout << add(2, 3) << endl;\n    return 0;\n}', '5')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\nusing namespace std;\n\nint main() {\n    auto add = [](int a, int b) { return a + b; };\n    cout << add(2, 3) << endl;\n    return 0;\n}' }, quickCheck({ text: 'What is a lambda expression mainly used for?', options: ['Declaring global variables', 'A short inline anonymous function', 'Memory allocation', 'File I/O'], correct_index: 1 })),
  lesson(3, 'Move Semantics', 7, { explanation: 'std::move converts an object to an "rvalue", letting its resources be transferred instead of copied — efficient for large objects like vectors.', syntax: 'vector<int> b = std::move(a);', examples: [ex('#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n    vector<int> a = {1, 2, 3};\n    vector<int> b = std::move(a);\n    cout << b.size() << endl;\n    return 0;\n}', '3')], important_points: ['After std::move(a), "a" is left in a valid but unspecified state — don\'t rely on its contents afterward.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n    vector<int> a = {1, 2, 3};\n    vector<int> b = std::move(a);\n    cout << b.size() << endl;\n    return 0;\n}' }, quickCheck({ text: 'What does std::move mainly enable?', options: ['Deleting an object', 'Transferring resources instead of copying them', 'Comparing two objects', 'Sorting a container'], correct_index: 1 }))
];

const M13 = [
  lesson(1, 'Linked Lists', 7, { explanation: 'A linked list node holds a value and a pointer to the next node — same idea as C, using "new" for allocation.', syntax: 'struct Node { int val; Node *next; };', examples: [ex('#include <iostream>\nusing namespace std;\n\nstruct Node { int val; Node *next; };\n\nint main() {\n    Node *head = new Node{10, nullptr};\n    cout << head->val << endl;\n    return 0;\n}', '10')], important_points: ['nullptr is C++\'s type-safe replacement for C\'s NULL.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\nusing namespace std;\n\nstruct Node { int val; Node *next; };\n\nint main() {\n    Node *head = new Node{10, nullptr};\n    cout << head->val << endl;\n    return 0;\n}' }, quickCheck({ text: 'What does nullptr represent in C++?', options: ['Zero', 'A pointer that points to nothing', 'An error code', 'An empty string'], correct_index: 1 })),
  lesson(2, 'Stacks', 6, { explanation: 'std::stack provides a ready-made LIFO container.', syntax: 'stack<int> s;\ns.push(1);\ns.pop();', examples: [ex('#include <iostream>\n#include <stack>\nusing namespace std;\n\nint main() {\n    stack<int> s;\n    s.push(1);\n    s.push(2);\n    cout << s.top() << endl;\n    return 0;\n}', '2')], important_points: ['top() reads the top element without removing it; pop() removes it (and returns nothing).'], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\n#include <stack>\nusing namespace std;\n\nint main() {\n    stack<int> s;\n    s.push(1);\n    s.push(2);\n    cout << s.top() << endl;\n    return 0;\n}' }, quickCheck({ text: 'What does s.top() do on a std::stack?', options: ['Removes the top element', 'Returns the top element without removing it', 'Empties the stack', 'Returns the bottom element'], correct_index: 1 })),
  lesson(3, 'Queues', 6, { explanation: 'std::queue provides a ready-made FIFO container.', syntax: 'queue<int> q;\nq.push(1);\nq.pop();', examples: [ex('#include <iostream>\n#include <queue>\nusing namespace std;\n\nint main() {\n    queue<int> q;\n    q.push(1);\n    q.push(2);\n    cout << q.front() << endl;\n    return 0;\n}', '1')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\n#include <queue>\nusing namespace std;\n\nint main() {\n    queue<int> q;\n    q.push(1);\n    q.push(2);\n    cout << q.front() << endl;\n    return 0;\n}' }, quickCheck({ text: 'What does q.front() return on a std::queue?', options: ['The most recently added element', 'The oldest (first-in) element', 'A random element', 'Nothing, it errors'], correct_index: 1 })),
  lesson(4, 'Searching', 6, { explanation: 'std::find performs a linear search over a range, returning an iterator to the first match (or end()).', syntax: 'find(v.begin(), v.end(), target);', examples: [ex('#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    vector<int> v = {1, 3, 5};\n    auto it = find(v.begin(), v.end(), 3);\n    cout << (it != v.end()) << endl;\n    return 0;\n}', '1')], important_points: ['If find() reaches v.end(), the value wasn\'t found.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    vector<int> v = {1, 3, 5};\n    auto it = find(v.begin(), v.end(), 3);\n    cout << (it != v.end()) << endl;\n    return 0;\n}' }, quickCheck({ text: 'What does find() return if the value is not found?', options: ['-1', 'v.end()', 'nullptr', 'It throws'], correct_index: 1 })),
  lesson(5, 'Sorting', 6, { explanation: 'sort() from <algorithm> is the standard way to sort a vector in ascending order.', syntax: 'sort(v.begin(), v.end());', examples: [ex('#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    vector<int> v = {5, 2, 8, 1};\n    sort(v.begin(), v.end());\n    cout << v[0] << endl;\n    return 0;\n}', '1')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    vector<int> v = {5, 2, 8, 1};\n    sort(v.begin(), v.end());\n    cout << v[0] << endl;\n    return 0;\n}' }, quickCheck({ text: 'What order does sort(v.begin(), v.end()) produce by default?', options: ['Descending', 'Ascending', 'Random', 'Unchanged'], correct_index: 1 }))
];

const M14 = [
  lesson(1, 'Trees Basics', 7, { explanation: 'A binary tree node has a value and pointers to left/right children.', syntax: 'struct Node { int val; Node *left, *right; };', examples: [ex('#include <iostream>\nusing namespace std;\n\nstruct Node { int val; Node *left, *right; };\n\nint main() {\n    Node *root = new Node{10, nullptr, nullptr};\n    cout << root->val << endl;\n    return 0;\n}', '10')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\nusing namespace std;\n\nstruct Node { int val; Node *left, *right; };\n\nint main() {\n    Node *root = new Node{10, nullptr, nullptr};\n    cout << root->val << endl;\n    return 0;\n}' }, quickCheck({ text: 'How many children does a binary tree node have at most?', options: ['1', '2', '3', 'Unlimited'], correct_index: 1 })),
  lesson(2, 'Graphs Basics', 7, { explanation: 'A graph is commonly represented in C++ as a map (or vector) from a node to its list of neighbors.', syntax: 'map<int, vector<int>> graph;', examples: [ex('#include <iostream>\n#include <map>\n#include <vector>\nusing namespace std;\n\nint main() {\n    map<int, vector<int>> graph;\n    graph[1] = {2, 3};\n    cout << graph[1][0] << endl;\n    return 0;\n}', '2')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\n#include <map>\n#include <vector>\nusing namespace std;\n\nint main() {\n    map<int, vector<int>> graph;\n    graph[1] = {2, 3};\n    cout << graph[1][0] << endl;\n    return 0;\n}' }, quickCheck({ text: 'What is a common way to represent a graph in code?', options: ['A single int', 'A map/list from each node to its neighbors', 'A string', 'It cannot be represented'], correct_index: 1 })),
  lesson(3, 'Problem Solving', 8, { explanation: 'Apply a vector + loop to solve a small problem: count occurrences of a value.', syntax: '', examples: [ex('#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n    vector<int> arr = {1, 2, 2, 3, 1, 1};\n    int count = 0;\n    for (int n : arr) if (n == 1) count++;\n    cout << count << endl;\n    return 0;\n}', '3')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n    vector<int> arr = {4, 4, 5, 6, 4};\n    // print how many times 4 appears\n    return 0;\n}' }, quickCheck({ type: 'code', text: 'Given vector<int> arr = {4,4,5,6,4}, print how many times 4 appears.', starter_code: '#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n    vector<int> arr = {4, 4, 5, 6, 4};\n    int count = 0;\n    for (int n : arr) if (n == 4) count++;\n    cout << count << endl;\n    return 0;\n}', test_cases: [{ input: '', expected_output: '3' }] }))
];

const M15 = [
  lesson(1, 'Calculator', 8, { explanation: 'Build a simple calculator using a function that branches on an operator character.', syntax: '', examples: [ex(MAIN('    auto calc = [](int a, int b, char op) {\n        if (op == \'+\') return a + b;\n        return 0;\n    };\n    cout << calc(4, 3, \'+\') << endl;'), '7')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    auto calc = [](int a, int b, char op) {\n        if (op == \'+\') return a + b;\n        if (op == \'-\') return a - b;\n        return 0;\n    };\n    cout << calc(10, 4, \'-\') << endl;') }, quickCheck({ type: 'code', text: 'Extend calc to support \'*\' and print calc(6, 7, \'*\').', starter_code: MAIN('    auto calc = [](int a, int b, char op) {\n        if (op == \'+\') return a + b;\n        if (op == \'-\') return a - b;\n        if (op == \'*\') return a * b;\n        return 0;\n    };\n    cout << calc(6, 7, \'*\') << endl;'), test_cases: [{ input: '', expected_output: '42' }] })),
  lesson(2, 'Bank Management System', 9, { explanation: 'Model an Account with a class holding a balance, and methods to deposit/withdraw.', syntax: '', examples: [ex(MAIN('    class Account {\n    public:\n        double balance = 0;\n        void deposit(double amt) { balance += amt; }\n    };\n    Account a;\n    a.deposit(100);\n    cout << a.balance << endl;'), '100')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: MAIN('    class Account {\n    public:\n        double balance = 0;\n        void deposit(double amt) { balance += amt; }\n        void withdraw(double amt) { if (amt <= balance) balance -= amt; }\n    };\n    Account a;\n    a.deposit(200);\n    a.withdraw(50);\n    cout << a.balance << endl;') }, quickCheck({ text: 'Why check "if (amt <= balance)" before withdrawing?', options: ['To speed up the program', 'To prevent the balance from going negative', 'It is required syntax', 'It has no purpose'], correct_index: 1 })),
  lesson(3, 'Inventory System', 9, { explanation: 'Track a list of Item objects with quantities using a vector of a class.', syntax: '', examples: [ex('#include <iostream>\n#include <vector>\n#include <string>\nusing namespace std;\n\nclass Item {\npublic:\n    string name; int qty;\n};\n\nint main() {\n    vector<Item> items;\n    items.push_back({"Pen", 10});\n    cout << items[0].name << " " << items[0].qty << endl;\n    return 0;\n}', 'Pen 10')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\n#include <vector>\n#include <string>\nusing namespace std;\n\nclass Item {\npublic:\n    string name; int qty;\n};\n\nint main() {\n    vector<Item> items;\n    items.push_back({"Pen", 10});\n    items.push_back({"Book", 5});\n    // print each item\'s name and qty\n    return 0;\n}' }, quickCheck({ text: 'Which combination models a list of inventory items?', options: ['A single class instance', 'A vector of a class holding name + quantity', 'A single int', 'A string only'], correct_index: 1 })),
  lesson(4, 'Final C++ Project', 10, { explanation: 'Bring it together: a class, a vector of them, and a loop to search for one by name.', syntax: '', examples: [ex('#include <iostream>\n#include <vector>\n#include <string>\nusing namespace std;\n\nclass Item {\npublic:\n    string name;\n};\n\nint main() {\n    vector<Item> items = {{"Pen"}, {"Book"}, {"Bag"}};\n    for (auto &i : items) {\n        if (i.name == "Bag") cout << "Found: " << i.name << endl;\n    }\n    return 0;\n}', 'Found: Bag')], important_points: ['This pattern — class + vector + range-for search — scales up directly into real applications.'], common_mistakes: [], real_world: '' }, { starter_code: '#include <iostream>\n#include <vector>\n#include <string>\nusing namespace std;\n\nclass Item {\npublic:\n    string name;\n};\n\nint main() {\n    vector<Item> items = {{"Pen"}, {"Book"}, {"Bag"}};\n    // find "Bag" and print "Found: Bag"\n    return 0;\n}' }, quickCheck({ type: 'code', text: 'Given items {Pen, Book, Bag}, print "Found: Bag" when found.', starter_code: '#include <iostream>\n#include <vector>\n#include <string>\nusing namespace std;\n\nclass Item {\npublic:\n    string name;\n};\n\nint main() {\n    vector<Item> items = {{"Pen"}, {"Book"}, {"Bag"}};\n    for (auto &i : items) {\n        if (i.name == "Bag") cout << "Found: " << i.name << endl;\n    }\n    return 0;\n}', test_cases: [{ input: '', expected_output: 'Found: Bag' }] }))
];

module.exports = { M3, M4, M5, M6, M7, M8, M9, M10, M11, M12, M13, M14, M15 };
