/**
 * JavaScript Full Course — Modules 3-15, authored content (lighter-detail pass).
 */
let AUTO_ID = 93000;
function qid() { AUTO_ID += 1; return `jsq${AUTO_ID}`; }
function lesson(order, title, estMinutes, learn, practice, test) {
  return { order, title, est_minutes: estMinutes, content_ready: true, learn, practice, test };
}
function quickCheck(q) {
  if (q.type === 'code') return { questions: [{ id: qid(), type: 'code', text: q.text, language: 'javascript', starter_code: q.starter_code, test_cases: q.test_cases }] };
  return { questions: [{ id: qid(), type: 'mcq', text: q.text, options: q.options, correct_index: q.correct_index }] };
}
function ex(code, output) { return { code, output }; }

const M3 = [
  lesson(1, 'Array Basics', 6, { explanation: 'An array holds an ordered list of values, indexed from 0, and can grow or shrink freely.', syntax: 'let nums = [10, 20, 30];', examples: [ex('let nums = [10, 20, 30];\nconsole.log(nums[1]);', '20')], important_points: ['JavaScript arrays can hold mixed types and resize automatically — no fixed size like in C/Java.'], common_mistakes: [], real_world: '' }, { starter_code: 'let nums = [10, 20, 30];\nconsole.log(nums[1]);' }, quickCheck({ text: 'What is nums[0] for let nums = [10, 20, 30]?', options: ['10', '20', '30', 'undefined'], correct_index: 0 })),
  lesson(2, 'Array Methods', 6, { explanation: 'Arrays come with built-in methods like push, pop, map, and filter for common operations.', syntax: 'arr.push(4); arr.map(x => x * 2);', examples: [ex('let nums = [1, 2, 3];\nlet doubled = nums.map(x => x * 2);\nconsole.log(doubled);', '[ 2, 4, 6 ]')], important_points: ['map() returns a brand-new array — it does not modify the original.'], common_mistakes: [], real_world: '' }, { starter_code: 'let nums = [1, 2, 3];\nlet doubled = nums.map(x => x * 2);\nconsole.log(doubled);' }, quickCheck({ text: 'Does array.map() modify the original array?', options: ['Yes, always', 'No — it returns a new array', 'Only for numbers', 'It depends on the browser'], correct_index: 1 })),
  lesson(3, 'String Basics', 6, { explanation: 'A string is text wrapped in quotes — single, double, or backticks.', syntax: 'let name = "Sam";', examples: [ex('let name = "Sam";\nconsole.log(name.length);', '3')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'let name = "Sam";\nconsole.log(name.length);' }, quickCheck({ text: 'What does "Sam".length return?', options: ['2', '3', '4', 'undefined'], correct_index: 1 })),
  lesson(4, 'String Methods', 6, { explanation: 'Strings have built-in methods like toUpperCase, slice, and includes for common text operations.', syntax: 'str.toUpperCase(); str.slice(0, 3);', examples: [ex('let s = "hello";\nconsole.log(s.toUpperCase());', 'HELLO')], important_points: ['Strings are immutable in JS — these methods return a new string rather than changing the original.'], common_mistakes: [], real_world: '' }, { starter_code: 'let s = "hello";\nconsole.log(s.toUpperCase());' }, quickCheck({ text: 'What does "hello".slice(0, 3) return?', options: ['"hel"', '"hell"', '"llo"', '"ello"'], correct_index: 0 })),
  lesson(5, 'Template Literals', 6, { explanation: 'Template literals (backtick strings) let you embed variables directly with ${...}, without manual concatenation.', syntax: 'let msg = `Hi ${name}`;', examples: [ex('let name = "Sam";\nlet msg = `Hi ${name}`;\nconsole.log(msg);', 'Hi Sam')], important_points: ['Template literals also support multi-line text without needing \\n.'], common_mistakes: [], real_world: '' }, { starter_code: 'let name = "Sam";\nlet msg = `Hi ${name}`;\nconsole.log(msg);' }, quickCheck({ text: 'What character starts/ends a template literal?', options: ['Single quote \'', 'Double quote "', 'Backtick `', 'Slash /'], correct_index: 2 })),
  lesson(6, 'Practice', 7, { explanation: 'Combine an array method with a template literal to build output.', syntax: '', examples: [ex('let fruits = ["apple", "banana"];\nfruits.forEach(f => console.log(f));', 'apple\nbanana')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'let nums = [1, 2, 3, 4];\n// print the sum of nums\n' }, quickCheck({ type: 'code', text: 'Given let nums = [1,2,3,4], print their sum.', starter_code: 'let nums = [1, 2, 3, 4];\nconsole.log(nums.reduce((a, b) => a + b, 0));', test_cases: [{ input: '', expected_output: '10' }] }))
];

const M4 = [
  lesson(1, 'Function Basics', 6, { explanation: 'A function is a reusable named block of code, defined with the "function" keyword.', syntax: 'function add(a, b) { return a + b; }', examples: [ex('function add(a, b) {\n    return a + b;\n}\nconsole.log(add(2, 3));', '5')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'function add(a, b) {\n    return a + b;\n}\nconsole.log(add(2, 3));' }, quickCheck({ text: 'What keyword starts a traditional function declaration?', options: ['func', 'def', 'function', 'method'], correct_index: 2 })),
  lesson(2, 'Arrow Functions', 6, { explanation: 'Arrow functions are a shorter syntax for writing functions, especially useful for one-liners.', syntax: 'const add = (a, b) => a + b;', examples: [ex('const add = (a, b) => a + b;\nconsole.log(add(2, 3));', '5')], important_points: ['A single-expression arrow function returns its value automatically, without a "return" keyword.'], common_mistakes: [], real_world: '' }, { starter_code: 'const add = (a, b) => a + b;\nconsole.log(add(2, 3));' }, quickCheck({ text: 'Does "(a, b) => a + b" need an explicit "return"?', options: ['Yes, always', 'No — single-expression arrows return implicitly', 'Only for numbers', 'It is a syntax error'], correct_index: 1 })),
  lesson(3, 'Default Parameters', 6, { explanation: 'A parameter can have a default value used automatically when the caller doesn\'t supply one.', syntax: 'function greet(name = "friend") { ... }', examples: [ex('function greet(name = "friend") {\n    console.log(`Hi ${name}`);\n}\ngreet();', 'Hi friend')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'function greet(name = "friend") {\n    console.log(`Hi ${name}`);\n}\ngreet();' }, quickCheck({ text: 'What happens if greet() is called with no argument and a default is set?', options: ['A crash', 'The default value is used', 'It uses undefined always', 'A syntax error'], correct_index: 1 })),
  lesson(4, 'Rest/Spread', 7, { explanation: 'Rest (...args) gathers extra arguments into an array; spread (...arr) expands an array into individual values.', syntax: 'function sum(...nums) { ... }\nconsole.log(...[1,2,3]);', examples: [ex('function sum(...nums) {\n    return nums.reduce((a, b) => a + b, 0);\n}\nconsole.log(sum(1, 2, 3));', '6')], important_points: ['The same "..." syntax means "gather" in a parameter list and "spread out" in a call/array — context decides which.'], common_mistakes: [], real_world: '' }, { starter_code: 'function sum(...nums) {\n    return nums.reduce((a, b) => a + b, 0);\n}\nconsole.log(sum(1, 2, 3));' }, quickCheck({ text: 'In "function sum(...nums)", what does ...nums do?', options: ['Gathers all arguments into an array', 'Spreads nums into separate values', 'Declares a global variable', 'Is invalid syntax'], correct_index: 0 })),
  lesson(5, 'Callbacks', 6, { explanation: 'A callback is a function passed into another function to be called later — common in JS for async or array operations.', syntax: 'arr.forEach(function(item) { ... });', examples: [ex('[1, 2, 3].forEach(n => console.log(n * 2));', '2\n4\n6')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: '[1, 2, 3].forEach(n => console.log(n * 2));' }, quickCheck({ text: 'What is a callback in JavaScript?', options: ['A function passed to another function to run later', 'A type of variable', 'A CSS property', 'A loop keyword'], correct_index: 0 })),
  lesson(6, 'Recursion', 6, { explanation: 'A recursive function calls itself with a smaller input, until a base case stops it.', syntax: 'function fact(n) { if (n <= 1) return 1; return n * fact(n - 1); }', examples: [ex('function fact(n) {\n    if (n <= 1) return 1;\n    return n * fact(n - 1);\n}\nconsole.log(fact(4));', '24')], important_points: ['Every recursive function needs a base case, or it will call itself forever.'], common_mistakes: [], real_world: '' }, { starter_code: 'function fact(n) {\n    if (n <= 1) return 1;\n    return n * fact(n - 1);\n}\nconsole.log(fact(5));' }, quickCheck({ text: 'What stops a recursive function from running forever?', options: ['Nothing, it always stops', 'The base case', 'The browser', 'A timeout'], correct_index: 1 }))
];

const M5 = [
  lesson(1, 'Object Basics', 6, { explanation: 'An object stores key-value pairs, similar to a dictionary/map in other languages.', syntax: 'let person = { name: "Sam", age: 20 };', examples: [ex('let person = { name: "Sam", age: 20 };\nconsole.log(person.name);', 'Sam')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'let person = { name: "Sam", age: 20 };\nconsole.log(person.name);' }, quickCheck({ text: 'How do you access the "name" key of person = {name: "Sam"}?', options: ['person[0]', 'person.name', 'person->name', 'person::name'], correct_index: 1 })),
  lesson(2, 'Object Methods', 6, { explanation: 'A function stored as a value inside an object is called a method.', syntax: 'let person = { greet() { console.log("hi"); } };', examples: [ex('let person = {\n    name: "Sam",\n    greet() { console.log("Hi " + this.name); }\n};\nperson.greet();', 'Hi Sam')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'let person = {\n    name: "Sam",\n    greet() { console.log("Hi " + this.name); }\n};\nperson.greet();' }, quickCheck({ text: 'What is a method in an object?', options: ['A key with a numeric value', 'A function stored as a value in the object', 'The object\'s prototype', 'A comment'], correct_index: 1 })),
  lesson(3, 'this Keyword', 6, { explanation: '"this" inside a method refers to the object the method was called on.', syntax: 'this.name', examples: [ex('let dog = {\n    name: "Rex",\n    bark() { console.log(this.name + " barks"); }\n};\ndog.bark();', 'Rex barks')], important_points: ['Arrow functions do not have their own "this" — they use the "this" from where they were defined.'], common_mistakes: [], real_world: '' }, { starter_code: 'let dog = {\n    name: "Rex",\n    bark() { console.log(this.name + " barks"); }\n};\ndog.bark();' }, quickCheck({ text: 'Inside dog.bark(), what does "this" refer to?', options: ['The global object', 'The dog object', 'undefined always', 'The bark function itself'], correct_index: 1 })),
  lesson(4, 'Object Destructuring', 6, { explanation: 'Destructuring pulls values out of an object into separate variables in one line.', syntax: 'const { name, age } = person;', examples: [ex('let person = { name: "Sam", age: 20 };\nconst { name, age } = person;\nconsole.log(name, age);', 'Sam 20')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'let person = { name: "Sam", age: 20 };\nconst { name, age } = person;\nconsole.log(name, age);' }, quickCheck({ text: 'What does "const { name } = person;" do?', options: ['Deletes person.name', 'Creates a variable "name" from person.name', 'Renames the object', 'Is invalid syntax'], correct_index: 1 })),
  lesson(5, 'JSON', 6, { explanation: 'JSON.stringify converts an object to a text string; JSON.parse converts text back into an object.', syntax: 'JSON.stringify(obj); JSON.parse(str);', examples: [ex('let person = { name: "Sam" };\nlet str = JSON.stringify(person);\nconsole.log(str);', '{"name":"Sam"}')], important_points: ['JSON is the standard format for sending structured data over the web (e.g. fetch/API responses).'], common_mistakes: [], real_world: '' }, { starter_code: 'let person = { name: "Sam" };\nlet str = JSON.stringify(person);\nconsole.log(str);' }, quickCheck({ text: 'What does JSON.stringify(obj) produce?', options: ['A copy of the object', 'A text string representing the object', 'An array', 'undefined'], correct_index: 1 }))
];

const M6 = [
  lesson(1, 'DOM Introduction', 6, { explanation: 'The DOM (Document Object Model) is how JavaScript represents and interacts with an HTML page.', syntax: 'document.title', examples: [ex('console.log(typeof document);', 'object')], important_points: ['The DOM only exists in a browser environment, not in plain Node.js scripts.'], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'What does the DOM represent?', options: ['A database', 'The structure of an HTML page, accessible to JS', 'A CSS file', 'A JavaScript function'], correct_index: 1 })),
  lesson(2, 'Selecting Elements', 6, { explanation: 'document.querySelector and getElementById find elements on the page to work with.', syntax: 'document.querySelector("#title");', examples: [ex('', 'document.querySelector("#title") finds the element with id="title" on the page.')], important_points: [], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'What does document.getElementById("title") return?', options: ['A CSS string', 'The element with that id', 'A list of all elements', 'undefined always'], correct_index: 1 })),
  lesson(3, 'Events', 6, { explanation: 'Events let you run code in response to user actions like clicks, using addEventListener.', syntax: 'button.addEventListener("click", () => { ... });', examples: [ex('', 'button.addEventListener("click", () => console.log("clicked")) runs the callback whenever the button is clicked.')], important_points: [], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'What does addEventListener("click", fn) do?', options: ['Runs fn immediately', 'Runs fn whenever the element is clicked', 'Deletes the element', 'Changes the element\'s style'], correct_index: 1 })),
  lesson(4, 'Modifying Elements', 6, { explanation: 'You can change a page by setting properties like .textContent, .innerHTML, or .style on a selected element.', syntax: 'el.textContent = "New text";', examples: [ex('', 'el.textContent = "Hello" replaces the element\'s visible text.')], important_points: ['innerHTML parses its content as HTML; textContent treats it as plain text (safer against injection).'], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'What is a key difference between .textContent and .innerHTML?', options: ['No difference', 'innerHTML parses HTML tags, textContent treats input as plain text', 'textContent is faster only', 'innerHTML cannot be changed'], correct_index: 1 }))
];

const M7 = [
  lesson(1, 'let/const', 6, { explanation: 'let declares a variable that can be reassigned; const declares one that cannot be reassigned after its initial value.', syntax: 'let x = 5;\nconst y = 10;', examples: [ex('let x = 5;\nx = 6;\nconsole.log(x);', '6')], important_points: ['const prevents reassignment, not mutation — a const array/object\'s contents can still change.'], common_mistakes: [], real_world: '' }, { starter_code: 'let x = 5;\nx = 6;\nconsole.log(x);' }, quickCheck({ text: 'Can a const variable be reassigned after declaration?', options: ['Yes, anytime', 'No', 'Only once', 'Only if it is a number'], correct_index: 1 })),
  lesson(2, 'Arrow Functions Recap', 6, { explanation: 'A quick recap: arrow functions are shorter and don\'t bind their own "this".', syntax: 'const square = x => x * x;', examples: [ex('const square = x => x * x;\nconsole.log(square(5));', '25')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'const square = x => x * x;\nconsole.log(square(5));' }, quickCheck({ text: 'What is a defining trait of arrow functions vs regular functions?', options: ['They cannot take arguments', 'They don\'t have their own "this"', 'They are always async', 'They cannot return values'], correct_index: 1 })),
  lesson(3, 'Classes', 6, { explanation: 'ES6 classes are syntax sugar over JavaScript\'s prototype-based objects, providing a familiar class-based structure.', syntax: 'class Dog {\n    constructor(name) { this.name = name; }\n}', examples: [ex('class Dog {\n    constructor(name) { this.name = name; }\n    bark() { console.log(this.name + " barks"); }\n}\nconst d = new Dog("Rex");\nd.bark();', 'Rex barks')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'class Dog {\n    constructor(name) { this.name = name; }\n    bark() { console.log(this.name + " barks"); }\n}\nconst d = new Dog("Rex");\nd.bark();' }, quickCheck({ text: 'What does the "constructor" method in a class do?', options: ['Runs on every method call', 'Runs once, when a new object is created', 'Deletes the object', 'Nothing automatically'], correct_index: 1 })),
  lesson(4, 'Modules', 6, { explanation: 'ES6 modules let you split code across files with export and import.', syntax: 'export function add(a, b) { return a + b; }\nimport { add } from "./math.js";', examples: [ex('', 'export lets a file share code; import lets another file use it.')], important_points: [], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'What does "export" let you do in a module?', options: ['Delete a function', 'Share code so another file can import it', 'Run code faster', 'Minify the file'], correct_index: 1 })),
  lesson(5, 'Optional Chaining', 6, { explanation: 'Optional chaining (?.) safely accesses a nested property, returning undefined instead of crashing if something in the chain is missing.', syntax: 'user?.address?.city', examples: [ex('let user = {};\nconsole.log(user?.address?.city);', 'undefined')], important_points: ['Without ?., accessing user.address.city when address is missing would throw an error instead of returning undefined.'], common_mistakes: [], real_world: '' }, { starter_code: 'let user = {};\nconsole.log(user?.address?.city);' }, quickCheck({ text: 'What does user?.address?.city return if user.address doesn\'t exist?', options: ['A crash', 'undefined', '0', '"null"'], correct_index: 1 }))
];

const M8 = [
  lesson(1, 'Callbacks', 6, { explanation: 'Async callbacks are functions passed to run once an asynchronous operation (like a timer) finishes.', syntax: 'setTimeout(() => { console.log("done"); }, 1000);', examples: [ex('setTimeout(() => console.log("done"), 0);', 'done')], important_points: ['Deeply nested callbacks are hard to read — this is exactly what Promises were designed to fix.'], common_mistakes: [], real_world: '' }, { starter_code: 'setTimeout(() => console.log("done"), 0);' }, quickCheck({ text: 'What problem do Promises mainly solve compared to nested callbacks?', options: ['They make code slower', 'They avoid deeply nested, hard-to-read callback chains', 'They remove the need for functions', 'They are unrelated to callbacks'], correct_index: 1 })),
  lesson(2, 'Promises', 7, { explanation: 'A Promise represents a value that will be available later — resolved (success) or rejected (failure).', syntax: 'new Promise((resolve, reject) => { resolve(5); });', examples: [ex('const p = new Promise((resolve) => resolve(5));\np.then(val => console.log(val));', '5')], important_points: ['.then() runs when the promise resolves; .catch() runs when it rejects.'], common_mistakes: [], real_world: '' }, { starter_code: 'const p = new Promise((resolve) => resolve(5));\np.then(val => console.log(val));' }, quickCheck({ text: 'Which method runs when a Promise successfully resolves?', options: ['.catch()', '.then()', '.finally() only', '.resolve()'], correct_index: 1 })),
  lesson(3, 'async/await', 7, { explanation: 'async/await is a cleaner syntax for working with Promises, letting async code read like regular sequential code.', syntax: 'async function run() { const val = await somePromise; }', examples: [ex('async function run() {\n    const val = await Promise.resolve(5);\n    console.log(val);\n}\nrun();', '5')], important_points: ['"await" can only be used inside an "async" function.'], common_mistakes: [], real_world: '' }, { starter_code: 'async function run() {\n    const val = await Promise.resolve(5);\n    console.log(val);\n}\nrun();' }, quickCheck({ text: 'Where can the "await" keyword be used?', options: ['Anywhere in a script', 'Only inside an async function', 'Only inside a class', 'Only at the top of a file'], correct_index: 1 })),
  lesson(4, 'fetch()', 7, { explanation: 'fetch() sends an HTTP request and returns a Promise for the response — the standard way to call web APIs from JS.', syntax: 'fetch(url).then(res => res.json());', examples: [ex('', 'fetch("https://api.example.com/data").then(res => res.json()).then(data => console.log(data));')], important_points: ['res.json() itself returns a Promise too — the actual parsed data arrives in the next .then().'], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'What does fetch() return?', options: ['The response data directly', 'A Promise for the response', 'undefined', 'A callback function'], correct_index: 1 }))
];

const M9 = [
  lesson(1, 'try-catch', 6, { explanation: 'try-catch lets your program handle a runtime error instead of crashing.', syntax: 'try { ... } catch (e) { ... }', examples: [ex('try {\n    JSON.parse("not json");\n} catch (e) {\n    console.log("Invalid JSON");\n}', 'Invalid JSON')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'try {\n    JSON.parse("not json");\n} catch (e) {\n    console.log("Invalid JSON");\n}' }, quickCheck({ text: 'When does code in a catch block run?', options: ['Always, before try', 'Only if the try block throws an error', 'Never automatically', 'Only on page load'], correct_index: 1 })),
  lesson(2, 'throw', 6, { explanation: '"throw" raises an error on purpose, when something invalid happens.', syntax: 'throw new Error("bad input");', examples: [ex('function check(age) {\n    if (age < 0) throw new Error("negative age");\n    console.log("OK:", age);\n}\ncheck(20);', 'OK: 20')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'function check(age) {\n    if (age < 0) throw new Error("negative age");\n    console.log("OK:", age);\n}\ncheck(20);' }, quickCheck({ text: 'What does "throw new Error(...)" do?', options: ['Logs a warning only', 'Raises an error that can be caught', 'Ends the program silently', 'Restarts the script'], correct_index: 1 })),
  lesson(3, 'Custom Errors', 6, { explanation: 'You can create your own error type by extending the built-in Error class.', syntax: 'class ValidationError extends Error { }', examples: [ex('class ValidationError extends Error {}\ntry {\n    throw new ValidationError("bad input");\n} catch (e) {\n    console.log(e.message);\n}', 'bad input')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'class ValidationError extends Error {}\ntry {\n    throw new ValidationError("bad input");\n} catch (e) {\n    console.log(e.message);\n}' }, quickCheck({ text: 'How do you create a custom error type in JS?', options: ['class X extends Error', 'You cannot in JavaScript', 'new CustomError()', 'Error.create()'], correct_index: 0 }))
];

const M10 = [
  lesson(1, 'Classes', 6, { explanation: 'A class is a template for creating objects with shared structure and behavior.', syntax: 'class Dog { constructor(name) { this.name = name; } }', examples: [ex('class Dog {\n    constructor(name) { this.name = name; }\n}\nconst d = new Dog("Rex");\nconsole.log(d.name);', 'Rex')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'class Dog {\n    constructor(name) { this.name = name; }\n}\nconst d = new Dog("Rex");\nconsole.log(d.name);' }, quickCheck({ text: 'How do you create an instance of class Dog?', options: ['Dog()', 'new Dog()', 'Dog.new()', 'create Dog()'], correct_index: 1 })),
  lesson(2, 'Constructors', 6, { explanation: 'The constructor method runs automatically when "new" creates an object, setting up its initial fields.', syntax: 'constructor(name) { this.name = name; }', examples: [ex('class Dog {\n    constructor(name) { this.name = name; }\n}\nconsole.log(new Dog("Fido").name);', 'Fido')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'class Dog {\n    constructor(name) { this.name = name; }\n}\nconsole.log(new Dog("Fido").name);' }, quickCheck({ text: 'When does the constructor method run?', options: ['Every method call', 'Once, when "new" creates the object', 'Never automatically', 'On program exit'], correct_index: 1 })),
  lesson(3, 'Inheritance', 7, { explanation: 'A class can inherit from another using "extends", reusing and extending its behavior.', syntax: 'class Dog extends Animal { }', examples: [ex('class Animal {\n    eat() { console.log("eating"); }\n}\nclass Dog extends Animal {}\nnew Dog().eat();', 'eating')], important_points: ['"super(...)" inside a subclass constructor calls the parent class\'s constructor.'], common_mistakes: [], real_world: '' }, { starter_code: 'class Animal {\n    eat() { console.log("eating"); }\n}\nclass Dog extends Animal {}\nnew Dog().eat();' }, quickCheck({ text: 'Which keyword makes one class inherit another?', options: ['implements', 'extends', 'inherits', 'super'], correct_index: 1 })),
  lesson(4, 'Encapsulation', 6, { explanation: 'JavaScript classes support private fields using a # prefix, hiding them from outside access.', syntax: 'class Account {\n    #balance = 0;\n}', examples: [ex('class Account {\n    #balance = 0;\n    deposit(amt) { this.#balance += amt; }\n    getBalance() { return this.#balance; }\n}\nconst a = new Account();\na.deposit(100);\nconsole.log(a.getBalance());', '100')], important_points: ['A #field cannot be accessed at all from outside the class, unlike a normal field.'], common_mistakes: [], real_world: '' }, { starter_code: 'class Account {\n    #balance = 0;\n    deposit(amt) { this.#balance += amt; }\n    getBalance() { return this.#balance; }\n}\nconst a = new Account();\na.deposit(100);\nconsole.log(a.getBalance());' }, quickCheck({ text: 'What does the # prefix on a class field do?', options: ['Makes it a constant', 'Makes it private, inaccessible from outside the class', 'Makes it static', 'Nothing special'], correct_index: 1 }))
];

const M11 = [
  lesson(1, 'Closures', 7, { explanation: 'A closure is a function that "remembers" the variables from where it was created, even after that outer function has finished running.', syntax: 'function makeCounter() {\n    let count = 0;\n    return () => ++count;\n}', examples: [ex('function makeCounter() {\n    let count = 0;\n    return () => ++count;\n}\nconst counter = makeCounter();\nconsole.log(counter());\nconsole.log(counter());', '1\n2')], important_points: ['Each call to makeCounter() creates a brand-new, independent "count" variable for that closure.'], common_mistakes: [], real_world: '' }, { starter_code: 'function makeCounter() {\n    let count = 0;\n    return () => ++count;\n}\nconst counter = makeCounter();\nconsole.log(counter());\nconsole.log(counter());' }, quickCheck({ text: 'What does a closure "remember"?', options: ['Nothing after the outer function ends', 'The variables from its creation scope', 'Only global variables', 'Only its own parameters'], correct_index: 1 })),
  lesson(2, 'Higher-Order Functions', 6, { explanation: 'A higher-order function takes a function as an argument or returns one — map, filter, and reduce are common examples.', syntax: 'arr.filter(x => x > 2);', examples: [ex('let nums = [1, 2, 3, 4];\nlet big = nums.filter(x => x > 2);\nconsole.log(big);', '[ 3, 4 ]')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'let nums = [1, 2, 3, 4];\nlet big = nums.filter(x => x > 2);\nconsole.log(big);' }, quickCheck({ text: 'What makes a function "higher-order"?', options: ['It runs faster', 'It takes or returns another function', 'It is declared with "function" not "=>"', 'It has no parameters'], correct_index: 1 })),
  lesson(3, 'Prototype Chain', 7, { explanation: 'Every JS object has an internal link to another object (its prototype) — property lookups walk up this chain if not found directly.', syntax: 'obj.__proto__', examples: [ex('let animal = { eats: true };\nlet dog = Object.create(animal);\nconsole.log(dog.eats);', 'true')], important_points: ['This prototype chain is what "class" and "extends" are built on top of under the hood.'], common_mistakes: [], real_world: '' }, { starter_code: 'let animal = { eats: true };\nlet dog = Object.create(animal);\nconsole.log(dog.eats);' }, quickCheck({ text: 'What happens when a property isn\'t found directly on an object?', options: ['undefined is returned immediately, always', 'JS looks up the prototype chain', 'An error is always thrown', 'The object is deleted'], correct_index: 1 })),
  lesson(4, 'Iterators/Generators', 7, { explanation: 'A generator function (function*) can pause and resume, yielding a sequence of values one at a time.', syntax: 'function* gen() { yield 1; yield 2; }', examples: [ex('function* gen() {\n    yield 1;\n    yield 2;\n}\nfor (const val of gen()) {\n    console.log(val);\n}', '1\n2')], important_points: ['"yield" pauses the generator, returning a value, until the next value is requested.'], common_mistakes: [], real_world: '' }, { starter_code: 'function* gen() {\n    yield 1;\n    yield 2;\n}\nfor (const val of gen()) {\n    console.log(val);\n}' }, quickCheck({ text: 'What does the "yield" keyword do inside a generator?', options: ['Ends the function immediately', 'Pauses and returns a value, resuming later', 'Throws an error', 'Declares a variable'], correct_index: 1 }))
];

const M12 = [
  lesson(1, 'HTTP Basics', 6, { explanation: 'HTTP is the protocol browsers and servers use to communicate — requests have a method (GET, POST) and get back a response.', syntax: '', examples: [ex('', 'A GET request asks for data; a POST request typically sends data to be created/processed.')], important_points: [], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'Which HTTP method is typically used to fetch data?', options: ['GET', 'DELETE', 'PUT', 'PATCH only'], correct_index: 0 })),
  lesson(2, 'fetch API', 7, { explanation: 'fetch() is the built-in way to make HTTP requests from JavaScript, returning a Promise.', syntax: 'fetch(url).then(res => res.json()).then(data => ...);', examples: [ex('', 'fetch("/api/users").then(res => res.json()).then(users => console.log(users));')], important_points: [], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'What type of value does fetch() return?', options: ['The raw data immediately', 'A Promise', 'A string', 'undefined'], correct_index: 1 })),
  lesson(3, 'JSON Handling', 6, { explanation: 'Most APIs send/receive JSON — res.json() parses a fetch response body into a usable JS object.', syntax: 'res.json()', examples: [ex('let data = JSON.parse(\'{"name":"Sam"}\');\nconsole.log(data.name);', 'Sam')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'let data = JSON.parse(\'{"name":"Sam"}\');\nconsole.log(data.name);' }, quickCheck({ text: 'What does res.json() do to a fetch response?', options: ['Sends a new request', 'Parses the response body into a JS object', 'Deletes the response', 'Converts it to a string only'], correct_index: 1 })),
  lesson(4, 'API Project', 8, { explanation: 'Combine fetch + async/await + JSON handling into one small workflow.', syntax: '', examples: [ex('async function getUser() {\n    // Conceptual: const res = await fetch(url); const data = await res.json();\n    const data = { name: "Sam" };\n    console.log(data.name);\n}\ngetUser();', 'Sam')], important_points: ['Wrap fetch calls in try/catch since network requests can fail.'], common_mistakes: [], real_world: '' }, { starter_code: 'async function getUser() {\n    const data = { name: "Ana" };\n    console.log(data.name);\n}\ngetUser();' }, quickCheck({ text: 'Why wrap a fetch() call in try/catch?', options: ['It is required syntax', 'Network requests can fail', 'It makes fetch faster', 'It is not necessary ever'], correct_index: 1 }))
];

const M13 = [
  lesson(1, 'Stacks', 6, { explanation: 'A stack (LIFO) can be built with a plain array using push/pop on the end.', syntax: 'stack.push(1); stack.pop();', examples: [ex('let stack = [];\nstack.push(1);\nstack.push(2);\nconsole.log(stack.pop());', '2')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'let stack = [];\nstack.push(1);\nstack.push(2);\nconsole.log(stack.pop());' }, quickCheck({ text: 'What does stack.pop() return?', options: ['The first element ever pushed', 'The most recently pushed element', 'A random element', 'undefined always'], correct_index: 1 })),
  lesson(2, 'Queues', 6, { explanation: 'A queue (FIFO) can be built with an array using push (add to end) and shift (remove from front).', syntax: 'q.push(1); q.shift();', examples: [ex('let q = [];\nq.push(1);\nq.push(2);\nconsole.log(q.shift());', '1')], important_points: ['shift() is O(n) on a JS array since every remaining element must move — fine for learning, not huge datasets.'], common_mistakes: [], real_world: '' }, { starter_code: 'let q = [];\nq.push(1);\nq.push(2);\nconsole.log(q.shift());' }, quickCheck({ text: 'What does q.shift() do?', options: ['Removes and returns the last element', 'Removes and returns the first element', 'Adds an element', 'Sorts the array'], correct_index: 1 })),
  lesson(3, 'Linked Lists', 7, { explanation: 'A linked list node is an object with a value and a reference to the next node.', syntax: 'let node = { val: 10, next: null };', examples: [ex('let node = { val: 10, next: null };\nconsole.log(node.val);', '10')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'let node = { val: 10, next: null };\nconsole.log(node.val);' }, quickCheck({ text: 'What marks the end of a singly linked list?', options: ['A node with value 0', 'A "next" reference that is null', 'The first node', 'An empty array'], correct_index: 1 })),
  lesson(4, 'Searching', 6, { explanation: 'Array.prototype.indexOf (or includes) performs a linear search over an array.', syntax: 'arr.indexOf(target);', examples: [ex('let arr = [1, 3, 5, 7];\nconsole.log(arr.indexOf(5));', '2')], important_points: ['indexOf returns -1 when the value is not found.'], common_mistakes: [], real_world: '' }, { starter_code: 'let arr = [1, 3, 5, 7];\nconsole.log(arr.indexOf(5));' }, quickCheck({ text: 'What does arr.indexOf(x) return if x is not found?', options: ['0', '-1', 'undefined', 'It throws'], correct_index: 1 })),
  lesson(5, 'Sorting', 6, { explanation: 'Array.prototype.sort() sorts an array in place — by default it sorts by string comparison, so numbers need a compare function.', syntax: 'arr.sort((a, b) => a - b);', examples: [ex('let arr = [5, 2, 8, 1];\narr.sort((a, b) => a - b);\nconsole.log(arr[0]);', '1')], important_points: ['Without a compare function, sort() treats numbers as strings — [10, 2].sort() gives [10, 2], not [2, 10]!'], common_mistakes: [], real_world: '' }, { starter_code: 'let arr = [5, 2, 8, 1];\narr.sort((a, b) => a - b);\nconsole.log(arr[0]);' }, quickCheck({ text: 'Why pass (a, b) => a - b to sort() for numbers?', options: ['It is optional decoration', 'Without it, sort() compares numbers as strings', 'It makes sort() run in reverse', 'It is required for arrays under 2 elements'], correct_index: 1 }))
];

const M14 = [
  lesson(1, 'Trees Basics', 7, { explanation: 'A binary tree node is an object with a value and left/right child references.', syntax: 'let node = { val: 10, left: null, right: null };', examples: [ex('let node = { val: 10, left: null, right: null };\nconsole.log(node.val);', '10')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'let node = { val: 10, left: null, right: null };\nconsole.log(node.val);' }, quickCheck({ text: 'How many children can a binary tree node have at most?', options: ['1', '2', '3', 'Unlimited'], correct_index: 1 })),
  lesson(2, 'Graphs Basics', 7, { explanation: 'A graph can be represented as a plain object mapping each node to an array of its neighbors.', syntax: 'let graph = { 1: [2, 3] };', examples: [ex('let graph = { 1: [2, 3] };\nconsole.log(graph[1][0]);', '2')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'let graph = { 1: [2, 3] };\nconsole.log(graph[1][0]);' }, quickCheck({ text: 'What is a common way to represent a graph in JS?', options: ['A single number', 'An object mapping each node to its neighbors', 'A string', 'It cannot be represented'], correct_index: 1 })),
  lesson(3, 'Problem Solving', 8, { explanation: 'Apply an array + loop to solve a small problem: count how many times a value appears.', syntax: '', examples: [ex('let arr = [1, 2, 2, 3, 1, 1];\nlet count = arr.filter(n => n === 1).length;\nconsole.log(count);', '3')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'let arr = [4, 4, 5, 6, 4];\n// print how many times 4 appears\n' }, quickCheck({ type: 'code', text: 'Given let arr = [4,4,5,6,4], print how many times 4 appears.', starter_code: 'let arr = [4, 4, 5, 6, 4];\nconsole.log(arr.filter(n => n === 4).length);', test_cases: [{ input: '', expected_output: '3' }] }))
];

const M15 = [
  lesson(1, 'Calculator', 8, { explanation: 'Build a simple calculator: a function that branches on an operator string.', syntax: '', examples: [ex('function calc(a, b, op) {\n    if (op === "+") return a + b;\n    return 0;\n}\nconsole.log(calc(4, 3, "+"));', '7')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'function calc(a, b, op) {\n    if (op === "+") return a + b;\n    if (op === "-") return a - b;\n    return 0;\n}\nconsole.log(calc(10, 4, "-"));' }, quickCheck({ type: 'code', text: 'Extend calc to support "*" and print calc(6, 7, "*").', starter_code: 'function calc(a, b, op) {\n    if (op === "+") return a + b;\n    if (op === "-") return a - b;\n    if (op === "*") return a * b;\n    return 0;\n}\nconsole.log(calc(6, 7, "*"));', test_cases: [{ input: '', expected_output: '42' }] })),
  lesson(2, 'To-Do App', 9, { explanation: 'Model a to-do list as an array of task objects with a "done" flag.', syntax: '', examples: [ex('let todos = [];\ntodos.push({ text: "Learn JS", done: false });\nconsole.log(todos[0].text);', 'Learn JS')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'let todos = [];\ntodos.push({ text: "Learn JS", done: false });\ntodos.push({ text: "Build project", done: false });\n// mark the first todo as done and print it\n' }, quickCheck({ text: 'What is a simple way to represent a to-do item?', options: ['A single string only', 'An object with text and a done flag', 'A number', 'It cannot be modeled'], correct_index: 1 })),
  lesson(3, 'Quiz Application', 9, { explanation: 'Model a quiz as an array of question objects, and check the user\'s answer against the correct one.', syntax: '', examples: [ex('let questions = [{ q: "2+2?", answer: 4 }];\nlet userAnswer = 4;\nconsole.log(userAnswer === questions[0].answer);', 'true')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'let questions = [{ q: "2+2?", answer: 4 }];\nlet userAnswer = 4;\nconsole.log(userAnswer === questions[0].answer);' }, quickCheck({ text: 'How do you check if a user\'s answer is correct?', options: ['Compare it to the stored correct answer', 'Always assume it is correct', 'Random chance', 'You cannot check in JS'], correct_index: 0 })),
  lesson(4, 'Final JavaScript Project', 10, { explanation: 'Bring it together: an array of objects and a loop/filter to search for one by name.', syntax: '', examples: [ex('let items = [{ name: "Pen" }, { name: "Book" }, { name: "Bag" }];\nlet found = items.find(i => i.name === "Bag");\nconsole.log("Found:", found.name);', 'Found: Bag')], important_points: ['This pattern — array of objects + find/filter — is the backbone of most small JS apps.'], common_mistakes: [], real_world: '' }, { starter_code: 'let items = [{ name: "Pen" }, { name: "Book" }, { name: "Bag" }];\n// find "Bag" and print "Found: Bag"\n' }, quickCheck({ type: 'code', text: 'Given items [{name:"Pen"},{name:"Book"},{name:"Bag"}], print "Found: Bag".', starter_code: 'let items = [{ name: "Pen" }, { name: "Book" }, { name: "Bag" }];\nlet found = items.find(i => i.name === "Bag");\nconsole.log("Found: " + found.name);', test_cases: [{ input: '', expected_output: 'Found: Bag' }] }))
];

module.exports = { M3, M4, M5, M6, M7, M8, M9, M10, M11, M12, M13, M14, M15 };
