/**
 * Python Full Course — Modules 9-15, authored content (lighter-detail pass).
 * Merged into Backend/pythonCourseData.js's HAND_AUTHORED map by `order`.
 */
let AUTO_ID = 95000;
function qid() { AUTO_ID += 1; return `pyq${AUTO_ID}`; }
function lesson(order, title, estMinutes, learn, practice, test) {
  return { order, title, est_minutes: estMinutes, content_ready: true, learn, practice, test };
}
function quickCheck(q) {
  if (q.type === 'code') return { questions: [{ id: qid(), type: 'code', text: q.text, language: 'python', starter_code: q.starter_code, test_cases: q.test_cases }] };
  return { questions: [{ id: qid(), type: 'mcq', text: q.text, options: q.options, correct_index: q.correct_index }] };
}
function ex(code, output) { return { code, output }; }

const M9 = [
  lesson(1, 'Errors vs Exceptions', 5, { explanation: 'A syntax error means your code isn\'t valid Python; an exception is a runtime error that occurs while otherwise-valid code is executing.', syntax: '', examples: [ex('print(10 / 0)', 'ZeroDivisionError: division by zero')], important_points: [], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'When does an exception occur, as opposed to a syntax error?', options: ['Before the program even starts', 'While otherwise-valid code is running', 'Never in Python', 'Only in loops'], correct_index: 1 })),
  lesson(2, 'try', 5, { explanation: 'A try block wraps code that might raise an exception, so it can be handled instead of crashing the program.', syntax: 'try:\n    ...', examples: [ex('try:\n    print(10 / 0)\nexcept ZeroDivisionError:\n    print("Cannot divide by zero")', 'Cannot divide by zero')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'try:\n    print(10 / 0)\nexcept ZeroDivisionError:\n    print("Cannot divide by zero")' }, quickCheck({ text: 'What goes inside a try block?', options: ['Code that always fails', 'Code that might raise an exception', 'Only print statements', 'Class definitions only'], correct_index: 1 })),
  lesson(3, 'except', 5, { explanation: 'except catches a specific exception type and runs recovery code instead of letting the program crash.', syntax: 'except ValueError:\n    ...', examples: [ex('try:\n    int("abc")\nexcept ValueError:\n    print("Not a number")', 'Not a number')], important_points: ['You can have multiple except blocks to handle different exception types differently.'], common_mistakes: [], real_world: '' }, { starter_code: 'try:\n    int("abc")\nexcept ValueError:\n    print("Not a number")' }, quickCheck({ text: 'What does an except block do?', options: ['Runs before try, always', 'Handles a specific exception type from the try block', 'Prevents any errors', 'Is required to be empty'], correct_index: 1 })),
  lesson(4, 'else', 5, { explanation: 'An else block after try/except runs only if the try block succeeded with no exception.', syntax: 'try:\n    ...\nexcept:\n    ...\nelse:\n    ...', examples: [ex('try:\n    x = 10\nexcept:\n    print("error")\nelse:\n    print("success:", x)', 'success: 10')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'try:\n    x = 10\nexcept:\n    print("error")\nelse:\n    print("success:", x)' }, quickCheck({ text: 'When does the else block after try/except run?', options: ['Only if an exception occurred', 'Only if no exception occurred', 'Always', 'Never'], correct_index: 1 })),
  lesson(5, 'finally', 5, { explanation: 'A finally block always runs after try/except, whether or not an exception occurred — useful for cleanup.', syntax: 'finally:\n    ...', examples: [ex('try:\n    print("try")\nfinally:\n    print("finally")', 'try\nfinally')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'try:\n    print("try")\nfinally:\n    print("finally")' }, quickCheck({ text: 'When does the finally block run?', options: ['Only on success', 'Only on failure', 'Always, regardless of outcome', 'Never automatically'], correct_index: 2 })),
  lesson(6, 'raise', 5, { explanation: '"raise" lets you trigger an exception yourself, on purpose, when something invalid happens.', syntax: 'raise ValueError("bad input")', examples: [ex('def check(age):\n    if age < 0:\n        raise ValueError("negative age")\n    print("OK:", age)\ncheck(20)', 'OK: 20')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'def check(age):\n    if age < 0:\n        raise ValueError("negative age")\n    print("OK:", age)\ncheck(20)' }, quickCheck({ text: 'What does "raise" do?', options: ['Catches an exception', 'Triggers an exception', 'Suppresses errors', 'Ends the program silently'], correct_index: 1 })),
  lesson(7, 'Custom Exceptions', 6, { explanation: 'You can define your own exception type by inheriting from Exception.', syntax: 'class MyError(Exception):\n    pass', examples: [ex('class MyError(Exception):\n    pass\ntry:\n    raise MyError("custom")\nexcept MyError as e:\n    print(e)', 'custom')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'class MyError(Exception):\n    pass\ntry:\n    raise MyError("custom")\nexcept MyError as e:\n    print(e)' }, quickCheck({ text: 'How do you create a custom exception type in Python?', options: ['class X(Exception): pass', 'You cannot in Python', 'def exception X():', 'raise class X'], correct_index: 0 }))
];

const M10 = [
  lesson(1, 'Classes', 5, { explanation: 'A class is a blueprint for creating objects, defined with the "class" keyword.', syntax: 'class Dog:\n    pass', examples: [ex('class Dog:\n    pass\nd = Dog()\nprint(type(d))', "<class '__main__.Dog'>")], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'class Dog:\n    pass\nd = Dog()\nprint(type(d))' }, quickCheck({ text: 'What keyword defines a class in Python?', options: ['def', 'class', 'object', 'struct'], correct_index: 1 })),
  lesson(2, 'Objects', 5, { explanation: 'An object is a specific instance created from a class, using ClassName().', syntax: 'd = Dog()', examples: [ex('class Dog:\n    pass\nd1 = Dog()\nd2 = Dog()\nprint(d1 is d2)', 'False')], important_points: ['Each call to Dog() creates a completely separate, independent object.'], common_mistakes: [], real_world: '' }, { starter_code: 'class Dog:\n    pass\nd1 = Dog()\nd2 = Dog()\nprint(d1 is d2)' }, quickCheck({ text: 'Does calling Dog() twice create the same object or two different ones?', options: ['The same object', 'Two different objects', 'It raises an error', 'It depends on the class'], correct_index: 1 })),
  lesson(3, 'Constructor', 5, { explanation: '__init__ is a special method that runs automatically when a new object is created, setting up its initial state.', syntax: 'def __init__(self, name):\n    self.name = name', examples: [ex('class Dog:\n    def __init__(self, name):\n        self.name = name\nd = Dog("Rex")\nprint(d.name)', 'Rex')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'class Dog:\n    def __init__(self, name):\n        self.name = name\nd = Dog("Rex")\nprint(d.name)' }, quickCheck({ text: 'When does __init__ run?', options: ['Every time a method is called', 'Automatically when a new object is created', 'Never automatically', 'Only when named explicitly'], correct_index: 1 })),
  lesson(4, 'self', 6, { explanation: '"self" refers to the current object inside a method — it must be the first parameter of every instance method.', syntax: 'def bark(self):\n    print(self.name)', examples: [ex('class Dog:\n    def __init__(self, name):\n        self.name = name\n    def bark(self):\n        print(self.name, "barks")\nDog("Rex").bark()', 'Rex barks')], important_points: ['Python passes "self" automatically — you never pass it explicitly when calling d.bark().'], common_mistakes: [], real_world: '' }, { starter_code: 'class Dog:\n    def __init__(self, name):\n        self.name = name\n    def bark(self):\n        print(self.name, "barks")\nDog("Rex").bark()' }, quickCheck({ text: 'What does "self" refer to inside a method?', options: ['The class itself', 'The current object', 'A global variable', 'Nothing, it is optional'], correct_index: 1 })),
  lesson(5, 'Instance Variables', 5, { explanation: 'Instance variables are attributes stored on "self" — each object has its own separate copy.', syntax: 'self.name = name', examples: [ex('class Dog:\n    def __init__(self, name):\n        self.name = name\nd1 = Dog("Rex")\nd2 = Dog("Fido")\nprint(d1.name, d2.name)', 'Rex Fido')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'class Dog:\n    def __init__(self, name):\n        self.name = name\nd1 = Dog("Rex")\nd2 = Dog("Fido")\nprint(d1.name, d2.name)' }, quickCheck({ text: 'Do two Dog objects share the same self.name value?', options: ['Yes, always', 'No, each object has its own', 'Only the first object does', 'Only if declared static'], correct_index: 1 })),
  lesson(6, 'Methods', 5, { explanation: 'A method is a function defined inside a class, operating on the object via "self".', syntax: 'def bark(self):\n    print("Woof")', examples: [ex('class Dog:\n    def bark(self):\n        print("Woof")\nDog().bark()', 'Woof')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'class Dog:\n    def bark(self):\n        print("Woof")\nDog().bark()' }, quickCheck({ text: 'What is a method?', options: ['A global function', 'A function defined inside a class', 'A variable', 'A module'], correct_index: 1 })),
  lesson(7, 'Encapsulation', 6, { explanation: 'Encapsulation means restricting direct access to some fields, conventionally by prefixing them with an underscore, and exposing controlled access through methods.', syntax: 'self._balance = 0', examples: [ex('class Account:\n    def __init__(self):\n        self._balance = 0\n    def deposit(self, amt):\n        self._balance += amt\n    def get_balance(self):\n        return self._balance\na = Account()\na.deposit(100)\nprint(a.get_balance())', '100')], important_points: ['Python doesn\'t truly enforce privacy — a leading underscore is a convention signaling "internal use only".'], common_mistakes: [], real_world: '' }, { starter_code: 'class Account:\n    def __init__(self):\n        self._balance = 0\n    def deposit(self, amt):\n        self._balance += amt\n    def get_balance(self):\n        return self._balance\na = Account()\na.deposit(100)\nprint(a.get_balance())' }, quickCheck({ text: 'What does a leading underscore on an attribute conventionally signal in Python?', options: ['It is a constant', 'It is intended for internal use only', 'It is a global variable', 'It cannot hold a value'], correct_index: 1 })),
  lesson(8, 'Inheritance', 6, { explanation: 'A subclass inherits fields/methods from a parent class, written as class Dog(Animal):.', syntax: 'class Dog(Animal):\n    pass', examples: [ex('class Animal:\n    def eat(self):\n        print("eating")\nclass Dog(Animal):\n    pass\nDog().eat()', 'eating')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'class Animal:\n    def eat(self):\n        print("eating")\nclass Dog(Animal):\n    pass\nDog().eat()' }, quickCheck({ text: 'What does "class Dog(Animal):" mean?', options: ['Dog implements Animal', 'Dog inherits from Animal', 'Dog is unrelated to Animal', 'A syntax error'], correct_index: 1 })),
  lesson(9, 'Multiple Inheritance', 6, { explanation: 'Python allows a class to inherit from more than one parent class at once.', syntax: 'class C(A, B):\n    pass', examples: [ex('class A:\n    def a(self): print("a")\nclass B:\n    def b(self): print("b")\nclass C(A, B):\n    pass\nC().a()\nC().b()', 'a\nb')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'class A:\n    def a(self): print("a")\nclass B:\n    def b(self): print("b")\nclass C(A, B):\n    pass\nC().a()\nC().b()' }, quickCheck({ text: 'Can a Python class inherit from multiple parent classes?', options: ['No, never', 'Yes', 'Only up to 2 levels deep', 'Only with special imports'], correct_index: 1 })),
  lesson(10, 'Polymorphism', 6, { explanation: 'Polymorphism means different classes can implement the same method name in their own way, and calling code doesn\'t need to know which.', syntax: '', examples: [ex('class Cat:\n    def sound(self): print("Meow")\nclass Dog:\n    def sound(self): print("Woof")\nfor a in [Cat(), Dog()]:\n    a.sound()', 'Meow\nWoof')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'class Cat:\n    def sound(self): print("Meow")\nclass Dog:\n    def sound(self): print("Woof")\nfor a in [Cat(), Dog()]:\n    a.sound()' }, quickCheck({ text: 'What does polymorphism let different classes do?', options: ['Share the exact same code', 'Implement the same method name differently', 'Avoid using methods', 'Only exist as one instance'], correct_index: 1 })),
  lesson(11, 'Abstraction', 6, { explanation: 'Abstraction means exposing only what\'s necessary and hiding implementation details — often via abstract base classes.', syntax: 'from abc import ABC, abstractmethod', examples: [ex('from abc import ABC, abstractmethod\nclass Shape(ABC):\n    @abstractmethod\n    def area(self): pass\nclass Circle(Shape):\n    def area(self): return 3.14 * 4\nprint(Circle().area())', '12.56')], important_points: ['You cannot instantiate an ABC directly if it has unimplemented abstract methods.'], common_mistakes: [], real_world: '' }, { starter_code: 'from abc import ABC, abstractmethod\nclass Shape(ABC):\n    @abstractmethod\n    def area(self): pass\nclass Circle(Shape):\n    def area(self): return 3.14 * 4\nprint(Circle().area())' }, quickCheck({ text: 'What does @abstractmethod mark?', options: ['A method that must be implemented by subclasses', 'A method that runs first', 'A private method', 'A static method'], correct_index: 0 }))
];

const M11 = [
  lesson(1, 'Iterators', 6, { explanation: 'An iterator is an object you can step through one value at a time with next(), until it\'s exhausted.', syntax: 'it = iter([1, 2, 3])\nnext(it)', examples: [ex('it = iter([1, 2, 3])\nprint(next(it))\nprint(next(it))', '1\n2')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'it = iter([1, 2, 3])\nprint(next(it))\nprint(next(it))' }, quickCheck({ text: 'What does next(it) do to an iterator?', options: ['Restarts it', 'Returns the next value and advances', 'Deletes it', 'Reverses it'], correct_index: 1 })),
  lesson(2, 'Generators', 7, { explanation: 'A generator function uses "yield" to produce values one at a time, pausing between each — more memory-efficient than building a whole list.', syntax: 'def gen():\n    yield 1\n    yield 2', examples: [ex('def gen():\n    yield 1\n    yield 2\nfor val in gen():\n    print(val)', '1\n2')], important_points: ['"yield" pauses the function, remembering its state, until the next value is requested.'], common_mistakes: [], real_world: '' }, { starter_code: 'def gen():\n    yield 1\n    yield 2\nfor val in gen():\n    print(val)' }, quickCheck({ text: 'What does "yield" do inside a generator function?', options: ['Ends the function immediately', 'Produces a value and pauses, resuming later', 'Raises an error', 'Declares a variable'], correct_index: 1 })),
  lesson(3, 'Decorators', 7, { explanation: 'A decorator is a function that wraps another function to add behavior, without changing its code.', syntax: '@my_decorator\ndef func(): ...', examples: [ex('def shout(func):\n    def wrapper():\n        print(func().upper())\n    return wrapper\n\n@shout\ndef greet():\n    return "hi"\ngreet()', 'HI')], important_points: ['The @decorator syntax is shorthand for "greet = shout(greet)".'], common_mistakes: [], real_world: '' }, { starter_code: 'def shout(func):\n    def wrapper():\n        print(func().upper())\n    return wrapper\n\n@shout\ndef greet():\n    return "hi"\ngreet()' }, quickCheck({ text: 'What does a decorator do?', options: ['Deletes a function', 'Wraps a function to add behavior around it', 'Only formats strings', 'Renames a function'], correct_index: 1 })),
  lesson(4, 'Comprehensions', 6, { explanation: 'Besides list comprehensions, Python also has dict and set comprehensions using {} syntax.', syntax: '{x: x*x for x in range(3)}', examples: [ex('squares = {x: x * x for x in range(3)}\nprint(squares)', '{0: 0, 1: 1, 2: 4}')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'squares = {x: x * x for x in range(3)}\nprint(squares)' }, quickCheck({ text: 'What does {x: x*x for x in range(3)} create?', options: ['A list', 'A dictionary mapping x to x squared', 'A set', 'A syntax error'], correct_index: 1 })),
  lesson(5, 'Regular Expressions', 7, { explanation: 'The re module lets you search and match text patterns, using a special pattern syntax.', syntax: 'import re\nre.match(r"\\d+", "123")', examples: [ex('import re\nresult = re.match(r"\\d+", "123abc")\nprint(result.group())', '123')], important_points: ['\\d+ matches one or more digits — regex patterns use special symbols like this for flexible matching.'], common_mistakes: [], real_world: '' }, { starter_code: 'import re\nresult = re.match(r"\\d+", "123abc")\nprint(result.group())' }, quickCheck({ text: 'What does the regex pattern \\d+ match?', options: ['One or more letters', 'One or more digits', 'Exactly one character', 'Whitespace only'], correct_index: 1 })),
  lesson(6, 'Context Managers', 6, { explanation: 'A context manager (used with "with") automatically sets up and tears down a resource — files are the most common example.', syntax: 'with open("f.txt") as f:\n    ...', examples: [ex('with open("out.txt", "w") as f:\n    f.write("hi")\nprint("done")', 'done')], important_points: ['You can build your own context managers by defining __enter__ and __exit__ methods.'], common_mistakes: [], real_world: '' }, { starter_code: 'with open("out.txt", "w") as f:\n    f.write("hi")\nprint("done")' }, quickCheck({ text: 'What is a context manager mainly used for?', options: ['Speeding up loops', 'Automatically setting up and cleaning up a resource', 'Declaring classes', 'Formatting strings'], correct_index: 1 })),
  lesson(7, 'Advanced Functions', 6, { explanation: 'Functions in Python are first-class objects — you can pass them as arguments, return them from other functions, and store them in variables.', syntax: 'def apply(f, x):\n    return f(x)', examples: [ex('def apply(f, x):\n    return f(x)\nprint(apply(lambda x: x * 2, 5))', '10')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'def apply(f, x):\n    return f(x)\nprint(apply(lambda x: x * 2, 5))' }, quickCheck({ text: 'What does "functions are first-class objects" mean in Python?', options: ['Functions cannot take arguments', 'Functions can be passed around like any other value', 'Functions run faster than loops', 'Only lambda functions are first-class'], correct_index: 1 }))
];

const M12 = [
  lesson(1, 'Database Basics', 6, { explanation: 'A database stores structured data persistently — tables of rows and columns, queried with SQL.', syntax: '', examples: [ex('', '(conceptual — a "students" table might have columns id, name, marks)')], important_points: [], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'What does a relational database typically organize data into?', options: ['A single text file', 'Tables of rows and columns', 'A single list', 'Random key-value pairs only'], correct_index: 1 })),
  lesson(2, 'SQLite', 6, { explanation: 'SQLite is a lightweight, file-based database built into Python via the sqlite3 module — no separate server needed.', syntax: 'import sqlite3\nconn = sqlite3.connect("data.db")', examples: [ex('import sqlite3\nconn = sqlite3.connect(":memory:")\nprint("connected")', 'connected')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'import sqlite3\nconn = sqlite3.connect(":memory:")\nprint("connected")' }, quickCheck({ text: 'What makes SQLite different from most databases?', options: ['It requires a separate server', 'It is file-based, built into Python, no server needed', 'It cannot store text', 'It only works online'], correct_index: 1 })),
  lesson(3, 'Connecting Python with Database', 6, { explanation: 'sqlite3.connect() opens a connection; conn.cursor() gives you an object to run SQL commands with.', syntax: 'cur = conn.cursor()', examples: [ex('import sqlite3\nconn = sqlite3.connect(":memory:")\ncur = conn.cursor()\nprint(type(cur))', "<class 'sqlite3.Cursor'>")], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'import sqlite3\nconn = sqlite3.connect(":memory:")\ncur = conn.cursor()\nprint(type(cur))' }, quickCheck({ text: 'What does conn.cursor() give you?', options: ['A database backup', 'An object to run SQL commands with', 'A new database file', 'A list of tables'], correct_index: 1 })),
  lesson(4, 'CRUD Operations', 7, { explanation: 'CRUD (Create, Read, Update, Delete) operations are run via SQL statements like INSERT, SELECT, UPDATE, DELETE.', syntax: 'cur.execute("INSERT INTO students VALUES (?)", (name,))', examples: [ex('import sqlite3\nconn = sqlite3.connect(":memory:")\ncur = conn.cursor()\ncur.execute("CREATE TABLE t (name TEXT)")\ncur.execute("INSERT INTO t VALUES (?)", ("Sam",))\ncur.execute("SELECT * FROM t")\nprint(cur.fetchone())', "('Sam',)")], important_points: ['Using ? placeholders (parameterized queries) protects against SQL injection.'], common_mistakes: [], real_world: '' }, { starter_code: 'import sqlite3\nconn = sqlite3.connect(":memory:")\ncur = conn.cursor()\ncur.execute("CREATE TABLE t (name TEXT)")\ncur.execute("INSERT INTO t VALUES (?)", ("Sam",))\ncur.execute("SELECT * FROM t")\nprint(cur.fetchone())' }, quickCheck({ text: 'Why use ? placeholders instead of building a raw SQL string?', options: ['They run faster only', 'They protect against SQL injection', 'They are required by Python syntax', 'They format the output'], correct_index: 1 })),
  lesson(5, 'SQL Queries from Python', 6, { explanation: 'cur.fetchall() returns every row from your last SELECT query as a list.', syntax: 'rows = cur.fetchall()', examples: [ex('import sqlite3\nconn = sqlite3.connect(":memory:")\ncur = conn.cursor()\ncur.execute("CREATE TABLE t (name TEXT)")\ncur.execute("INSERT INTO t VALUES (?)", ("Sam",))\ncur.execute("SELECT * FROM t")\nprint(cur.fetchall())', "[('Sam',)]")], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'import sqlite3\nconn = sqlite3.connect(":memory:")\ncur = conn.cursor()\ncur.execute("CREATE TABLE t (name TEXT)")\ncur.execute("INSERT INTO t VALUES (?)", ("Sam",))\ncur.execute("SELECT * FROM t")\nprint(cur.fetchall())' }, quickCheck({ text: 'What does cur.fetchall() return?', options: ['Only the first row', 'Every row from the last query, as a list', 'The table name', 'Nothing'], correct_index: 1 }))
];

const M13 = [
  lesson(1, 'HTTP Basics', 5, { explanation: 'HTTP is the protocol used to communicate with web servers — requests have a method like GET or POST and get back a response.', syntax: '', examples: [ex('', 'A GET request asks for data; a POST request typically sends data to be created/processed.')], important_points: [], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'Which HTTP method is typically used to fetch data?', options: ['GET', 'DELETE', 'PATCH', 'PUT only'], correct_index: 0 })),
  lesson(2, 'APIs', 5, { explanation: 'An API (Application Programming Interface) lets your program communicate with another service, often over HTTP.', syntax: '', examples: [ex('', 'A weather API lets your program request current weather data for a city.')], important_points: [], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'What is a web API typically used for?', options: ['Styling a webpage', 'Letting programs communicate over HTTP', 'Compiling code', 'Formatting text only'], correct_index: 1 })),
  lesson(3, 'JSON', 5, { explanation: 'JSON is the standard text format most APIs use to send structured data.', syntax: 'import json\njson.loads(text)', examples: [ex('import json\ndata = json.loads(\'{"name": "Sam"}\')\nprint(data["name"])', 'Sam')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'import json\ndata = json.loads(\'{"name": "Sam"}\')\nprint(data["name"])' }, quickCheck({ text: 'What does json.loads(text) do?', options: ['Converts a dict to text', 'Parses JSON text into a Python object', 'Sends a request', 'Deletes data'], correct_index: 1 })),
  lesson(4, 'GET', 6, { explanation: 'requests.get(url) sends a GET request and returns a response object containing the data.', syntax: 'import requests\nres = requests.get(url)', examples: [ex('', 'res = requests.get("https://api.example.com/data"); print(res.json())')], important_points: ['res.status_code tells you if the request succeeded (200) or failed.'], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'What does requests.get(url) do?', options: ['Sends data to the server', 'Fetches data from the server', 'Deletes a resource', 'Opens a file'], correct_index: 1 })),
  lesson(5, 'POST', 6, { explanation: 'requests.post(url, json=data) sends data to a server, typically to create or update something.', syntax: 'requests.post(url, json={"name": "Sam"})', examples: [ex('', 'requests.post("https://api.example.com/users", json={"name": "Sam"})')], important_points: [], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'What is requests.post() typically used for?', options: ['Only reading data', 'Sending data to create/update something', 'Deleting the connection', 'Formatting responses'], correct_index: 1 })),
  lesson(6, 'API Response Handling', 6, { explanation: 'Always check the response status and handle errors before assuming the data is valid.', syntax: 'if res.status_code == 200:\n    data = res.json()', examples: [ex('status_code = 200\nif status_code == 200:\n    print("success")\nelse:\n    print("failed")', 'success')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'status_code = 200\nif status_code == 200:\n    print("success")\nelse:\n    print("failed")' }, quickCheck({ text: 'Why check res.status_code before using the response data?', options: ['It is optional and rarely useful', 'To confirm the request actually succeeded', 'It changes the request method', 'It formats the JSON'], correct_index: 1 })),
  lesson(7, 'Python API Project', 8, { explanation: 'Combine requests + JSON handling into a small end-to-end workflow: fetch data and use it.', syntax: '', examples: [ex('data = {"temp": 22}\nprint(f"Temperature: {data[\'temp\']}°C")', 'Temperature: 22°C')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'data = {"temp": 25}\nprint(f"Temperature: {data[\'temp\']}°C")' }, quickCheck({ text: 'Why wrap an API call in try/except in real code?', options: ['It is required syntax', 'Network requests can fail', 'It makes requests faster', 'It is never necessary'], correct_index: 1 }))
];

const M14 = [
  lesson(1, 'Arrays/Lists', 6, { explanation: 'Python uses lists where other languages use arrays — indexed access is O(1), same fast lookup.', syntax: '', examples: [ex('nums = [1, 2, 3]\nprint(nums[1])', '2')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'nums = [1, 2, 3]\nprint(nums[1])' }, quickCheck({ text: 'What is the time complexity of accessing nums[i] in a Python list?', options: ['O(n)', 'O(1)', 'O(log n)', 'O(n^2)'], correct_index: 1 })),
  lesson(2, 'Stack', 5, { explanation: 'A Python list can act as a stack (LIFO) using append() to push and pop() to remove from the end.', syntax: 'stack.append(1)\nstack.pop()', examples: [ex('stack = []\nstack.append(1)\nstack.append(2)\nprint(stack.pop())', '2')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'stack = []\nstack.append(1)\nstack.append(2)\nprint(stack.pop())' }, quickCheck({ text: 'What does stack.pop() return by default?', options: ['The first element added', 'The last element added', 'A random element', 'The whole list'], correct_index: 1 })),
  lesson(3, 'Queue', 5, { explanation: 'collections.deque provides an efficient queue (FIFO) with popleft() to remove from the front.', syntax: 'from collections import deque\nq = deque()', examples: [ex('from collections import deque\nq = deque()\nq.append(1)\nq.append(2)\nprint(q.popleft())', '1')], important_points: ['A plain list\'s pop(0) also removes the first item, but it is slower (O(n)) than deque\'s popleft() (O(1)).'], common_mistakes: [], real_world: '' }, { starter_code: 'from collections import deque\nq = deque()\nq.append(1)\nq.append(2)\nprint(q.popleft())' }, quickCheck({ text: 'Why prefer deque over a list for a queue?', options: ['deque cannot hold numbers', 'popleft() on deque is O(1), faster than list.pop(0)', 'Lists cannot store queues at all', 'There is no difference'], correct_index: 1 })),
  lesson(4, 'Searching', 5, { explanation: 'Linear search checks each element in order; Python\'s "in" operator does this for you.', syntax: 'target in my_list', examples: [ex('nums = [1, 3, 5, 7]\nprint(5 in nums)', 'True')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'nums = [1, 3, 5, 7]\nprint(5 in nums)' }, quickCheck({ text: 'What does "5 in nums" check?', options: ['If nums has exactly 5 elements', 'If 5 is present anywhere in nums', 'The index of 5', 'If nums is sorted'], correct_index: 1 })),
  lesson(5, 'Sorting', 5, { explanation: 'sorted() returns a new sorted list; list.sort() sorts a list in place.', syntax: 'sorted(my_list)', examples: [ex('nums = [3, 1, 2]\nprint(sorted(nums))', '[1, 2, 3]')], important_points: ['sorted() leaves the original list unchanged; .sort() modifies it directly.'], common_mistakes: [], real_world: '' }, { starter_code: 'nums = [3, 1, 2]\nprint(sorted(nums))' }, quickCheck({ text: 'Does sorted(my_list) modify the original list?', options: ['Yes', 'No, it returns a new sorted list', 'Only for numbers', 'It raises an error'], correct_index: 1 })),
  lesson(6, 'Linked List Basics', 6, { explanation: 'A linked list node can be modeled as a small class holding a value and a reference to the next node.', syntax: 'class Node:\n    def __init__(self, val):\n        self.val = val\n        self.next = None', examples: [ex('class Node:\n    def __init__(self, val):\n        self.val = val\n        self.next = None\nhead = Node(10)\nprint(head.val)', '10')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'class Node:\n    def __init__(self, val):\n        self.val = val\n        self.next = None\nhead = Node(10)\nprint(head.val)' }, quickCheck({ text: 'What marks the end of a linked list built this way?', options: ['A node with value 0', 'A node whose "next" is None', 'The first node', 'An empty list'], correct_index: 1 })),
  lesson(7, 'Trees Basics', 6, { explanation: 'A binary tree node can be modeled as a class with a value and left/right child references.', syntax: 'class Node:\n    def __init__(self, val):\n        self.val = val\n        self.left = None\n        self.right = None', examples: [ex('class Node:\n    def __init__(self, val):\n        self.val = val\n        self.left = None\n        self.right = None\nroot = Node(10)\nprint(root.val)', '10')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'class Node:\n    def __init__(self, val):\n        self.val = val\n        self.left = None\n        self.right = None\nroot = Node(10)\nprint(root.val)' }, quickCheck({ text: 'How many children can a binary tree node have at most?', options: ['1', '2', '3', 'Unlimited'], correct_index: 1 })),
  lesson(8, 'Problem Solving', 7, { explanation: 'Apply a list + loop to solve a small problem: count how many times a value appears.', syntax: '', examples: [ex('nums = [1, 2, 2, 3, 1, 1]\nprint(nums.count(1))', '3')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'nums = [4, 4, 5, 6, 4]\n# print how many times 4 appears\n' }, quickCheck({ type: 'code', text: 'Given nums = [4, 4, 5, 6, 4], print how many times 4 appears.', starter_code: 'nums = [4, 4, 5, 6, 4]\nprint(nums.count(4))', test_cases: [{ input: '', expected_output: '3' }] }))
];

const M15 = [
  lesson(1, 'Calculator', 8, { explanation: 'Build a simple calculator: a function that branches on an operator string.', syntax: '', examples: [ex('def calc(a, b, op):\n    if op == "+":\n        return a + b\n    return 0\nprint(calc(4, 3, "+"))', '7')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'def calc(a, b, op):\n    if op == "+":\n        return a + b\n    if op == "-":\n        return a - b\n    return 0\nprint(calc(10, 4, "-"))' }, quickCheck({ type: 'code', text: 'Extend calc to support "*" and print calc(6, 7, "*").', starter_code: 'def calc(a, b, op):\n    if op == "+":\n        return a + b\n    if op == "-":\n        return a - b\n    if op == "*":\n        return a * b\n    return 0\nprint(calc(6, 7, "*"))', test_cases: [{ input: '', expected_output: '42' }] })),
  lesson(2, 'Number Guessing Game', 8, { explanation: 'Model a guessing game: compare a guess to a target number and report high/low/correct.', syntax: '', examples: [ex('target = 7\nguess = 5\nif guess == target:\n    print("Correct!")\nelif guess < target:\n    print("Too low")\nelse:\n    print("Too high")', 'Too low')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'target = 7\nguess = 9\nif guess == target:\n    print("Correct!")\nelif guess < target:\n    print("Too low")\nelse:\n    print("Too high")' }, quickCheck({ text: 'What determines whether the game says "Too low" or "Too high"?', options: ['Random chance', 'Comparing the guess to the target', 'The number of tries', 'It always says "Too low"'], correct_index: 1 })),
  lesson(3, 'Quiz Application', 8, { explanation: 'Model a quiz as a list of question dictionaries, checking the user\'s answer against the correct one.', syntax: '', examples: [ex('questions = [{"q": "2+2?", "answer": 4}]\nuser_answer = 4\nprint(user_answer == questions[0]["answer"])', 'True')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'questions = [{"q": "2+2?", "answer": 4}]\nuser_answer = 4\nprint(user_answer == questions[0]["answer"])' }, quickCheck({ text: 'How do you model a quiz question with its correct answer?', options: ['A single string only', 'A dictionary with question and answer keys', 'A number', 'It cannot be modeled'], correct_index: 1 })),
  lesson(4, 'Student Management System', 9, { explanation: 'Use a class + list of instances to store a small set of student records.', syntax: '', examples: [ex('class Student:\n    def __init__(self, name, marks):\n        self.name = name\n        self.marks = marks\nstudents = [Student("Sam", 85), Student("Ana", 92)]\nprint(students[0].name)', 'Sam')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'class Student:\n    def __init__(self, name, marks):\n        self.name = name\n        self.marks = marks\nstudents = [Student("Sam", 85), Student("Ana", 92)]\n# print each student\'s name and marks\n' }, quickCheck({ text: 'Which combination models a list of student records?', options: ['A single class instance', 'A class + a list of instances', 'A single string', 'A number'], correct_index: 1 })),
  lesson(5, 'Expense Tracker', 9, { explanation: 'Track a list of expense dictionaries, and sum their amounts to get a total.', syntax: '', examples: [ex('expenses = [{"item": "Coffee", "amount": 3}, {"item": "Bus", "amount": 2}]\ntotal = sum(e["amount"] for e in expenses)\nprint(total)', '5')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'expenses = [{"item": "Coffee", "amount": 3}, {"item": "Lunch", "amount": 8}]\n# print the total of all expense amounts\n' }, quickCheck({ type: 'code', text: 'Given expenses [{"amount":3},{"amount":8}], print the total.', starter_code: 'expenses = [{"item": "Coffee", "amount": 3}, {"item": "Lunch", "amount": 8}]\nprint(sum(e["amount"] for e in expenses))', test_cases: [{ input: '', expected_output: '11' }] })),
  lesson(6, 'Contact Management System', 9, { explanation: 'Track a list of contact dictionaries and search through them by name.', syntax: '', examples: [ex('contacts = [{"name": "Sam", "phone": "111"}]\nfor c in contacts:\n    if c["name"] == "Sam":\n        print(c["phone"])', '111')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'contacts = [{"name": "Sam", "phone": "111"}, {"name": "Ana", "phone": "222"}]\n# find and print Ana\'s phone number\n' }, quickCheck({ type: 'code', text: 'Given the contacts list, find and print Ana\'s phone number.', starter_code: 'contacts = [{"name": "Sam", "phone": "111"}, {"name": "Ana", "phone": "222"}]\nfor c in contacts:\n    if c["name"] == "Ana":\n        print(c["phone"])', test_cases: [{ input: '', expected_output: '222' }] })),
  lesson(7, 'Weather API Application', 9, { explanation: 'Combine dictionary handling with the API concepts from Module 13 to display weather-style data.', syntax: '', examples: [ex('data = {"city": "Delhi", "temp": 30}\nprint(f"{data[\'city\']}: {data[\'temp\']}°C")', 'Delhi: 30°C')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'data = {"city": "Mumbai", "temp": 28}\nprint(f"{data[\'city\']}: {data[\'temp\']}°C")' }, quickCheck({ text: 'In a real weather app, where would the temperature data usually come from?', options: ['Typed manually every time', 'A weather API response', 'It is impossible to get', 'A hardcoded constant only'], correct_index: 1 })),
  lesson(8, 'Final Python Project', 10, { explanation: 'Bring it together: a class, a list of them, and a loop to search for one by name.', syntax: '', examples: [ex('class Item:\n    def __init__(self, name):\n        self.name = name\nitems = [Item("Pen"), Item("Book"), Item("Bag")]\nfor i in items:\n    if i.name == "Book":\n        print("Found:", i.name)', 'Found: Book')], important_points: ['This shape — class + list + search loop — is the same pattern behind most small record-management programs.'], common_mistakes: [], real_world: '' }, { starter_code: 'class Item:\n    def __init__(self, name):\n        self.name = name\nitems = [Item("Pen"), Item("Book"), Item("Bag")]\n# find "Bag" and print "Found: Bag"\n' }, quickCheck({ type: 'code', text: 'Given items [Pen, Book, Bag], find and print "Found: Bag".', starter_code: 'class Item:\n    def __init__(self, name):\n        self.name = name\nitems = [Item("Pen"), Item("Book"), Item("Bag")]\nfor i in items:\n    if i.name == "Bag":\n        print("Found:", i.name)', test_cases: [{ input: '', expected_output: 'Found: Bag' }] }))
];

module.exports = { M9, M10, M11, M12, M13, M14, M15 };
