/**
 * Python Full Course — Modules 2-8, authored content (lighter-detail pass).
 * Merged into Backend/pythonCourseData.js's HAND_AUTHORED map by `order`.
 */
let AUTO_ID = 94000;
function qid() { AUTO_ID += 1; return `pyq${AUTO_ID}`; }
function lesson(order, title, estMinutes, learn, practice, test) {
  return { order, title, est_minutes: estMinutes, content_ready: true, learn, practice, test };
}
function quickCheck(q) {
  if (q.type === 'code') return { questions: [{ id: qid(), type: 'code', text: q.text, language: 'python', starter_code: q.starter_code, test_cases: q.test_cases }] };
  return { questions: [{ id: qid(), type: 'mcq', text: q.text, options: q.options, correct_index: q.correct_index }] };
}
function ex(code, output) { return { code, output }; }

const M2 = [
  lesson(1, 'if Statement', 5, { explanation: 'An if statement runs a block of code only when its condition is True.', syntax: 'if condition:\n    # code', examples: [ex('age = 20\nif age >= 18:\n    print("Adult")', 'Adult')], important_points: ['Python uses indentation (not braces) to mark which lines belong to the if block.'], common_mistakes: ['Forgetting the colon at the end of the if line.'], real_world: '' }, { starter_code: 'age = 20\nif age >= 18:\n    print("Adult")' }, quickCheck({ text: 'What marks the start of an if block in Python?', options: ['A curly brace {', 'A colon and indentation', 'A semicolon', 'Parentheses'], correct_index: 1 })),
  lesson(2, 'if-else', 5, { explanation: 'if-else runs one block when the condition is True, and a different block when it is False.', syntax: 'if condition:\n    ...\nelse:\n    ...', examples: [ex('age = 15\nif age >= 18:\n    print("Adult")\nelse:\n    print("Minor")', 'Minor')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'age = 15\nif age >= 18:\n    print("Adult")\nelse:\n    print("Minor")' }, quickCheck({ text: 'When does the else block run?', options: ['Always', 'Only when the if condition is False', 'Only when the if condition is True', 'Never in Python'], correct_index: 1 })),
  lesson(3, 'elif', 5, { explanation: 'elif ("else if") lets you check several conditions in order, running the first one that\'s True.', syntax: 'if a:\n    ...\nelif b:\n    ...\nelse:\n    ...', examples: [ex('marks = 75\nif marks >= 90:\n    print("A")\nelif marks >= 60:\n    print("B")\nelse:\n    print("C")', 'B')], important_points: ['Only the first matching branch runs — Python skips the rest once one matches.'], common_mistakes: [], real_world: '' }, { starter_code: 'marks = 75\nif marks >= 90:\n    print("A")\nelif marks >= 60:\n    print("B")\nelse:\n    print("C")' }, quickCheck({ text: 'If multiple elif conditions are True, how many branches run?', options: ['All of them', 'Only the first one that matches', 'None', 'Only the last one'], correct_index: 1 })),
  lesson(4, 'Nested Conditions', 5, { explanation: 'An if statement can contain another if statement inside it, for checking a condition within a condition.', syntax: 'if a:\n    if b:\n        ...', examples: [ex('age = 20\nhas_id = True\nif age >= 18:\n    if has_id:\n        print("Entry allowed")', 'Entry allowed')], important_points: ['Each nested level needs its own extra indentation.'], common_mistakes: [], real_world: '' }, { starter_code: 'age = 20\nhas_id = True\nif age >= 18:\n    if has_id:\n        print("Entry allowed")' }, quickCheck({ text: 'What does nesting if statements let you do?', options: ['Run code faster', 'Check a condition only when an outer condition is also true', 'Skip loops', 'Avoid using else'], correct_index: 1 })),
  lesson(5, 'for Loop', 5, { explanation: 'A for loop repeats a block once for each item in a sequence, like a range or a list.', syntax: 'for item in sequence:\n    ...', examples: [ex('for i in range(3):\n    print(i)', '0\n1\n2')], important_points: ['range(3) generates 0, 1, 2 — it stops before reaching 3.'], common_mistakes: [], real_world: '' }, { starter_code: 'for i in range(3):\n    print(i)' }, quickCheck({ text: 'What values does range(3) produce?', options: ['1, 2, 3', '0, 1, 2', '0, 1, 2, 3', '3, 2, 1'], correct_index: 1 })),
  lesson(6, 'while Loop', 5, { explanation: 'A while loop repeats a block as long as its condition stays True.', syntax: 'while condition:\n    ...', examples: [ex('count = 0\nwhile count < 3:\n    print(count)\n    count += 1', '0\n1\n2')], important_points: ['You must update the condition variable inside the loop, or it may run forever.'], common_mistakes: ['Forgetting to update the loop variable, causing an infinite loop.'], real_world: '' }, { starter_code: 'count = 0\nwhile count < 3:\n    print(count)\n    count += 1' }, quickCheck({ text: 'What happens if you forget to update the condition variable in a while loop?', options: ['It runs once and stops', 'It may loop forever', 'Python stops it automatically', 'A syntax error'], correct_index: 1 })),
  lesson(7, 'break', 5, { explanation: 'break immediately exits the nearest enclosing loop, skipping any remaining iterations.', syntax: 'for x in range(10):\n    if x == 3:\n        break', examples: [ex('for i in range(5):\n    if i == 3:\n        break\n    print(i)', '0\n1\n2')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'for i in range(5):\n    if i == 3:\n        break\n    print(i)' }, quickCheck({ text: 'What does break do inside a loop?', options: ['Skips just this iteration', 'Exits the loop immediately', 'Restarts the loop', 'Pauses the program'], correct_index: 1 })),
  lesson(8, 'continue', 5, { explanation: 'continue skips the rest of the current iteration and moves on to the next one.', syntax: 'for x in range(5):\n    if x == 2:\n        continue', examples: [ex('for i in range(4):\n    if i == 2:\n        continue\n    print(i)', '0\n1\n3')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'for i in range(4):\n    if i == 2:\n        continue\n    print(i)' }, quickCheck({ text: 'What does continue do differently from break?', options: ['It also exits the loop', 'It skips to the next iteration instead of exiting', 'It restarts the program', 'Nothing, they are identical'], correct_index: 1 })),
  lesson(9, 'pass', 5, { explanation: 'pass is a no-op placeholder — it does nothing, used where Python syntax requires a statement but you have no code yet.', syntax: 'if True:\n    pass', examples: [ex('if True:\n    pass\nprint("after")', 'after')], important_points: ['pass is often used to stub out a function or branch you\'ll fill in later.'], common_mistakes: [], real_world: '' }, { starter_code: 'if True:\n    pass\nprint("after")' }, quickCheck({ text: 'What does the pass statement do?', options: ['Skips the current loop iteration', 'Nothing — it is a placeholder', 'Exits the program', 'Raises an error'], correct_index: 1 })),
  lesson(10, 'Nested Loops', 6, { explanation: 'A loop can contain another loop inside it — useful for grids or combinations.', syntax: 'for i in range(2):\n    for j in range(2):\n        ...', examples: [ex('for i in range(2):\n    for j in range(2):\n        print(i, j)', '0 0\n0 1\n1 0\n1 1')], important_points: ['The inner loop completes all its iterations for each single iteration of the outer loop.'], common_mistakes: [], real_world: '' }, { starter_code: 'for i in range(2):\n    for j in range(2):\n        print(i, j)' }, quickCheck({ type: 'code', text: 'Print all pairs (i, j) for i and j in range(2) using nested for loops.', starter_code: 'for i in range(2):\n    for j in range(2):\n        print(i, j)', test_cases: [{ input: '', expected_output: '0 0\n0 1\n1 0\n1 1' }] }))
];

const M3 = [
  lesson(1, 'String Basics', 5, { explanation: 'A string is text wrapped in single or double quotes.', syntax: "name = 'Sam'", examples: [ex('name = "Sam"\nprint(len(name))', '3')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'name = "Sam"\nprint(len(name))' }, quickCheck({ text: 'What does len("Sam") return?', options: ['2', '3', '4', 'Error'], correct_index: 1 })),
  lesson(2, 'String Indexing', 5, { explanation: 'You can access one character of a string by its position, starting at index 0.', syntax: 's[0]', examples: [ex('s = "hello"\nprint(s[1])', 'e')], important_points: ['s[-1] gives the last character — negative indexes count from the end.'], common_mistakes: [], real_world: '' }, { starter_code: 's = "hello"\nprint(s[1])' }, quickCheck({ text: 'What does s[-1] give you for a string s?', options: ['The first character', 'The last character', 'An error always', 'The string length'], correct_index: 1 })),
  lesson(3, 'String Slicing', 6, { explanation: 'Slicing extracts a substring using s[start:end] — end is exclusive.', syntax: 's[0:3]', examples: [ex('s = "hello"\nprint(s[0:3])', 'hel')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 's = "hello"\nprint(s[0:3])' }, quickCheck({ text: 'What does "hello"[0:3] return?', options: ['"hel"', '"hell"', '"ello"', '"llo"'], correct_index: 0 })),
  lesson(4, 'String Methods', 6, { explanation: 'Strings have built-in methods like upper(), lower(), and replace() for common text operations.', syntax: 's.upper()', examples: [ex('s = "hello"\nprint(s.upper())', 'HELLO')], important_points: ['String methods return a new string — strings themselves cannot be changed in place.'], common_mistakes: [], real_world: '' }, { starter_code: 's = "hello"\nprint(s.upper())' }, quickCheck({ text: 'What does "hello".upper() return?', options: ['"hello"', '"HELLO"', '"Hello"', 'An error'], correct_index: 1 })),
  lesson(5, 'String Formatting', 6, { explanation: 'The .format() method inserts values into a string at {} placeholders.', syntax: '"{} is {}".format(name, age)', examples: [ex('name = "Sam"\nprint("Hi {}".format(name))', 'Hi Sam')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'name = "Sam"\nprint("Hi {}".format(name))' }, quickCheck({ text: 'What does {} act as in "Hi {}".format(name)?', options: ['A comment', 'A placeholder filled by format()', 'A syntax error', 'A loop'], correct_index: 1 })),
  lesson(6, 'f-Strings', 5, { explanation: 'f-strings (f"...") are a shorter, modern way to embed variables directly inside a string.', syntax: 'f"{name} is {age}"', examples: [ex('name = "Sam"\nage = 20\nprint(f"{name} is {age}")', 'Sam is 20')], important_points: ['f-strings are generally preferred over .format() for readability in modern Python.'], common_mistakes: [], real_world: '' }, { starter_code: 'name = "Sam"\nage = 20\nprint(f"{name} is {age}")' }, quickCheck({ text: 'How do you mark a string as an f-string?', options: ['Prefix it with f', 'Suffix it with f', 'Wrap it in {}', 'Use double f-quotes'], correct_index: 0 })),
  lesson(7, 'String Practice', 7, { explanation: 'Combine slicing and f-strings to build formatted output.', syntax: '', examples: [ex('name = "Python"\nprint(f"First 3 letters: {name[0:3]}")', 'First 3 letters: Pyt')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 's = "Campus Orbis"\n# print the first 6 characters of s\n' }, quickCheck({ type: 'code', text: 'Given s = "Campus Orbis", print the first 6 characters.', starter_code: 's = "Campus Orbis"\nprint(s[0:6])', test_cases: [{ input: '', expected_output: 'Campus' }] }))
];

// Module 4 (Lists) already has lesson 1 (List Introduction) hand-authored
// in pythonCourseData.js — these are orders 2-10, the rest of the module.
const M4 = [
  lesson(2, 'Creating Lists', 5, { explanation: 'A list is created with square brackets, and can hold any mix of value types.', syntax: 'my_list = [1, "two", 3.0]', examples: [ex('nums = [1, 2, 3]\nprint(nums)', '[1, 2, 3]')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'nums = [1, 2, 3]\nprint(nums)' }, quickCheck({ text: 'Which brackets create a list in Python?', options: ['()', '{}', '[]', '<>'], correct_index: 2 })),
  lesson(3, 'Indexing', 5, { explanation: 'Access a single list item by its position, starting at index 0.', syntax: 'my_list[0]', examples: [ex('nums = [10, 20, 30]\nprint(nums[1])', '20')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'nums = [10, 20, 30]\nprint(nums[1])' }, quickCheck({ text: 'What is nums[0] for nums = [10, 20, 30]?', options: ['10', '20', '30', 'Error'], correct_index: 0 })),
  lesson(4, 'Slicing', 6, { explanation: 'Slicing a list works just like slicing a string: list[start:end].', syntax: 'my_list[1:3]', examples: [ex('nums = [10, 20, 30, 40]\nprint(nums[1:3])', '[20, 30]')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'nums = [10, 20, 30, 40]\nprint(nums[1:3])' }, quickCheck({ text: 'What does [10,20,30,40][1:3] return?', options: ['[10, 20]', '[20, 30]', '[30, 40]', '[20, 30, 40]'], correct_index: 1 })),
  lesson(5, 'Adding Elements', 5, { explanation: 'append() adds one item to the end of a list; insert() adds at a specific position.', syntax: 'my_list.append(4)', examples: [ex('nums = [1, 2]\nnums.append(3)\nprint(nums)', '[1, 2, 3]')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'nums = [1, 2]\nnums.append(3)\nprint(nums)' }, quickCheck({ text: 'What does append(x) do to a list?', options: ['Removes x', 'Adds x to the end', 'Adds x to the beginning', 'Sorts the list'], correct_index: 1 })),
  lesson(6, 'Removing Elements', 5, { explanation: 'remove() deletes the first matching value; pop() removes and returns an item by index.', syntax: 'my_list.remove(2)', examples: [ex('nums = [1, 2, 3]\nnums.remove(2)\nprint(nums)', '[1, 3]')], important_points: ['remove() removes by value; pop() removes by index — easy to mix up.'], common_mistakes: [], real_world: '' }, { starter_code: 'nums = [1, 2, 3]\nnums.remove(2)\nprint(nums)' }, quickCheck({ text: 'Does remove(x) remove by value or by index?', options: ['By value', 'By index', 'Both work identically', 'Neither'], correct_index: 0 })),
  lesson(7, 'List Methods', 6, { explanation: 'Lists have many built-in methods: sort(), reverse(), count(), index(), and more.', syntax: 'my_list.sort()', examples: [ex('nums = [3, 1, 2]\nnums.sort()\nprint(nums)', '[1, 2, 3]')], important_points: ['sort() sorts the list in place — it doesn\'t return a new list.'], common_mistakes: [], real_world: '' }, { starter_code: 'nums = [3, 1, 2]\nnums.sort()\nprint(nums)' }, quickCheck({ text: 'Does list.sort() return a new list?', options: ['Yes', 'No, it sorts in place and returns None', 'Only for numbers', 'It raises an error'], correct_index: 1 })),
  lesson(8, 'Nested Lists', 6, { explanation: 'A list can contain other lists, forming a grid-like structure.', syntax: 'grid = [[1, 2], [3, 4]]', examples: [ex('grid = [[1, 2], [3, 4]]\nprint(grid[1][0])', '3')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'grid = [[1, 2], [3, 4]]\nprint(grid[1][0])' }, quickCheck({ text: 'For grid = [[1,2],[3,4]], what is grid[0][1]?', options: ['1', '2', '3', '4'], correct_index: 1 })),
  lesson(9, 'List Comprehension', 7, { explanation: 'List comprehension is a compact way to build a new list from an existing one in a single line.', syntax: '[x * 2 for x in nums]', examples: [ex('nums = [1, 2, 3]\ndoubled = [x * 2 for x in nums]\nprint(doubled)', '[2, 4, 6]')], important_points: ['A list comprehension does the same job as a for loop + append(), but more compactly.'], common_mistakes: [], real_world: '' }, { starter_code: 'nums = [1, 2, 3]\ndoubled = [x * 2 for x in nums]\nprint(doubled)' }, quickCheck({ text: 'What does [x * 2 for x in nums] produce?', options: ['A single number', 'A new list with each element doubled', 'The original list unchanged', 'A syntax error'], correct_index: 1 })),
  lesson(10, 'List Practice', 7, { explanation: 'Combine list methods and comprehension to solve a small task.', syntax: '', examples: [ex('nums = [1, 2, 3, 4]\nprint(sum(nums))', '10')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'nums = [5, 10, 15]\n# print the sum of nums\n' }, quickCheck({ type: 'code', text: 'Given nums = [5, 10, 15], print their sum.', starter_code: 'nums = [5, 10, 15]\nprint(sum(nums))', test_cases: [{ input: '', expected_output: '30' }] }))
];

const M5 = [
  lesson(1, 'Tuple Basics', 5, { explanation: 'A tuple is an ordered collection like a list, but immutable — it can\'t be changed after creation.', syntax: 't = (1, 2, 3)', examples: [ex('t = (1, 2, 3)\nprint(t)', '(1, 2, 3)')], important_points: ['Use a tuple when you want to guarantee the data won\'t change.'], common_mistakes: [], real_world: '' }, { starter_code: 't = (1, 2, 3)\nprint(t)' }, quickCheck({ text: 'What is the main difference between a tuple and a list?', options: ['Tuples can hold more data', 'Tuples are immutable', 'Tuples are always faster to print', 'No difference'], correct_index: 1 })),
  lesson(2, 'Tuple Indexing', 5, { explanation: 'Tuples support indexing exactly like lists — access an item with t[i].', syntax: 't[0]', examples: [ex('t = (10, 20, 30)\nprint(t[1])', '20')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 't = (10, 20, 30)\nprint(t[1])' }, quickCheck({ text: 'What is t[0] for t = (10, 20, 30)?', options: ['10', '20', '30', 'Error'], correct_index: 0 })),
  lesson(3, 'Tuple Methods', 5, { explanation: 'Tuples support a small set of methods since they\'re immutable: count() and index().', syntax: 't.count(2)', examples: [ex('t = (1, 2, 2, 3)\nprint(t.count(2))', '2')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 't = (1, 2, 2, 3)\nprint(t.count(2))' }, quickCheck({ text: 'Why do tuples have fewer methods than lists?', options: ['They are less useful', 'They are immutable, so no methods change them', 'Python forbids extra tuple methods', 'It is a bug'], correct_index: 1 })),
  lesson(4, 'Tuple Unpacking', 6, { explanation: 'You can assign a tuple\'s values directly to separate variables in one line.', syntax: 'x, y = (1, 2)', examples: [ex('point = (3, 4)\nx, y = point\nprint(x, y)', '3 4')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'point = (3, 4)\nx, y = point\nprint(x, y)' }, quickCheck({ text: 'What does "x, y = (1, 2)" do?', options: ['Creates a tuple named x, y', 'Assigns 1 to x and 2 to y', 'A syntax error', 'Assigns 2 to x and 1 to y'], correct_index: 1 })),
  lesson(5, 'Set Basics', 5, { explanation: 'A set is an unordered collection of unique values — duplicates are automatically removed.', syntax: 's = {1, 2, 3}', examples: [ex('s = {1, 2, 2, 3}\nprint(s)', '{1, 2, 3}')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 's = {1, 2, 2, 3}\nprint(s)' }, quickCheck({ text: 'What happens to duplicate values in a set?', options: ['They are kept', 'They are automatically removed', 'They cause an error', 'They are sorted'], correct_index: 1 })),
  lesson(6, 'Set Add/Remove', 5, { explanation: 'add() inserts one value into a set; remove() deletes one.', syntax: 's.add(4)', examples: [ex('s = {1, 2}\ns.add(3)\nprint(s)', '{1, 2, 3}')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 's = {1, 2}\ns.add(3)\nprint(s)' }, quickCheck({ text: 'Which method adds a value to a set?', options: ['append()', 'add()', 'insert()', 'push()'], correct_index: 1 })),
  lesson(7, 'Set Union', 5, { explanation: 'Union combines two sets, keeping every unique value from both.', syntax: 'a | b', examples: [ex('a = {1, 2}\nb = {2, 3}\nprint(a | b)', '{1, 2, 3}')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'a = {1, 2}\nb = {2, 3}\nprint(a | b)' }, quickCheck({ text: 'What does a | b compute for two sets?', options: ['Only values in both', 'All unique values from both', 'Only values in a', 'A syntax error'], correct_index: 1 })),
  lesson(8, 'Set Intersection', 5, { explanation: 'Intersection finds only the values present in both sets.', syntax: 'a & b', examples: [ex('a = {1, 2, 3}\nb = {2, 3, 4}\nprint(a & b)', '{2, 3}')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'a = {1, 2, 3}\nb = {2, 3, 4}\nprint(a & b)' }, quickCheck({ text: 'What does a & b compute?', options: ['Values in either set', 'Values in both sets', 'Values only in a', 'The size of a'], correct_index: 1 })),
  lesson(9, 'Set Difference', 5, { explanation: 'Difference finds values in the first set that are not in the second.', syntax: 'a - b', examples: [ex('a = {1, 2, 3}\nb = {2, 3}\nprint(a - b)', '{1}')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'a = {1, 2, 3}\nb = {2, 3}\nprint(a - b)' }, quickCheck({ text: 'What does a - b return?', options: ['Values in b not in a', 'Values in a not in b', 'Values in both', 'All values from both'], correct_index: 1 })),
  lesson(10, 'Dictionary Basics', 5, { explanation: 'A dictionary stores key-value pairs, letting you look up a value by its key.', syntax: 'd = {"name": "Sam"}', examples: [ex('d = {"name": "Sam"}\nprint(d["name"])', 'Sam')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'd = {"name": "Sam"}\nprint(d["name"])' }, quickCheck({ text: 'How do you access a dictionary value by key "name"?', options: ['d.name', 'd["name"]', 'd(name)', 'd->name'], correct_index: 1 })),
  lesson(11, 'Dictionary Keys and Values', 5, { explanation: '.keys() and .values() give you the dictionary\'s keys or values separately.', syntax: 'd.keys(); d.values()', examples: [ex('d = {"a": 1, "b": 2}\nprint(list(d.keys()))', "['a', 'b']")], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'd = {"a": 1, "b": 2}\nprint(list(d.keys()))' }, quickCheck({ text: 'What does d.keys() return?', options: ['The dictionary\'s values', 'The dictionary\'s keys', 'A single key', 'Nothing'], correct_index: 1 })),
  lesson(12, 'Adding/Updating Data', 5, { explanation: 'Assigning to a new or existing key adds or updates that entry.', syntax: 'd["age"] = 20', examples: [ex('d = {"name": "Sam"}\nd["age"] = 20\nprint(d)', "{'name': 'Sam', 'age': 20}")], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'd = {"name": "Sam"}\nd["age"] = 20\nprint(d)' }, quickCheck({ text: 'What happens if you assign to an existing dictionary key?', options: ['An error occurs', 'The value is updated', 'A duplicate key is added', 'Nothing happens'], correct_index: 1 })),
  lesson(13, 'Removing Data', 5, { explanation: 'del or .pop(key) removes an entry from a dictionary.', syntax: 'del d["age"]', examples: [ex('d = {"name": "Sam", "age": 20}\ndel d["age"]\nprint(d)', "{'name': 'Sam'}")], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'd = {"name": "Sam", "age": 20}\ndel d["age"]\nprint(d)' }, quickCheck({ text: 'What does "del d[key]" do?', options: ['Adds a key', 'Removes the key-value pair', 'Clears the whole dictionary', 'Renames the key'], correct_index: 1 })),
  lesson(14, 'Dictionary Methods', 5, { explanation: '.get(key, default) safely reads a value, returning a default instead of an error if the key is missing.', syntax: 'd.get("age", 0)', examples: [ex('d = {"name": "Sam"}\nprint(d.get("age", 0))', '0')], important_points: ['Using d["age"] directly would raise a KeyError if "age" doesn\'t exist — .get() avoids that.'], common_mistakes: [], real_world: '' }, { starter_code: 'd = {"name": "Sam"}\nprint(d.get("age", 0))' }, quickCheck({ text: 'What does d.get("age", 0) do if "age" is missing?', options: ['Raises an error', 'Returns 0', 'Returns None always', 'Adds "age": 0'], correct_index: 1 })),
  lesson(15, 'Nested Dictionaries', 6, { explanation: 'A dictionary value can itself be another dictionary, letting you model structured records.', syntax: 'student = {"name": "Sam", "grades": {"math": 90}}', examples: [ex('student = {"name": "Sam", "grades": {"math": 90}}\nprint(student["grades"]["math"])', '90')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'student = {"name": "Sam", "grades": {"math": 90}}\nprint(student["grades"]["math"])' }, quickCheck({ text: 'How do you reach a value in a nested dictionary?', options: ['Chain the keys: d["a"]["b"]', 'd.a.b only', 'It is not possible', 'd["a,b"]'], correct_index: 0 }))
];

const M6 = [
  lesson(1, 'Function Basics', 5, { explanation: 'A function is a reusable named block of code, defined with "def".', syntax: 'def add(a, b):\n    return a + b', examples: [ex('def add(a, b):\n    return a + b\nprint(add(2, 3))', '5')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'def add(a, b):\n    return a + b\nprint(add(2, 3))' }, quickCheck({ text: 'What keyword defines a function in Python?', options: ['func', 'def', 'function', 'lambda only'], correct_index: 1 })),
  lesson(2, 'Parameters', 5, { explanation: 'Parameters are the named inputs a function accepts.', syntax: 'def greet(name):\n    print(f"Hi {name}")', examples: [ex('def greet(name):\n    print(f"Hi {name}")\ngreet("Sam")', 'Hi Sam')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'def greet(name):\n    print(f"Hi {name}")\ngreet("Sam")' }, quickCheck({ text: 'In def greet(name), what is "name"?', options: ['A global variable', 'A parameter', 'The return value', 'A comment'], correct_index: 1 })),
  lesson(3, 'Arguments', 5, { explanation: 'Arguments are the actual values you pass into a function when calling it.', syntax: 'greet("Sam")  # "Sam" is the argument', examples: [ex('def greet(name):\n    print(f"Hi {name}")\ngreet("Ana")', 'Hi Ana')], important_points: ['"Parameter" is the name in the function definition; "argument" is the value passed at call time.'], common_mistakes: [], real_world: '' }, { starter_code: 'def greet(name):\n    print(f"Hi {name}")\ngreet("Ana")' }, quickCheck({ text: 'What is the difference between a parameter and an argument?', options: ['No difference', 'A parameter is in the definition; an argument is the value passed at call time', 'Arguments are only numbers', 'Parameters are only strings'], correct_index: 1 })),
  lesson(4, 'Return Values', 5, { explanation: 'return sends a value back from a function to wherever it was called.', syntax: 'def square(n):\n    return n * n', examples: [ex('def square(n):\n    return n * n\nprint(square(4))', '16')], important_points: ['A function without a return statement returns None by default.'], common_mistakes: [], real_world: '' }, { starter_code: 'def square(n):\n    return n * n\nprint(square(4))' }, quickCheck({ text: 'What does a function return if it has no return statement?', options: ['0', 'None', 'An empty string', 'An error'], correct_index: 1 })),
  lesson(5, 'Default Arguments', 5, { explanation: 'A parameter can have a default value, used automatically if the caller doesn\'t supply one.', syntax: 'def greet(name="friend"):\n    ...', examples: [ex('def greet(name="friend"):\n    print(f"Hi {name}")\ngreet()', 'Hi friend')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'def greet(name="friend"):\n    print(f"Hi {name}")\ngreet()' }, quickCheck({ text: 'What happens if greet() is called with no argument and name has a default?', options: ['A crash', 'The default value is used', 'name becomes None', 'A syntax error'], correct_index: 1 })),
  lesson(6, 'Keyword Arguments', 5, { explanation: 'Keyword arguments let you pass values by parameter name, in any order.', syntax: 'greet(name="Sam", age=20)', examples: [ex('def info(name, age):\n    print(name, age)\ninfo(age=20, name="Sam")', 'Sam 20')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'def info(name, age):\n    print(name, age)\ninfo(age=20, name="Sam")' }, quickCheck({ text: 'What is the benefit of keyword arguments?', options: ['They run faster', 'You can pass them in any order by name', 'They are required for every function', 'They replace return values'], correct_index: 1 })),
  lesson(7, 'Variable-length Arguments', 6, { explanation: '*args collects any number of extra positional arguments into a tuple.', syntax: 'def total(*nums):\n    return sum(nums)', examples: [ex('def total(*nums):\n    return sum(nums)\nprint(total(1, 2, 3))', '6')], important_points: ['**kwargs similarly collects extra named arguments into a dictionary.'], common_mistakes: [], real_world: '' }, { starter_code: 'def total(*nums):\n    return sum(nums)\nprint(total(1, 2, 3))' }, quickCheck({ text: 'What does *nums collect in a function definition?', options: ['Exactly one argument', 'Any number of extra positional arguments, as a tuple', 'Keyword arguments only', 'Nothing, it is invalid'], correct_index: 1 })),
  lesson(8, 'Scope', 6, { explanation: 'A variable\'s scope is where it can be accessed — local (inside a function) or global (outside).', syntax: 'def f():\n    x = 5  # local to f', examples: [ex('def f():\n    x = 5\n    print(x)\nf()', '5')], important_points: ['A local variable inside a function is not visible outside it.'], common_mistakes: [], real_world: '' }, { starter_code: 'def f():\n    x = 5\n    print(x)\nf()' }, quickCheck({ text: 'Can a variable defined inside a function be accessed outside it?', options: ['Yes, always', 'No, not by default (it is local)', 'Only if named x', 'Only in loops'], correct_index: 1 })),
  lesson(9, 'Lambda Functions', 6, { explanation: 'A lambda is a small, unnamed, one-line function.', syntax: 'square = lambda x: x * x', examples: [ex('square = lambda x: x * x\nprint(square(5))', '25')], important_points: ['Lambdas are limited to a single expression — no statements or multiple lines.'], common_mistakes: [], real_world: '' }, { starter_code: 'square = lambda x: x * x\nprint(square(5))' }, quickCheck({ text: 'What is a defining trait of a lambda function?', options: ['It must have a name', 'It is a small, unnamed, one-expression function', 'It cannot take arguments', 'It always returns None'], correct_index: 1 })),
  lesson(10, 'Recursion', 6, { explanation: 'A recursive function calls itself with a smaller input, until a base case stops it.', syntax: 'def fact(n):\n    if n <= 1:\n        return 1\n    return n * fact(n - 1)', examples: [ex('def fact(n):\n    if n <= 1:\n        return 1\n    return n * fact(n - 1)\nprint(fact(4))', '24')], important_points: ['Every recursive function needs a base case, or it never stops.'], common_mistakes: [], real_world: '' }, { starter_code: 'def fact(n):\n    if n <= 1:\n        return 1\n    return n * fact(n - 1)\nprint(fact(5))' }, quickCheck({ type: 'code', text: 'Write a recursive fact(n) and print fact(6).', starter_code: 'def fact(n):\n    if n <= 1:\n        return 1\n    return n * fact(n - 1)\nprint(fact(6))', test_cases: [{ input: '', expected_output: '720' }] }))
];

const M7 = [
  lesson(1, 'Modules', 5, { explanation: 'A module is simply a .py file containing reusable code (functions, variables, classes) you can use in other files.', syntax: '', examples: [ex('', 'A file "math_utils.py" containing functions is itself a module.')], important_points: [], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'What is a Python module?', options: ['A special kind of loop', 'A .py file of reusable code', 'A built-in data type', 'A test framework'], correct_index: 1 })),
  lesson(2, 'import', 5, { explanation: 'import brings an entire module into your script so you can use its contents.', syntax: 'import math\nprint(math.sqrt(16))', examples: [ex('import math\nprint(math.sqrt(16))', '4.0')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'import math\nprint(math.sqrt(16))' }, quickCheck({ text: 'After "import math", how do you call sqrt?', options: ['sqrt(16)', 'math.sqrt(16)', 'math->sqrt(16)', 'Math.Sqrt(16)'], correct_index: 1 })),
  lesson(3, 'from import', 5, { explanation: '"from module import name" imports just one specific thing, so you can use it without the module prefix.', syntax: 'from math import sqrt\nprint(sqrt(16))', examples: [ex('from math import sqrt\nprint(sqrt(16))', '4.0')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'from math import sqrt\nprint(sqrt(16))' }, quickCheck({ text: 'After "from math import sqrt", how do you call it?', options: ['math.sqrt(16)', 'sqrt(16)', 'from.sqrt(16)', 'import.sqrt(16)'], correct_index: 1 })),
  lesson(4, 'Built-in Modules', 5, { explanation: 'Python ships with many built-in modules — math, random, datetime, os, and more.', syntax: 'import random\nprint(random.randint(1, 10))', examples: [ex('import random\nprint(type(random.randint(1, 10)))', "<class 'int'>")], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'import random\nprint(type(random.randint(1, 10)))' }, quickCheck({ text: 'Which of these is a Python built-in module?', options: ['requests', 'pandas', 'math', 'flask'], correct_index: 2 })),
  lesson(5, 'Creating Custom Modules', 6, { explanation: 'Any .py file you write can be imported by another file in the same project, just like a built-in module.', syntax: 'import my_helpers', examples: [ex('', 'If you have greet.py with a hello() function, another file can do "import greet" then "greet.hello()".')], important_points: [], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'Can you import your own .py files the same way as built-in modules?', options: ['No, never', 'Yes', 'Only with pip', 'Only in Jupyter'], correct_index: 1 })),
  lesson(6, 'Packages', 6, { explanation: 'A package is a folder of modules, usually containing an __init__.py file, letting you organize related modules together.', syntax: 'import package.module', examples: [ex('', 'A folder "shapes/" with circle.py and square.py can be imported as "shapes.circle".')], important_points: [], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'What is a Python package?', options: ['A single function', 'A folder of related modules', 'A built-in data type', 'A test file'], correct_index: 1 })),
  lesson(7, 'pip', 6, { explanation: 'pip is Python\'s package installer, used to install third-party libraries from PyPI.', syntax: 'pip install requests', examples: [ex('', 'Running "pip install requests" downloads and installs the requests library.')], important_points: ['pip is run from the command line, not inside a Python script.'], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'What is pip used for?', options: ['Running Python scripts', 'Installing third-party Python packages', 'Formatting code', 'Debugging'], correct_index: 1 }))
];

const M8 = [
  lesson(1, 'Opening Files', 5, { explanation: 'open() opens a file, returning a file object you can read from or write to.', syntax: 'f = open("data.txt", "r")', examples: [ex('f = open("data.txt", "w")\nprint("opened")\nf.close()', 'opened')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'f = open("data.txt", "w")\nprint("opened")\nf.close()' }, quickCheck({ text: 'What does open("data.txt", "r") do?', options: ['Deletes the file', 'Opens the file for reading', 'Creates a new empty file', 'Opens the file for writing only'], correct_index: 1 })),
  lesson(2, 'Reading Files', 5, { explanation: '.read() reads a file\'s entire contents as one string; .readline() reads one line at a time.', syntax: 'content = f.read()', examples: [ex('', 'f = open("data.txt", "r"); content = f.read(); f.close()')], important_points: [], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'What does f.read() return?', options: ['A single character', 'The entire file contents as a string', 'The file name', 'Nothing'], correct_index: 1 })),
  lesson(3, 'Writing Files', 5, { explanation: '.write() writes text to a file opened in write mode.', syntax: 'f.write("hello")', examples: [ex('f = open("out.txt", "w")\nf.write("hello")\nf.close()\nprint("written")', 'written')], important_points: ['Opening a file in "w" mode erases its existing contents first.'], common_mistakes: [], real_world: '' }, { starter_code: 'f = open("out.txt", "w")\nf.write("hello")\nf.close()\nprint("written")' }, quickCheck({ text: 'What happens to existing content when you open a file in "w" mode?', options: ['It is preserved', 'It is erased', 'It is appended to', 'Nothing happens'], correct_index: 1 })),
  lesson(4, 'Appending Files', 5, { explanation: 'Opening a file in "a" mode adds new writes after the existing content instead of erasing it.', syntax: 'f = open("out.txt", "a")', examples: [ex('f = open("out.txt", "a")\nf.write("more")\nf.close()\nprint("appended")', 'appended')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'f = open("out.txt", "a")\nf.write("more")\nf.close()\nprint("appended")' }, quickCheck({ text: 'Which mode appends instead of overwriting?', options: ['"r"', '"w"', '"a"', '"x"'], correct_index: 2 })),
  lesson(5, 'File Modes', 5, { explanation: 'Common modes: "r" read, "w" write (overwrite), "a" append, "x" create (fails if it exists).', syntax: 'open(path, mode)', examples: [ex('', '"r" is the default mode if none is specified.')], important_points: [], common_mistakes: [], real_world: '' }, null, quickCheck({ text: 'What is the default file mode if none is given to open()?', options: ['"w"', '"a"', '"r"', '"x"'], correct_index: 2 })),
  lesson(6, 'with Statement', 6, { explanation: '"with open(...) as f:" automatically closes the file for you when the block ends, even if an error occurs.', syntax: 'with open("data.txt") as f:\n    content = f.read()', examples: [ex('with open("out.txt", "w") as f:\n    f.write("hi")\nprint("done")', 'done')], important_points: ['Using "with" is preferred over manually calling f.close(), since it\'s automatic and safer.'], common_mistakes: [], real_world: '' }, { starter_code: 'with open("out.txt", "w") as f:\n    f.write("hi")\nprint("done")' }, quickCheck({ text: 'What is the main benefit of "with open(...) as f:"?', options: ['It reads files faster', 'It automatically closes the file, even on error', 'It prevents writing', 'It is required to open any file'], correct_index: 1 })),
  lesson(7, 'Working with CSV', 6, { explanation: 'The csv module reads and writes comma-separated value files, row by row.', syntax: 'import csv\nreader = csv.reader(f)', examples: [ex('import csv\nprint(csv.__name__)', 'csv')], important_points: [], common_mistakes: [], real_world: '' }, { starter_code: 'import csv\nprint(csv.__name__)' }, quickCheck({ text: 'What is the csv module used for?', options: ['Sending emails', 'Reading and writing comma-separated files', 'Making HTTP requests', 'Drawing graphics'], correct_index: 1 })),
  lesson(8, 'Working with JSON', 6, { explanation: 'The json module converts between Python dictionaries and JSON text.', syntax: 'import json\njson.dumps(data)', examples: [ex('import json\nprint(json.dumps({"name": "Sam"}))', '{"name": "Sam"}')], important_points: ['json.dumps() converts a dict to JSON text; json.loads() converts JSON text back to a dict.'], common_mistakes: [], real_world: '' }, { starter_code: 'import json\nprint(json.dumps({"name": "Sam"}))' }, quickCheck({ text: 'What does json.dumps(data) do?', options: ['Parses JSON text into a dict', 'Converts a dict into JSON text', 'Deletes data', 'Opens a file'], correct_index: 1 }))
];

module.exports = { M2, M3, M4, M5, M6, M7, M8 };
