'use strict';
// ---------------------------------------------------------------------------
// Security headers (Helmet) — Section 13 of the hardening pass.
//
// This only governs what Express itself serves: the JSON API (headers only
// matter there, there's no HTML) and the legacy static site in Backend/public
// (index.html / start.html + app_logic.js), which IS the actual served
// frontend for this app — the React app under Frontend/ is built and served
// separately and never touches this Express process, so it isn't covered by
// this CSP.
//
// The CSP below was built by actually reading Backend/public's HTML rather
// than guessing:
//   - Two Google Fonts <link> stylesheets                -> style-src + font-src
//   - pdf.js + Chart.js loaded from cdnjs.cloudflare.com  -> script-src
//   - pdf.js's worker, also from cdnjs                    -> worker-src
//   - A handful of inline <script> blocks (theme-on-load,
//     pdf.js worker path) -> allowed individually by SHA-256 hash, NOT
//     'unsafe-inline', so injecting a new inline script still fails CSP
//   - Extensive inline style="" attributes (the whole UI is generated by
//     string-built HTML, not a component framework) -> style-src needs
//     'unsafe-inline'; there is no practical way to hash/nonce hundreds of
//     dynamically-generated attributes, so this is a deliberate, documented
//     trade-off (style injection is a much lower-severity primitive than
//     script injection, which stays strict)
//   - Camera/mic recording during test monitoring uses blob: media/img URLs
//   - The WebRTC signalling channel needs a stun: entry in connect-src
//     (Chromium enforces connect-src against ICE server connections)
//
// If Backend/public's HTML ever changes (new inline <script>, a new CDN),
// recompute the SHA-256 hash of the exact inline script text and add it
// below, or the new script will silently fail to run under this CSP.
// ---------------------------------------------------------------------------
const helmet = require('helmet');

const INLINE_SCRIPT_HASHES = [
  "'sha256-9B6q4G6iNh+vJOPinKXbaPxvAZUq09llrmjj5ZrhgCs='", // theme-before-paint script (index.html + start.html)
  "'sha256-cST9ac0pVBescY2+UglC1uRD/XrgxS8S2MDc1iL0kYs='", // pdfjsLib.GlobalWorkerOptions.workerSrc (index.html)
  "'sha256-TZuw67DAYPkmjMyayKQHhOJeU6cPJ2x3INXyaARfJCA='", // light/dark toggle script (start.html)
];

function buildSecurityHeaders() {
  return helmet({
    contentSecurityPolicy: {
      directives: {
        defaultSrc: ["'self'"],
        scriptSrc: ["'self'", 'https://cdnjs.cloudflare.com', ...INLINE_SCRIPT_HASHES],
        workerSrc: ["'self'", 'https://cdnjs.cloudflare.com', 'blob:'],
        styleSrc: ["'self'", "'unsafe-inline'", 'https://fonts.googleapis.com'],
        fontSrc: ["'self'", 'https://fonts.gstatic.com'],
        imgSrc: ["'self'", 'data:', 'blob:'],
        mediaSrc: ["'self'", 'blob:'],
        connectSrc: ["'self'", 'ws:', 'wss:', 'stun:stun.l.google.com:19302'],
        objectSrc: ["'none'"],
        baseUri: ["'self'"],
        formAction: ["'self'"],
        frameAncestors: ["'none'"], // clickjacking protection (also covered by X-Frame-Options below)
        upgradeInsecureRequests: process.env.NODE_ENV === 'production' ? [] : null,
      },
    },
    // Helmet sets X-Frame-Options: SAMEORIGIN by default; frame-ancestors
    // 'none' above is stricter and takes precedence in modern browsers, but
    // we keep both for older browsers that only understand X-Frame-Options.
    crossOriginEmbedderPolicy: false, // would block the cross-origin cdnjs script/worker loads above
    crossOriginResourcePolicy: { policy: 'cross-origin' },
  });
}

module.exports = { buildSecurityHeaders };
